### ISSUE TITLE
Allowing the parser to return HTML comments

### ISSUE THREAD

**Issue by paulstatezny** [surface-ui/surface#258]
When SurfaceFormatter re-writes Surface code to format it, it's not aware of HTML comments because the Surface parser doesn't return them. Are there any options that would allow SurfaceFormatter to see HTML comments returned by the parser?

```
<!-- Comments like these -->
```

Thanks!

**Comment by msaraiva** [comment]
Hi @paulstatezny! 

We should change the parser to allow that. Although Surface ignores it, it can be very useful for tools like your formatter. I believe it would be a matter of just creating a new `AST.Comment` node and then handling it later by just dumping its content as it is. 

@lnr0626 do you see any possible issue if we go this direction?

**Comment by lnr0626** [comment]
I don't see any issues with that, some additional options:

* update the parser to return a tuple for comments with some indication that they're a comment (e.g.`{:comment, "<!-- Comments like these -->"}`), throw these away in `Surface.Compler.convert_node_to_ast` - iirc the formatter uses the parser, not the compiler, so this would accomplish what we need for the formatter to preserve comment
* update the parser to treat an html comment like text, and just pass it along via `AST.Literal`, this may require some additional changes to the code to be able to treat comments like whitespace and so would imo be less idea than a dedicated `AST.Comment`, but slightly more trivial

**Comment by msaraiva** [comment]
@lnr0626 I like the first one. You're right. We don't need to convert comments as AST. Let's just get rid of them before 👍

**Comment by msaraiva** [comment]
@paulstatezny if we go with the `{:comment, "<!-- Comments like these -->"}` approach, that means you'll have to worry about placing the comment as well, which includes respecting the new calculated indentation of the parent node and maybe something else I'm not aware of. Is that desided? Or it would be better to just leave comments untouched?

**Comment by msaraiva** [comment]
@paulstatezny BTW, until we have our solution ready, in case you want to give the user a workaround, I believe using `<#Raw>` would be the easiest way. Like:

```
<#Raw><!-- I will stay here no matter what --></#Raw>
```

Then after the fix, it would be easier for them to search for `<#Raw><!--` and remove the `<#Raw>...</#Raw>`

**Comment by paulstatezny** [comment]
@msaraiva Yes that's totally fine if the formatter has to decide how much to indent. It's already re-calculating that for every node to ensure children are indebted 2 spaces from their parent.

**Comment by msaraiva** [comment]
> What do you mean by "leaving the comments untouched"?

It means they would be treated as regular text, possibly concatenated with other chunks of text too. You wouldn't be able to distinguish them unless you parse it again.

**Comment by paulstatezny** [comment]
@msaraiva That's an excellent idea using `<#Raw>` for the time being. I'll suggest that in the docs instead of the interpolated Elixir comments method.

And about keeping comments inside text nodes, I think the formatter can make that work too. It'd be extra work, but I'll be glad to go with it if y'all think that's best for the parser.

**Comment by lnr0626** [comment]
I prefer the `{:comment, ...}` approach, as it allows us to ignore them fairly easily in the compiler for now, and if we found the need to keep them around down the road, could easily be extended to put them in either an `AST.Literal` or an `AST.Comment` node. It also sounds like it'd be easier to handle in the formatter
