### ISSUE TITLE
Add a new `reject_nil` option to `prop` macro

### ISSUE THREAD

**Issue by msaraiva** [surface-ui/surface#270]
Currently, there's some confusion about how the `required` and `default` option work. For instance, when defining:

```elixir
prop data, :list, default: []
```

the default value `[]` will only be set if the prop is not explicitly passed. If the prop is passed as `nil`, it will be kept as `nil`. Although this makes sense as `nil` can be a valid/expected value, I've noticed a lot of people (including myself) designing components expecting the value will never be `nil`, which may lead to runtime errors. I noticed this happening a lot when working with the playground as it now allows us to set `nil` values for some of the props.

~So should we consider extending the API to allow defining props in a way that they should never be initialized as `nil`? My first idea is:~

~Add a new `default!` option:~

```elixir
prop data, :list, default!: []
```

~Unlike `default`, this one would set the default value even if the value is passed explicitly as `nil`.~

**UPDATE**: The `default!` idea is not applicable.

@lnr0626 @Malian @olivermt any other suggestion/thoughts?

**Comment by Malian** [comment]
My first thought is that it will be confusing. I believe developpers will not understand why when passing `prop="nil"` it will not work as expected.

What about following these rules (1) when a prop is not set we use the default value, (2) when a prop is set, even if it is nil, we should use the given value?

**Comment by msaraiva** [comment]
@Malian that's the current behaviour and I believe it's correct. Maybe I'm just overthinking this now because with the catalogue I can easily set a prop value as `nil`, which may crash the playground if the code doesn't expect that `nil`. As far as I can see, 8 out of 10 components don't do that. It seems that using `required` or `default` alone it's not enough to describe the intention. Maybe what we're missing is a way to describe the type better. I guess if we could do something like:

```elixir
prop data, :list | nil
```

then it would be explicit that the code handles `nil` values properly. Otherwise, it doesn't and the user and the catalogue would be aware of that, allowing the playground to provide a more assertive message instead of just crashing.

**Comment by olivermt** [comment]
I don't think you can fix this, because required should always have the KEY present, but the value can be nil.

If you do choose the default! way, you need to differentiate between key present and value = nil, beacuse foo={{nil}} should still be possible, even with default!

**Comment by lnr0626** [comment]
We could add something new like `reject_nil` that set the default value when the prop was nil

**Comment by msaraiva** [comment]
@olivermt yeah, the `default!` option is not applicable, we should never override a passed value. What we need is just a way to inform that the component can (or cannot) handle the prop as `nil`. So instead of setting the value, we could just raise a runtime error like:

```
** (RuntimeError) prop "data" cannot be nil
```

which is way more assertive then what we get today:

```
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom
```

Since none of those error messages will mention the root of the problem is that the prop `data` is `nil`, the user needs to dig into the components code to find out what's going on. It can be even worse if the error happens down the stack.

As a bonus, the catalogue can retrieve that information and enable/disable setting `nil` on the playground prop editor.

@lnr0626 I like `reject_nil` as it keeps the semantics of `required` (unlike the `enforce`  + `require` idea).

**Comment by msaraiva** [comment]
I wonder, however, if we should use `allow_nil` instead of `reject_nil` :)

**Comment by lnr0626** [comment]
hmm, this feels like something i'd expect to be opt-in instead of opt-out to me

**Comment by Malian** [comment]
I have the same opinion as @lnr0626. From my point of view I prefer to "allow" a behaviour instead of reject it.

**Comment by miguel-s** [comment]
Late to the party but I agree with @lnr0626 and @Malian to "allow" this behaviour. In my own code I rarely expect `nil` when setting a type on a prop, especially so when I also set a default value.

**Comment by msaraiva** [comment]
I decided to close this issue. It seems it's not as relevant as I thought. Let's expect component authors to handle `nil` values properly then. Is this issue comes up in the future we can reopen it for discussion. Thanks for the inputs!
