### ISSUE TITLE
Generated documentation should also exposes doc for slot

### ISSUE THREAD

**Issue by Malian** [surface-ui/surface#293]
Currently, Surface only generates the documentation for props. We should add proper documentation for `slot` as it is part of the component API.

As `data` is private, I believe we should not generate doc for `data`.

To add documentation for `slot` we should update this part of the code:

https://github.com/surface-ui/surface/blob/2ec6c816e388f842a0254415831250908dc4499f/lib/surface/api.ex#L458-L488

**Comment by msaraiva** [comment]
@Malian I'm actually thinking about removing this feature. It was nice to have it at first but now I'm forced to remove that generated part every time I need to retrieve the docs for the website or for catalogue.

**Comment by Malian** [comment]
> @Malian I'm actually thinking about removing this feature. It was nice to have it at first but now I'm forced to remove that generated part every time I need to retrieve the docs for the website or for catalogue.

I understand and as I can see you also have to remove the `## examples` sections. If we remove this feature it means that neither exdoc nor the terminal helper `h` will provide that documentation. This is a shift away from the traditional use of the Elixir documentation system and I fear it will confuse the developers. It sounds like the dev will have to choose between Surface Catalogue and ExDoc, but not both.

**Comment by msaraiva** [comment]
@Malian I remember there were plans to allow ExDoc to create custom sections based on metadata. That means we could add additional sections like "Properties", "Slots", etc. that would be presented just like "Types" and "Functions". I'll check if this is still on the roadmap to be introduced anytime soon. If so, we could remove it and start working on exposing those metadata.

**Comment by msaraiva** [comment]
@Malian the feature I mentioned is already available but unfortunately is not what I thought it was. It can group information only if it's related to a function or macro. Example:

https://github.com/elixir-lang/elixir/blob/master/lib/elixir/docs.exs#L5
https://hexdocs.pm/elixir/Kernel.html#module-guards

So if we don't want to have to choose between Surface Catalogue and ExDoc, we need to keep adding the information in the docs and removing it later. I hate to do that but it seems it's the only way. 

Question: do you think it's worth adding also a separate section for events to keep it consistent with the website/catalogue?
