### ISSUE TITLE
Add  `mix surface.new` task

### ISSUE THREAD

**Issue by msaraiva** [surface-ui/surface#30]
Similar to `mix phx.new`. Probably with the same options.

**Comment by lnr0626** [comment]
some tasks similar to phx.gen.live for the components would also likely be useful to have

**Comment by aleDsz** [comment]
I think it should be in a separated project like [Phoenix](https://github.com/phoenixframework/phoenix/tree/master/installer) and [Nerves](https://github.com/nerves-project/nerves_bootstrap) do

**Comment by jprincipe** [comment]
I have a [demo repo](https://github.com/jprincipe/surface_demo) where I ran
```elixir
mix phx.gen.live Accounts User users name:string age:integer
```

I then converted my all the generated live views and components into surface views and components.  I'd like to use this as a template to implement a `mix surface.gen.live` task.  This is my first go at using Surface so I'd appreciate another set of eyes on this to make sure I'm starting from a solid base.

**Comment by jprincipe** [comment]
> I think it should be in a separated project like [Phoenix](https://github.com/phoenixframework/phoenix/tree/master/installer) and [Nerves](https://github.com/nerves-project/nerves_bootstrap) do

I agree here... it needs to be separate in order to have knowledge about Surface to generate the project

**Comment by msaraiva** [comment]
> I have a [demo repo](https://github.com/jprincipe/surface_demo) where I ran

@jprincipe this looks nice! I think it can be a great starting point.

One question. Are there more variations of the generated code that depends on options that may be been passed by the user?

Thanks!

**Comment by aleDsz** [comment]
Also, maybe it's time to move this repo to an org?

**Comment by jprincipe** [comment]
> > I have a [demo repo](https://github.com/jprincipe/surface_demo) where I ran
> 
> 
> 
> @jprincipe this looks nice! I think it can be a great starting point.
> 
> 
> 
> One question. Are there more variations of the generated code that depends on options that may be been passed by the user?
> 
> 
> 
> Thanks!

Thanks for the feedback @msaraiva

I'm planning on replicating all the different options that are supported in `phx.gen.live`.  Just wanted to use this as a sanity check and for reference as I build out the task.

**Comment by msaraiva** [comment]
I don't think anyone will have the time to work on this in the near future so I'm closing it. In case anyone gets some spare time and wants to play with this, feel free to reopen it.
