### ISSUE TITLE
Global properties, eg @flash

### ISSUE THREAD

**Issue by ewildgoose** [surface-ui/surface#301]
Hi, I think this is a simple yes or no proposal. Should Surface support "globals", eg @flash? I can see there is some stub support for a property called "flash" (and this prevents any component creating a :flash property), however, it doesn't seem to be wired up?

So, a) is there any use case for a global property? b) Is there any desire for a preset top level context that gets initialised with certain params such as @flash ?

I have no idea what other frameworks do. I think this is easily shut down with a no and close the issue though? (However, a few thoughts on clever ways to handle global type concerns such as @flash would be useful in the docs I think?  Thanks)

**Comment by Malian** [comment]
@ewildgoose Thank you for creating this issue!

> Hi, I think this is a simple yes or no proposal. Should Surface support "globals", eg @flash? I can see there is some stub support for a property called "flash" (and this prevents any component creating a :flash property), however, it doesn't seem to be wired up?

What do you mean be "is not wired up" ? Do you mean that you are able to create a `flash` property in one of your components or something else?

> So, a) is there any use case for a global property? b) Is there any desire for a preset top level context that gets initialised with certain params such as @flash ?

There is the notion of [Context](https://surface-ui.org/contexts). It allows you to initialize some kind of context before using a component. Does it answer your questions?

May I ask you if you have a concrete example to share with us that will help us to have a global view of what you have in mind ?

**Comment by ewildgoose** [comment]
Hi, yes, in component.ex and live_component.ex we have:

```
      @doc "Built-in assign"
      data flash, :map
```

And in helpers.ex we have

```
  @builtin_common_assigns [
    :socket,
    :flash,
    :__context__,
    :__surface__
  ]
```

This prevents you making a property in any custom component called "flash".

However, at least in the version of surface I'm using (which I concede isn't the very latest), it does not pull from the top level assigns either, ie if you want to see the global @assigns.flash, then you need to:
a) create a custom property, or add code to stash it in a context
b) that custom property CANNOT be called flash (as this is reserved by the data stanza shown above)

It looks almost as though someone original wanted there to be a magic property called "flash" that gets passed to all components, but didn't quite finish the coding? Is this the desire?

I've phrased the question in the more general sense: Do we want there to be a way to create "magic properties" that apply to all components? Whether this is via some way to pre-initialise the top level context of all components, or through some ability to set properties that apply to all components, globally? Or should we go the other way and remove the "data properties()" and demand that components handle this themselves? Both seem fine directions to me - I can definitely see a use for "magic global properties" though?

**Comment by lnr0626** [comment]
To the more general question: We previously played around with a slightly different version of `Context` that was similar; however, settled on the current approach as there are fewer edge cases. I /think/ that should be able to handle most cases of magic/global properties (though I haven't played with them too much lately). The context stuff (as well as any global variable type thing) also has implications for change tracking

The `:flash` assign is referencing phoenix's flash assign, we haven't tried to implement anything specific for the flash assign. However, since that's only automatically added in a `LiveView`, we shouldn't be preventing assigns named `flash` in components.

**Comment by msaraiva** [comment]
@ewildgoose is right. We shouldn't have `flash` in  `Component` nor `LiveComponent`. It's up to the user how to send the parent flash to the component. You may want to pass it as a prop or using the context or even use another name for it as mentioned [here](https://elixirforum.com/t/liveview-flash-assigns-not-available-in-child-livecomponent/29558/4). The only value that is automatically handled is the one in the LiveView so I think it's ok to keep it.

**Comment by ewildgoose** [comment]
I don't want to re-open this and create noise, but I wanted to note one other use-case for "globals". Sometimes due to the structure of HTML it can be difficult to do a "modal" effect through a single component. For example as implemented in bootstrap you need one component at the top level to darken the background and another (likely elsewhere in the html structure) to actually show the modal itself.  Usually js is used to toggle the background from the "component" implementing the modal, but this does feel like a hack to cross boundaries. It could be rather complicated to implement this only using surface features and no js?

I can't think of many other use cases (other than flash), but I wonder if other technologies have some kind of "global" context that could be used to cleanup such implementations?
