### ISSUE TITLE
Warn on duplicated props without accumulate: true

### ISSUE THREAD

**Issue by nduitz** [surface-ui/surface#302]
Hey there,
I think it might be helpful to raise a compile error in case of passing duplicated props or slots to a component.
Additionally the current behavior varies between props and slots:
```
defmodule MyApp.Components.Modal do
  use Surface.LiveComponent

  slot header
  prop paragraph, :string

  def render(assigns) do
    ~H"""
    <div>
      <slot name="header" />
      <p>@paragraph</p>
    </div>
    """
  end
end
```

```
<Modal paragraph="one" paragraph="two">
  <template slot="header">
    <p>one</p>
  </template>
  <template slot="header">
    <p>two</two>
  </template>
</Modal>
```

This example would render the `Modal` with `paragraph=two` but with the `header-slot = one`.

I will try to submit a PR on this topic if people agree with this proposal (might take me some time though).

**Comment by Malian** [comment]
@nduitz Thank you for creating this issue.

Multiple slots is a valid behaviour especialy with [Renderless Component](https://surface-ui.org/slots#renderless-components). For example, the following components (extracted from the doc) are valid and the Grid component accepts multiple slots that have the same name, `cols`. You can access these slots with the assign variable `@cols` and loop over it.

```elixir
  defmodule Column do
    use Surface.Component, slot: "cols"

    @doc "The field to be rendered"
    prop field, :string
  end

  defmodule Grid do
    use Surface.Component

    @doc "The list of items to be rendered"
    prop items, :list, required: true

    @doc "The list of columns defining the Grid"
    slot cols

    def render(assigns) do
      ~H"""
      <table class="table is-bordered is-striped is-hoverable is-fullwidth">
        <thead>
          <tr>
            <th :for={{ col <- @cols }}>
              {{ Phoenix.Naming.humanize(col.field) }}
            </th>
          </tr>
        </thead>
        <tbody>
          <tr :for={{ item <- @items }} class={{ "has-text-warning": item[:selected] }}>
            <td :for={{ col <- @cols, field = String.to_atom(col.field) }}>
              {{ item[field] }}
            </td>
          </tr>
        </tbody>
      </table>
      """
    end
  end

  defmodule Example do
    use Surface.LiveComponent

    data albums, :list, default: []

    def mount(socket) do
      {:ok, assign(socket, albums: [
        %{name: "The Dark Side of the Moon", artist: "Pink Floyd", released: "March 1, 1973"},
        %{name: "OK Computer", artist: "Radiohead", released: "June 16, 1997"},
        %{name: "Disraeli Gears", artist: "Cream", released: "November 2, 1967", selected: true},
        %{name: "Physical Graffiti", artist: "Led Zeppelin", released: "February 24, 1975"}
      ])}
    end

    def render(assigns) do
      ~H"""
      <div>
        <Grid items={{ @albums }}>
          <Column field="name" />
          <Column field="artist" />
          <Column field="released" />
        </Grid>
      </div>
      """
    end
  end
```

That being said, I recognize we could be more explicit when we allow this behaviour like we do with `props` and the `:accumulate` option that instructs Surface to group all different values provided for a property into a single list.

For example:
```elixir
  # Component
  defmodule Accumulator do
    use Surface.Component

    prop acc, :string, accumulate: true

    def render(assigns) do
      ~H"""
      <ul>
        <li :for={{ str <- @acc }}>{{ str }}</li>
      </ul>
      """
    end
  end

 # Usage
  <Accumulator acc="hello" acc="world" acc="!" />
 
 # Result
  <ul>
    <li>hello</li>
    <li>world</li>
    <li>!</li>
  </ul>
```
If you do not set the `:accumulate` option to `true` like in your example, the last value will override the previous one. This is why `<Modal paragraph="one" paragraph="two">` use `two` for the `paragraph` prop.

You are right when you say that the behaviour is not consistent between `props` and `slots`. I believe we should fix that. This brings up several suggestions:
* Warn when props are specified multiple time but the accumulate option is not set to true
* Being more explicit if the api allows multiple time the same slot name by adding an `accumulate` option to `slot`
* Warn when multiple `slots` are used but the `accumulate` option is not set to true
* In case of several slots with the same name, use the last value to be consistent with what we do with `slot`

@nduitz @miguel-s @lnr0626 @msaraiva what do you think of this plan? Do you see edge cases?

**Comment by nduitz** [comment]
@Malian 
Thank you for your response.

I saw the possibility to use a slot multiple times while digging in the code. So I think you are absolutely right that `slots` should be marked explicitly as `accumulate: true` if intended, making it easier to determine to warn or not.

**Comment by msaraiva** [comment]
Regarding props, I agree we should emit a warning or even an error if there's more than one defined and `accumulate` is `false`.  This validation makes sense since the value can be either a list or an unwrapped value. This mimics the same behaviour we can find in some other places in Elixir, e.g. `Module.put_attribute/3`. 

For slots, however, I believe we should always have them as lists as it makes the implementation much more consistent and its use more predictable (it's similar to the way most other implementations work). I might be wrong though :)

**Comment by lnr0626** [comment]
I definitely agree that we should emit at least a warning if props are specified multiple times, but `accumulate` is false

For slots, I'd agree we should always treat them as lists as the implementation is much simpler that way. I think the confusion may be arising because we allow `<slot name="<name>" />` as short hand for `<slot name="<name>" index="0" />`. Would adding some additional documentation about this help?

**Comment by miguel-s** [comment]
> ... we allow `<slot name="<name>" />` as short hand for `<slot name="<name>" index="0" />`

I've been using this without ever knowing that's how it actually works 😮 Some documentation around this would be really nice 👍

**Comment by msaraiva** [comment]
> Would adding some additional documentation about this help?

Yeah, I believe so! 👍

Ok. That leave us with two thing to do:

1. Add a warning if props are specified multiple times, but `accumulate` is `false`
2. Update the docs to inform that slots are always lists and `<slot name="<name>" />` is just a short hand for `<slot name="<name>" index="0" />`

**Comment by msaraiva** [comment]
I updated the title of this issue and created a new one at https://github.com/surface-ui/surface_site/issues/19 for the docs.
