### ISSUE TITLE
Add a \n at every step of a :for directive to render html properly

### ISSUE THREAD

**Issue by Malian** [surface-ui/surface#303]
I was replying to #302 and to validate my comment I wrote the following test to validate the behaviour of the `accumulate` prop option.

```elixir
## COMPONENT

  defmodule MyComponentWithAccumulateProp do
    use Surface.Component

    prop acc, :string, accumulate: true

    def render(assigns) do
      ~H"""
      <ul>
        <li :for={{ str <- @acc }}>{{ str }}</li>
      </ul>
      """
    end
  end

## TEST

    test "accumulate property" do
      html =
        render_surface do
          ~H"""
            <Surface.PropertiesTest.Components.MyComponentWithAccumulateProp
              acc={{ "hello" }}
              acc={{ "world" }}
              acc={{ "!" }}
            />
          """
        end

      assert html == """
             <ul>
               <li>hello</li>
               <li>world</li>
               <li>!</li>
             </ul>
             """
    end
```

Unfortunately the test didn't pass
```bash
  1) test accumulate accumulate property (Surface.PropertiesTest)
     test/properties_test.exs:560
     Assertion with == failed
     code:  assert html == "<ul>\n  <li>hello</li>\n  <li>world</li>\n  <li>!</li>\n</ul>\n"
     left:  "  <ul>\n  <li>hello</li><li>world</li><li>!</li>\n</ul>\n"
     right: "<ul>\n  <li>hello</li>\n  <li>world</li>\n  <li>!</li>\n</ul>\n"
     stacktrace:
       test/properties_test.exs:572: (test)
```

To make the test pass I had to write one of the following:
```elixir
      assert html == """
               <ul>
               <li>hello</li>\
             <li>world</li>\
             <li>!</li>
             </ul>
             """

      assert html =~ """
               <ul>
               <li>hello</li><li>world</li><li>!</li>
             </ul>
             """
```

After few investigations, I have seen this way of working several times in the tests. ([here](https://github.com/surface-ui/surface/blob/master/test/properties_test.exs#L510-L512), [here](https://github.com/surface-ui/surface/blob/master/test/directives_test.exs#L387-L405) and [here](https://github.com/surface-ui/surface/blob/master/test/directives_test.exs#L461-L468) for example)

Maybe I miss something but from a DX I expect to be able to test the expected output without those white spaces issue :grin: WDYT?

Note: It is maybe because a do not place the component on the same column as the `"""`?

**Comment by miguel-s** [comment]
> Note: It is maybe because a do not place the component on the same column as the """?

Yes, you're basically adding two whitespaces to the start of each line. Took me a while to get used to not indenting inside `~H` 😅

> Maybe I miss something but from a DX I expect to be able to test the expected output without those white spaces issue 😁 WDYT?

Having more readable tests would be a plus for me. However, as far as I could see Phoenix HTML does not add any whitespaces or newlines, does anybody know if there's a reason for that? [Example](https://github.com/phoenixframework/phoenix_html/blob/57b8d8336cca4966d74ddf74466a83b09f6b621b/test/phoenix_html/form_test.exs#L889)

**Comment by msaraiva** [comment]
Whenever using `"""`, no matter if it's with `~H` or not, you should never ident the text unless you want to add those extra spaces. It also always adds an `\n` at the end unless you add a `\` at the end of the last line or you use the other `~H` variants like `~H"..."` or `~H(...)`. I believe we could change this behaviour by passing `trim: true` to the compiler but I haven't tested yet so I'm not sure it would behave as we expected.

https://hexdocs.pm/eex/EEx.html#module-options

**Comment by Malian** [comment]
I have updated the code and removing the extra spaces:

```elixir
## Component
    def render(assigns) do
      ~H"""
      <ul>
        <li :for={{ str <- @acc }}>{{ str }}</li>
      </ul>
      """
    end

## Test
      assert html =~ """
             <ul>
               <li>hello</li>\
               <li>world</li>\
               <li>!</li>
             </ul>
             """
```

But the test still does not pass due to "extra" spaces between `<li>`:

```bash
  1) test accumulate accumulate property (Surface.PropertiesTest)
     test/properties_test.exs:560
     Assertion with =~ failed
     code:  assert html =~ "<ul>\n  <li>hello</li>  <li>world</li>  <li>!</li>\n</ul>\n"
     left:  "<ul>\n  <li>hello</li><li>world</li><li>!</li>\n</ul>\n"
     right: "<ul>\n  <li>hello</li>  <li>world</li>  <li>!</li>\n</ul>\n"
     stacktrace:
       test/properties_test.exs:574: (test)
```

If I remove the `\`, it works as expected:
```elixir
      assert html =~ """
             <ul>
               <li>hello</li><li>world</li><li>!</li>
             </ul>
             """
```
I have to write the `<li>` on the same column as the closing tag:

```elixir
      assert html =~ """
             <ul>
               <li>hello</li>\
             <li>world</li>\
             <li>!</li>
             </ul>
             """
```
> Having more readable tests would be a plus for me. However, as far as I could see Phoenix HTML does not add any whitespaces or newlines, does anybody know if there's a reason for that?

I don't think we should do anything different from what Phoenix is doing, so I suggest keeping tests as it is.

**Comment by Malian** [comment]
I close this issue for the moment as we already have a solution that works and is aligned with Phoenix. Feel free to reopen it if needed.
