### ISSUE TITLE
Warn if a slot is defined but not used in the template

### ISSUE THREAD

**Issue by Malian** [surface-ui/surface#304]
Today the following code is valid:

```elixir
defmodule ComponentWithDeclaredButUnusedSlot
  use Surface.Component

  slot default
  slot header

  def render(assigns) do
    ~H"""
    <div />  
    """
  end
end
```

I believe we could warn the user to avoid unnecessary code with a simple message like the following:

> "The slot `default` is defined but not used in the template. Hint: Remove the `slot default` line or add a slot in the template `<slot name="default"></slot>`"

**Comment by msaraiva** [comment]
@Malian we have discussed this in the past and the problem is that if we want to make sure the code does not use the slot, we'll need to traverse every expression/interpolation inside `~H` and check if it doesn't use `@the_slot_name` nor `assigns[:the_slot_name]`. So I'm not sure if it's worth it.

**Comment by Malian** [comment]
@msaraiva I'll close the issue. I believe we could live without this warning as it does not affect the code.
