### ISSUE TITLE
Add `as` or `element` prop to `<#Markdown>`

### ISSUE THREAD

**Issue by sodapopcan** [surface-ui/surface#306]
Hi!

I was wondering if you would be amenable to adding an `as` or `element` prop to `<#Markdown>`.  As it stands it can only be rendered as a `<div>` but I would like to be able to render it as an arbitrary element (like `section` or `article`, for example).

What do you think?  I'd be happy to do the work if you're ok with it, I just thought I would ask first.

Thanks!  And thanks for Surface—it's so great.

e.g.

```surface
<#Markdown as="article">
  ### Title
</#Markdown>
```

**Comment by msaraiva** [comment]
Hi @sodapopcan!

I think it's a great idea. We could even call it `container` and allow passing a tuple, e.g. `{:div, class: ..., style: ...}`, just like when defining a [Phoenix.LiveView](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#__using__/1). However, for now, we could accept just a string or atom that allows replacing the node name and then, if necessary, we can add support for tuples in the future. The user can always use the `unwrap` property to remove the root container and wrap the markdown with any custom markup required.

WDYT? 

A PR would be very welcome!

**Comment by sodapopcan** [comment]
Oh boy, I totally overlooked the `unwrap` property.  On one hand, this is sufficient to solve my problem.  On the other, it does add a level of indentation to my otherwise cruft-free Surface template, so I would still advocate for a new prop (which you seem very open to!)

I was also unaware of the `container` option for LiveView.  I personally can't think of a time I would use this for markdown, though it probably exists.  The main reason I like `as` is because it's nice and short which is nice if you end up with repeated `<#Markdown />`s in a template, though that's probably rare (In my current case, I have a grid layout where I have a repeated `<img /><#Markdown />`s).  I'm perfectly happy to go with `container` over advocating for `as` since it allows for extending it to be like LiveView's `container` option.

**Comment by msaraiva** [comment]
I'm closing this since the `unwrap` prop solves the issue.

@sodapopcan  we're extracting the Markdown component to https://github.com/surface-ui/surface_markdown. Feel free to open an issue there if you face any other problem.

Thanks!
