### ISSUE TITLE
Extract the Markdown component to its own project

### ISSUE THREAD

**Issue by schnittchen** [surface-ui/surface#310]
If I'm right about this, this is the only reason for the earmark dependency. Since probably most people won't need it, consider extracting the component into its own hex package (there may be other ways to accomplish the same)...

**Comment by Malian** [comment]
@msaraiva I am in favour of this extraction. I do believe we should do the same with the `Code` Macro Component from the `surface_site` repository after some refactoring. WDYT?

**Comment by msaraiva** [comment]
Is the idea to create a separate `surface_markdown` project or something more generic? The `Code` component, for instance, does not depend on markdown.

**Comment by Malian** [comment]
> Is the idea to create a separate `surface_markdown` project or something more generic? The `Code` component, for instance, does not depend on markdown.

The idea is to create a `surface_markdown` repository to remove the earmark dependency from Surface as it is not needed in Surface except for that component that I suspect it is not, or it will not be, used so often. In my projects for example, I do not use it.

**Comment by msaraiva** [comment]
I agree. Let's extract it then 👍
