### ISSUE TITLE
defcomponent

### ISSUE THREAD

**Issue by batate** [surface-ui/surface#318]
Is there any interest in: 

```elixir
defmodule PageLive do
  use Surface.Component
  defcomponent Title, props: [title: :string]

...

  def render(assigns) do
    ~H"""
      <Title message="hi">
    """
  end
end
```
  
in title.sface: 

```html
<h1>{{ @message }}</h1>
```

removing the need for the boilerplate for a component module for stateless components?

**Comment by msaraiva** [comment]
Hi @batate!

The short answer is yes! We have even discussed something in that direction here: https://github.com/surface-ui/surface/issues/1#issuecomment-710040032.

However, we're waiting for a few nice changes in LV's API that should be out soon to move forward with that idea. Those changes will have a direct impact on the implementation.

I'll keep you updated :)

**Comment by batate** [comment]
Excellent. I'll wait and watch. Feel free to close this one and track the progress in the referenced pr if desired.
