### ISSUE TITLE
Do not encode literal strings passed as attributes

### ISSUE THREAD

**Issue by derek-zhou** [surface-ui/surface#323]
If I have HTML entities in the sface text, they are not converted. eg: `&#x1f527;` will come out as is. not as `🔧`

I know .sface is not really HTML, but it pretends to be an extended HTML, so people may paste HTML code in with surprising results. Other similar technologies, such as Svelte, correctly mimics the HTML behavior and converts HTML entities.

I am not sure whether it should be changed, though. It is a backward incompatible change. Maybe this behavior shall just be documented.

**Comment by msaraiva** [comment]
Hi @derek-zhou!

How are you injecting `&#x1f527;` in your code? It works just fine for me:

![image](https://user-images.githubusercontent.com/457237/113509060-e7cb7300-9529-11eb-9284-ba0f2fe55c59.png)

**Comment by derek-zhou** [comment]
As an attribute to an html tag

**Comment by msaraiva** [comment]
Attribute values are always encoded unless you explicitly use `raw/1`:

```jsx
<div title={{ raw("This will be kept as it is: &#x1f527;") }}>
```

**Comment by derek-zhou** [comment]
So the behavior will be:
* literal string shall take html entity
* interpolated string shall be encoded

Right?

**Comment by msaraiva** [comment]
Yup. We should keep the behaviour as close to HTML as possible when handling vanilla HTML markup.
