### ISSUE TITLE
Defining temporary assigns

### ISSUE THREAD

**Issue by yusufyildirim** [surface-ui/surface#324]
Hi,

I've been finding myself overriding the `mount` callback to specify my `data` assigns as `temporary`. I think it would be convinient if we could just specify something like `temporary: true` as a option or `temporary_data` as a new keyword to avoid this. Latter would require much more work I assume and it would probably be better not to introduce a new keyword for everything 😄 

I digged the code a bit and It didn't looked hard to me but I'm a newbie 😄 , what do you think? Can we do this?

**Comment by Malian** [comment]
Hi @yusufyildirim ! Thank you for the suggestion.

From the doc, temporary assigns will be reset to a default value after each update.
>By default, all LiveView assigns are stateful, which enables change tracking and stateful interactions. In some cases, it's useful to mark assigns as temporary, meaning they will be reset to a default value after each update. This allows otherwise large but infrequently updated values to be discarded after the client has been patched.

So, I do not understand what you have in mind with `temporary: true` option. What will be the default value of this assign after each update ? 

Could you share a piece of code where you are overriding the `mount` function to specify your temporary assign? It will help us to have a big picture of what you are trying to do. Thanks !

**Comment by yusufyildirim** [comment]
> From the doc, temporary assigns will be reset to a default value after each update.

Yes, exactly! I have to specify a `data assign` as temporary to achieve this. This is how I do it right now:

```elixir
data orders, :list, default: []

def mount (_params, _session, socket) do
{:ok, socket, temporary_assigns: [orders: []]
end
```

I'd prefer just turning the code above into this:

```elixir
data orders, :list, default: [], temporary: true
```

Since we know that `data assigns'` default value and we know it should be temporary, we'd be able to define this `temporary_assigns` implicitly -under the hood- and  no `mount` overriding would be necessary at all.

**Comment by msaraiva** [comment]
This is something that crossed my mind a couple of times when dealing with temporary assigns. However, I'm not sure we should assume the reset value to be always the default value.  My concern is that the user might expect that `default` will only be used as an initial value, not the value after reset. 

I confess I've never faced such a scenario.  Whenever I used temp assigns, it always starts with and gets reset to `[]`. 

Do you see any other possible use case? Should we worry about them? After all, the user can always use `mount` to customize it.

**Comment by yusufyildirim** [comment]
> Whenever I used temp assigns, it always starts with and gets reset to []

Same, but your concern is valid too.

I think we can introduce a flexible solution for that by just adding an option like `reset_to` and that option can be any value just like `default`. So, we won't have to worry about any case because the user can define the reset value directly what he/she wants.

```elixir
data orders, :list, default: [], reset_to: nil
```
-- or --
```elixir
data orders, :list, default: [], reset_to: []
```

We can stick to the previous `temporary: true` kind of implementation too, it's enough as is. Wording can be definitely different but these are the suggestions that came to my mind without any thinking effort 😄  WDYT?

**Comment by Malian** [comment]
> I confess I've never faced such a scenario. Whenever I used temp assigns, it always starts with and gets reset to `[]`.
> 
> Do you see any other possible use case? Should we worry about them? After all, the user can always use `mount` to customize 

The Phoenix Live view [documentation](https://hexdocs.pm/phoenix_live_view/dom-patching.html#temporary-assigns) presents a use case with a chat application where you want to load only the last 20 messages

```elixir
def mount(_params, _session, socket) do
  socket = assign(socket, :messages, load_last_20_messages())
  {:ok, socket, temporary_assigns: [messages: []]}
end
```

Regarding this valid use case I am not in favour of the `temporary: true` implementation because it is a deviation from what Phoenix LIve View does, and we should stay as close as possible from it.

What about:
```elixir
data orders, :list, default: [], temporary: []
```
I believe it's not a big deal for the user, and it is more explicit.

Moreover, if Surface decides later to support a default value from a function, we will no break the api:
```elixir
data messages, :list, default: &load_last_20_messages/0, temporary: []
```

**Comment by yusufyildirim** [comment]
That was my point when I suggested `reset_to` actually. I'm okay with that 😄

**Comment by msaraiva** [comment]
Yeah, `temporary: []` looks good to me as it makes it no assumption about the `default` value.

**Comment by msaraiva** [comment]
I guess we will :)

**Comment by Malian** [comment]
@msaraiva & @yusufyildirim I gave it a try with the following syntax:
```
data messages, :list, temporary: []
```
It works as expected but I am not a fan of the current implementation.

We have to manage several cases:

- The user hasn't defined a `mount` function: Pretty straightforward to implement
- The user has defined a `mount` function that returns a tuple: `{:ok, socket}`: We have to catch it and return a tuple `{:ok, socket, temporary_assigns: __our_keywords_list__}`
- The user has defined a `mount` function that returns a tuple : `{:ok, socket, opts}`: We have to catch it and handle 2 cases:
  - There is no `temporary_keys` key: Add it
  - There is a `temporary_keys` key: What should we do? Merge both keyword list? Override it ? Let the list override ours?

It complexifies the `quoted_mount` function a lot. I will clean the code before showing it to you.

**Comment by msaraiva** [comment]
> There is a `temporary_keys` key: What should we do? Merge both keyword list? Override it ? Let the list override ours?

I think we should merge it, having any key from the user's `mount` overriding ours.

**Comment by msaraiva** [comment]
I'm closing this until we have a better picture of the new hooks system that should be introduced in LV. We can evaluate re-opening this one along with https://github.com/surface-ui/surface/pull/336 when the time comes.
