### ISSUE TITLE
Template tag restriction

### ISSUE THREAD

**Issue by yusufyildirim** [surface-ui/surface#326]
Hi,

If I'm doing something wrong, Surface doesn't let me use `<template>` tag outside it's own use-cases. I try to use [Alpine.js](https://github.com/alpinejs/alpine), I have to use `<template>` tags for some cases like [this one](https://github.com/alpinejs/alpine#x-for) but I can't because Surface compiler throws an error at me. It says: 

<img width="1624" alt="Screen Shot 2021-04-08 at 23 10 06" src="https://user-images.githubusercontent.com/22980987/114090040-93284f00-98bf-11eb-8332-5956a27c83fc.png">

It's just enough to add a `template` tag into somewhere in your HTML to get this error. Is there a workaround? Am I doing something wrong 😄?

I think we should let people use template tags somehow, if possible.

**Comment by Malian** [comment]
Hi @yusufyildirim ! The issue is known and related to #259 and #268 

We definitely should fix this.

In the meantime, could you please try this workaround, and tell us if it fix the issue?

```html
<#Raw><template></#Raw>
...
<#Raw></template></#Raw>
```

**Comment by yusufyildirim** [comment]
Oh, how did I miss that 😅 I'm sorry.

Thank you for the suggestion! 

Feel free to close the issue if you want.
