### ISSUE TITLE
Unclear why warning  `Error: cannot render <X /> (module X could not be loaded` is happening

### ISSUE THREAD

**Issue by harmon25** [surface-ui/surface#329]
Have some very inconsistent behavior when compiling/loading some component.

After a clean compile (mix clean + mix compile) the component is failing to load.

If I open the code where the component is being rendered - cut it out, recompile, paste it back, recompile, it loads fine. 😕 

There is too much code to share, and unlikely I can make a small reproduction.

I am willing to do a screen share to demonstrate the issue. I can reproduce it but after staring at the components for a couple hours, I have no clue why this would happen.

I do get warnings during compilation but they indicate `module X could not be loaded` which after copying and pasting, seems to go away.

This is also happening when building a release - which is also puzzling, as I figure all the modules would be getting loaded.

Please help!

**Comment by harmon25** [comment]
It does appear the files are being compiled - as they have corresponding `.beam` files in the _build directory... but cannot be loaded for some reason?

**Comment by harmon25** [comment]
Am able to narrow it down to - https://github.com/surface-ui/surface/blob/master/lib/surface/compiler/helpers.ex#L176

`Code.ensure_compiled/1` is returning `{:error, :unavailable}` the documentation of which states: 

> If the module being checked is currently in a compiler deadlock, this function returns {:error, :unavailable}. Unavailable doesn't necessarily mean the module doesn't exist, just that it is not currently available, but it (or may not) become available in the future.

Changing that function to this:
```elixir
  def check_module_loaded(module, node_alias) do
    case Code.ensure_compiled(module) do
      {:module, mod} ->
        {:ok, mod}
      {:error, :unavailable} ->
        {:ok, module}
      {:error, reason} ->
        message = "module #{inspect(module)} could not be loaded"

        if !String.contains?(node_alias, ".") and inspect(module) == node_alias do
          {:error, message, hint_for_unloaded_module(node_alias)}
        else
          {:error, message}
        end
    end
  end
```

Is now causing this warning:
`warning: cannot render <X> (module X is not a component)`

**Comment by Malian** [comment]
From the slack [thread](https://elixir-lang.slack.com/archives/C01220C92QM/p1617998670113000):

The docs says the following about the `ensure_compiled` function:
>  Given this function halts compilation, use it carefully. In particular, avoid using it to guess which modules are in the system. Overuse of this function can also lead to deadlocks, where two modules check at the same time if the other is compiled. This returns a specific unavailable error code, where we cannot successfully verify a module is available or not.

Gif that shows the behaviour:
![image](https://user-images.githubusercontent.com/553321/114318454-518ce380-9b0d-11eb-8ccb-fed8048cff6c.png)

**Comment by harmon25** [comment]
here is the gif - ![cannot_load](https://user-images.githubusercontent.com/6964054/114318797-9fd5be80-9adc-11eb-95a9-0a2208cdc959.gif)

**Comment by harmon25** [comment]
Removing all `handle_event/3` callbacks in the live_component fixes the problem, but does not explain why. is also not the solution i am looking for..

**Comment by Malian** [comment]
@harmon25 we should find why your component arrives in the `:unavailable` state during compilation. I would like to be able to catch this kind of error and provide the user with a better error message, if possible.

You told me the following code still produces the error:
```elixir
  def render(assigns) do
    ~H"""
     <div>
        {{__MODULE__}}
     </div>
    """
  end
```
but it seems that the error comes from elsewhere. I am not able to reproduce the bug with that piece of code.

Did you try to remove the `handle_event/3` function one by one until it the error disappears? Did you identify a function that causes in the error?

**Comment by harmon25** [comment]
Seems to load OK as a stateless `Component` instead of a `LiveComponent` . This does not solve the underlying issue but will allow me to work through it. I am using `LiveComponents` in other places without problem.

I can very easily reproduce the issue in my code - but talk about a heisenbug, it is super weird behaviour 😖 

Doing a screen share would be the most effective debugging/exploration, you could look at whatever you want, and we could try some things. I can confirm it is happening to other people on the project, and also during a release (via docker container) so is not a specific to my system, but something to do with the code/structure.

**Comment by harmon25** [comment]
With help from @msaraiva was able to narrow down this issue to the usage of a particular ecto struct that was causing the compiler deadlock. I can avoid the struct to work around the issue. 

If other folks encounter the issue - might want to re-open this.

Hopeful new elixir or surface versions will indirectly fix this deadlock. 

Thanks @msaraiva and @Malian for being patient and helping me out! 
You're both amazing!  🎉

**Comment by lucasavila00** [comment]
It happened to me.

It's really bad because tests passed but IRL the component won't render.

It also does not trigger a runtime error, but returns a string in place:
```
     <span style="color: red; border: 2px solid red; padding: 3px"> Error: cannot render &lt;Renderer&gt; (module LanceWeb.BuyRenderer.Renderer could not be loaded)</span>
```

**Comment by zkat** [comment]
@msaraiva can we reopen this? I have a reliable repro over at https://github.com/digitalworkersguild/banchan/tree/zkat/module-x-not-loaded-bug-repro that you can check out. It's definitely something similar to what @harmon25 ran into, in that when I remove the dependency on `Event`, it goes away.
