### ISSUE TITLE
If directive is not applied on slot or on slotable component 

### ISSUE THREAD

**Issue by Malian** [surface-ui/surface#331]
### Context

I am trying to dynamically render a slot base on a condition. My use case is to show a secondary column, if the user is on a `:preview` route, and not showing this column if the user is on the `:index` route. The routes point to the same Surface Live View. 

This kind of pattern is the default one when you run the `phx.gen.live ...` command from Phoenix. For example, it generates the following routes:

```elixir
live "/companies", CompanyLive.Index, :index
live "/companies/new", CompanyLive.Index, :new
```

In my case I have the following routes:
```elixir
live "/contacts", ContactsLive.Index, :index
live "/contacts/preview/:id", ContactsLive.Index, :preview
```

The `:index` route shows a list of the contacts, and the `:preview` route should add a secondary column on the right with additional information about the contact when the user clicks on the table row.

I am using a `Layout` component that manages the layout and where should go the `secondary` column and the `default` content. The render content of the light is as simple as this:

```elixir
def render(assigns) do
  ~H"""
    <div>
      <div id="main">
         <slot />
      </div>
      <slot name="secondary_column" />
    </div>
  """
end
```

I also created a `SecondaryColumn` slotable component that reduces the boilerplate code when you use the `Layout` component.

```elixir
defmodule SecondaryColumn do
  use Surface.Component, slot: "secondary_column"

  slot default, required: true

  def render(assigns) do
    ~H"""
    <aside id="secondary_column">
      <slot name="default" />
    </aside>
    """
  end
end
```

In my views, I am able to use these components like this:

```elixir
def render(assigns) do
  ~H"""
    <Layout>
      <div>
        <h1>My Main content</h1> 
     </div>
     <SecondaryColumn>
        <h2>My Secondary Content</h2>
     </SecondaryColumn>
    </Layout>
  """
end
```

### What I am trying to achieve, and what did I try?
When the layout of the view is static, I mean when I know a should have a secondary column, it works fine, but when I would like to show this column based on a condition (in my case, depending on the route but it can be any other condition), it does not work as expected.

#### `:if` directive with `<template slot="...">`
My first attempt was to use the plain old `template` tag. With this approach, the slot is always rendered, no matter the value of the condition. To be clear, if you set the `if` directive to `false` the slot is rendered anyway.  In my example, no matter the route you are on, the `slot` is displayed.

:warning: From my point of view, if it is not a bug, we should clearly inform the user that the `if` directive does not work with the `template`tag.
```elixir
def render(assigns) do
  ~H"""
    <Layout>
      <div>
        <h1>My Main content</h1> 
     </div>
     <template slot="secondary_column" :if={{ @live_action == :preview }}>
        <h2>My Secondary Content</h2>
     </template>
    </Layout>
  """
end
```

#### `:if` directive with Slotable
My second attempt was to use the `:if` directive on the SecondaryColumn slotable component. Things are interesting and surprising in this case.

1. The slot is not displayed if the condition is equal to `false` :heavy_check_mark: (In my case on the `:index` route)
2. The slot is displayed  if the condition is equal to `true` :heavy_check_mark: (In my case on the `:preview` route)
3. The slot is rendered as if it is part of the `default` slot of the `Layout` component :heavy_multiplication_x:

The following code
```elixir
def render(assigns) do
  ~H"""
    <Layout>
      <div>
        <h1>My Main content</h1> 
     </div>
     <SecondaryColumn :if={{ @live_action == :preview }}>
        <h2>My Secondary Content</h2>
     </SecondaryColumn>
    </Layout>
  """
end
```
will generate the following HTML code:
```html
    <div>
      <div id="main">
        <div>
          <h1>My Main content</h1> 
        </div>
        <aside id="secondary_column">
            <h2>My Secondary Content</h2>
        </aside>
      </div>
    </div>
```
instead of
will generate the following HTML code:
```html
    <div>
      <div id="main">
        <div>
          <h1>My Main content</h1> 
        </div>
      </div>
      <aside id="secondary_column">
        <h2>My Secondary Content</h2>
      </aside>
    </div>
```

Note that the `aside` tag should be outside the `main` as expected regarding the `Layout` render function.

#### `<If cond={{ @live_action == :preview }}>...</If>` with `<template ...>` or  `<SecondaryColumn>`

It raises in a compilation error because the `If` component does not declare a `secondary_column` slot, which is perfectly normal.

```console
** (CompileError) lib/my_app_web/live/contacts/index.ex:91: The slotable component <MyAppWeb.Layout.SecondaryColumn> as the `:slot` option set to `secondary_column`.

That slot name is not declared in parent component <If>.

Please declare the slot in the parent component or rename the value in the `:slot` option.

Available slot: "default"

    (surface 0.3.2) expanding macro: Surface.sigil_H/2
    (archi_studio 0.1.0) lib/my_app_web/live/contacts/index.ex:50: MyAppWeb.ContactsLive.Index.render/1
    (elixir 1.12.0-rc.0) lib/kernel/parallel_compiler.ex:319: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

### Sample App that reproduces the bug
I created a simple app that reproduces the unexpected behaviour: https://github.com/Malian/surface_conditional_slot

You can navigate to:
- `/template/`: default vue with `<template slot="..." :if={{ false }} />` that should not show the slot content but shows it
- `/template/foo`: default vue with `<template slot="..." :if={{ true }} />` that should show the slot content but shows it
- `/slotable/`: default vue with `<SecondaryColumn :if={{ false }}>` that should not show the slot content
- `/slotable/foo`: default vue with `SecondaryColumn :if={{ true }}>` that should show the slot content

The only one that __seems__ to work is the view with slotable component + `:if` directive, but if you look carefully at the HTML code, the content of the slotable component is added at the end of the content of the default slot as explained before.

### Discussion
Do we agree we have a bug here? And, if it is not a bug, how could we inform the user that he is doing something we do not support ?

**Comment by msaraiva** [comment]
> ⚠️ From my point of view, if it is not a bug, we should clearly inform the user that the `if` directive does not work with the `template`tag.

@Malian yup. Using `:if` or `:for` is not allowed in `<template>` nor in components using the `slot` option. We actually already have an issue for it. See: https://github.com/surface-ui/surface/issues/189. I updated the title to include `:if`.

> 3\. The slot is rendered as if it is part of the `default` slot of the `Layout` component ✖️

I'm not sure how we can handle that with slotables components. @lnr0626 any ideas?

**Comment by lnr0626** [comment]
I think we'll have to add some checks inside the directives to handle warning when they're used where they aren't supported

**Comment by msaraiva** [comment]
@lnr0626 this means he can only achieve what he wants today by passing the values he needs for the condition to the `Layout` and then add the `:if` there to conditionally show/hide the column. Right? If so, I wonder if we could improve the API to allow at least allow `:if` on templates/slottables. Would that be possible with some adjustments in the current implementation or it's a no-no situation.

**Comment by lnr0626** [comment]
One potential would be to automatically move the if inside the template for those two - I think that's feasible, though that has some potential for confusion. I'll type up some examples when I get to the computer so it's a bit clearer what I'm suggesting

**Comment by msaraiva** [comment]
@Malian maybe the best thing to do would be to add a prop `show` to the column itself, mimicking the behaviour of `:if`. Something like:

```elixir
def render(assigns) do
  ~H"""
    <Layout>
      <div>
        <h1>My Main content</h1> 
     </div>
     <SecondaryColumn show={{ @live_action == :preview }}>
        <h2>My Secondary Content</h2>
     </SecondaryColumn>
    </Layout>
  """
end
```

The `Layout` could then check that property and show/hide the column accordingly. That's probably better than use `:if` anyway as it makes it explicit. You could even define it as `required`. The only downside is that, for now, it will require a component for the column instead of just a `<template>`.

**Comment by Malian** [comment]
@msaraiva Not sure what you mean by "The layout could check that property".

The render function of the layout look like this:
```elixir
def render(assigns) do
  ~H"""
    <div>
      <div id="main">
         <slot />
      </div>
      <slot name="secondary_column" />
    </div>
  """
end
```
How can I hide the `secondary_column` slot with you suggestion?

Moreover, I am not sure it will work if I have some assign that are specified only for the preview view in the `handle_params` function for example:
```elixir
defp apply_action(socket, :preview, _params) do
  socket
  |> assign(:page_title, "New Contact")
  |> assign(:contact, %Contact{})
end
```



I believe the following will raise an `assign @contact not available in eex template`

```HTML
<SecondaryColumn show={{ @live_action }}>
  {{ @contact }}
</SecondaryColumn>
```

I am probably miss something ?

**Comment by msaraiva** [comment]
> How can I hide the `secondary_column` slot with you suggestion?

You can do:

```jsx
<slot name="secondary_column" :if={{ List.first(@secondary_column).show }}/>
```

> I believe the following will raise an `assign @contact not available in eex template`

As long as you have a `data contact, ...` defined, it shouldn't.

Here's a similar example I tested:

```elixir
defmodule Layout do
  use Surface.Component

  slot default
  slot secondary_column

  def render(assigns) do
    ~H"""
    <div id="layout" style="border: 2px solid red; padding: 3px;">
      <div id="layout_content" style="border: 2px solid black; padding: 3px;">
        <slot />
      </div>
      <slot name="secondary_column" :if={{ List.first(@secondary_column).show }}/>
    </div>
    """
  end
end

defmodule SecondaryColumn do
  use Surface.Component, slot: "secondary_column"

  prop show, :boolean, default: false

  slot default, required: true

  def render(assigns) do
    ~H"""
    <div id="secondary_column" style="border: 2px solid green; padding: 3px;">
      <slot name="default" />
    </div>
    """
  end
end

defmodule Example do
  use Surface.LiveView

  data contact, :string, default: "John Doe"

  def render(assigns) do
    ~H"""
    <Layout>
      <div>
        <h1>My Main content</h1>
      </div>
      <SecondaryColumn show={{ true }}>
        <h2>My contact: {{ @contact }}</h2>
      </SecondaryColumn>
    </Layout>
    """
  end
end
```

You could also have a prop `show_secondary_column` on the `Layout` itself and change the condition to use that value instead of the `show` in the column. So you'd have:

```jsx
<Layout show_secondary_column={{ expression }}>
  <div>
    <h1>My Main content</h1>
  </div>
  <SecondaryColumn>
    <h2>My contact: {{ @contact }}</h2>
  </SecondaryColumn>
</Layout>
```

Whatever suits you best :)

**Comment by lnr0626** [comment]
some context to make sure we're all on the same page:

the way that the renderable slotables work is essentially by transforming:
```
<ParentComponent>
  <SomeSlotableComponent :let={{ ... }}>
    ...
  </SomeSlotableComponent>
</ParentComponent>
```

into something close to:
```
<ParentComponent>
  <SomeSlotableComponent :let={{ ... }}> # treated purely as a template here
    <SomeSlotableComponent> # treated as a normal component that's rendered via live_component(...)
      ...
    </SomeSlotableComponent>
  </SomeSlotableComponent>
</ParentComponent>
```
---

the way that the if directive works is essentially transforming:
```
<Component :if={{ <bool expression> }}>
  ...
</Component>
```

into:
```
<If condition={{ <bool expression> }}>
  <Component>
    ...
  </Component>
</If>
```

---
with that in mind, my thought is that

my thought is that it might be feasible to translate the following:
```
<ParentComponent>
  <SomeSlotableComponent :let={{ ... }} :if={{ ... }}>
    ...
  </SomeSlotableComponent>
</ParentComponent>
```

into something along the lines of
```
<ParentComponent>
  <SomeSlotableComponent :let={{ ... }}> # same as before - treated purely as a template here
    <If condition={{ ... }}>
      <SomeSlotableComponent> # same as before - treated as a normal component that's rendered via live_component(...)
        ...
      </SomeSlotableComponent>
    </If>
  </SomeSlotableComponent>
</ParentComponent>
```

additionally, it might be feasible to enable using props from that slot to define the condition and values for the component props (essentially what I suggested to @Malian in slack). this should be doable, but may not be straightforward

**Comment by Malian** [comment]
@msaraiva Thanks I completely missed that the slot value is accessible from the assign :man_facepalming:

I had to access the slot through the `assigns` instead of directly access it with `@secondary_column` as my slot is optional and when I do not set a secondary column, the `@secondary_column` does not exist. Is this the behaviour we would like to keep? It's the same as the `data foo, :string` that is not initialized if no default value has been set. I would have expected `@secondary_column` to be equal to `nil`.

> As long as you have a data contact, ... defined, it shouldn't.

Right if the `data contact` as a default value. Is set it to `nil`.

Thank you both, for your help and suggestions!

**Comment by msaraiva** [comment]
@lnr0626 thanks for the explanation.

> into something along the lines of
> 
> ```
> <ParentComponent>
>   <SomeSlotableComponent :let={{ ... }}> # same as before - treated purely as a template here
>     <If condition={{ ... }}>
>       <SomeSlotableComponent> # same as before - treated as a normal component that's rendered via live_component(...)
>         ...
>       </SomeSlotableComponent>
>     </If>
>   </SomeSlotableComponent>
> </ParentComponent>
> ```

That's a great idea. This way you can keep the template definition (which is required) allowing you to conditionally show the content. Great!

> additionally, it might be feasible to enable using props from that slot to define the condition and values for the component props (essentially what I suggested to @Malian in slack). this should be doable, but may not be straightforward

I have no idea what you guys are talking about 😆

> I had to access the slot through the `assigns` instead of directly access it with `@secondary_column` as my slot is optional and when I do not set a secondary column, the `@secondary_column` does not exist. Is this the behaviour we would like to keep? ...  I would have expected `@secondary_column` to be equal to `nil`.

@Malian you can still use `@secondary_column` as long as you conditionally check if it has been assigned with: 

```
slot_assigned?(:secondary_column)
```

**Comment by lnr0626** [comment]
> I have no idea what you guys are talking about 😆

haha - essentially allowing the props pulled out with `:let` to be used inside the `if` as well as inside prop value definitions, eg:

```
<ParentComponent>
  <SomeSlotableComponent :let={{ item: item, value: name }} :if={{ it.some_bool? }} prop_1={{ name }}>
    ...
  </SomeSlotableComponent>
</ParentComponent>
```

it may not work, but it's something we should look into

**Comment by msaraiva** [comment]
Oh, I see. Thanks.

Yeah, it should be doable.

**Comment by Malian** [comment]
> @Malian you can still use @secondary_column as long as you conditionally check if it has been assigned with:
> slot_assigned?(:secondary_column)

@msaraiva Indeed I could do that but I have chosen to extract the condition into a function as the intention is more clear:
```
<slot name="secondary_column" :if={{ slot_assigned?(:secondary_column) and List.first(@secondary_column).show }} />
```
vs
```
<slot name="secondary_column" :if={{ show_secondary_column?(assigns) }} />
```

@lnr0626 
> into something along the lines of
> 
> ```
> <ParentComponent>
>   <SomeSlotableComponent :let={{ ... }}> # same as before - treated purely as a template here
>     <If condition={{ ... }}>
>       <SomeSlotableComponent> # same as before - treated as a normal component that's rendered via live_component(...)
>         ...
>       </SomeSlotableComponent>
>     </If>
>   </SomeSlotableComponent>
> </ParentComponent>
> ```

Will it not be difficult to treat `<SomeSlotableComponent>` as a normal component as it has a `slot` name different than "default" ? With the current implementation, if you wrap a slotable component into a `If` tag, it will result in an error as `If` does not accept a slot other than the `default` slot.

```
The slotable component <MyAppWeb.Layout.SecondaryColumn> as the `:slot` option set to `secondary_column`.

That slot name is not declared in parent component <If>.

Please declare the slot in the parent component or rename the value in the `:slot` option.

Available slot: "default"
```

**Comment by Malian** [comment]
Close as there is a proper workaround and issue #189 already tackles this. Feel free to reopen if needed.
