### ISSUE TITLE
Compilation error "expected closing tag..." when aligning attributes

### ISSUE THREAD

**Issue by mkhennoussi** [surface-ui/surface#332]
Hi everyone !

I have a compilation error when the HTML attributes are formatted and aligned (I'm using Prettier by the way to format .sface files). The error is : **expected closing tag for `<name of the parent tag>`**

The code (from tailwindcss home page for instance) to get the compilation error : 
```
<figure class="bg-gray-100 rounded-xl p-8">
      <img
        class="w-32 h-32 md:w-48 md:h-auto md:rounded-none rounded-full mx-auto"
        alt=""
        width="384"
        height="512"
      />
   ...
</figure>
```

There is no error when the code is written like this (on one line):
```
<figure class="bg-gray-100 rounded-xl p-8">
      <img class="w-32 h-32 md:w-48 md:h-auto md:rounded-none rounded-full mx-auto" alt="" width="384" height="512" />
     ....
</figure>
```

Any ideas guys ? 
Thanks !

**Comment by Malian** [comment]
Hi @mkhennoussi 

This issue should be fixed on master with https://github.com/surface-ui/surface/commit/a8a7af67b87f3197033c97f5c875269ccdf28f8f

Could you please check if it works for you?

**Comment by mkhennoussi** [comment]
Hi @Malian ,

Yes it works great ! We can close the issue.
Thanks !
