### ISSUE TITLE
Syntax changes and deprecations for `v0.4` and `v0.5`

### ISSUE THREAD

**Issue by msaraiva** [surface-ui/surface#340]
I'm working on a proposal for a new unified syntax for built-in constructs, slots, dynamic props/attrs and directives.

Any syntax-related discussion will be moved here and consolidated into a single proposal for v`0.5.0`. A couple of those changes might be introduced already in `0.4.0`, deprecating a few aspects of the current syntax. ~The first draft of the proposal should be available for general feedback soon.~

The full proposal can be found [here](https://gist.github.com/msaraiva/dd40ab537e1508f1af2954a19faa2d54).

We also have plans to create a mix task based on the Surface formatter to automatically apply those changes.

### v0.4.0 :white_check_mark:

  - [x] Remove support for auto-conversion of literal strings into atoms when the `prop` is of type `:atom`

### v0.5.0

  - [x] Replace `{{ }}` with `{ }`
  - [x] Replace `~H` with `~F` to avoid conflict with `HEEx`
  - [x] Introduce `<#template>` and `<#slot>` and deprecate `<template>` and `<slot>` with proper warnings
  - [x] Introduce shorthand notation for `<#template slot="my_slot">` -> `<:my_slot>`
  - [x] Introduce `{#if}` and deprecate `<If>` with proper warning
  - [x] Introduce `{#for}` and deprecate `<For>` with proper warning
  - [x] Introduce `{#unless}`
   - [x] Deprecate passing attribute values as `selected=true` or `tabindex=1`. Any non-string value should be passed as `selected={true}` (just like React)
  - [x] Introduce the concept of root properties, e.g. `<Component {@var}>`
  - [x] Introduce the new shorthand  notation `{...@attrs}` for dynamic attributes/properties ~~and deprecate `:props` and `:attrs` with proper warnings~~ (we can deprecate them in future versions after getting some feedback)
  - [x] Introduce the new shorthand notation for attribute assignment, e.g., `<div {=@class}>`
  - [x] Support `{#if}...{#elseif}...{#else}...{/if}`
  - [x] Support `{#case}...{#match}...{/case}`
  - [x] Support `{#for}...{#else}...{/for}`
  - [x] Introduce the `s-` prefix for directives as an alternative to `:`
  - [x] Remove support for `{{ }}` interpolation inside string values for attributes, for instance, `id="id_{{@id}}"` will not evaluate `{{@id}}`. Such code should be rewritten as `id={"id_#{@id}"}`. Reason: literal string values should be kept as they were defined, i.e. no encoding, no conversion, no interpolation.
  - [x] Do not perform interpolation inside `<style>...</style>` and `<script>...</script>`.
  - [x] Provide a converter that can automatically convert:
    - [x] `{{ }}` into `{ }`
    - [x] `<template>` -> `<#template>`
    - [x] `<slot>` -> `<#slot>`
    - [x] `<If>` -> `{#if}`
    - [x] `<For>` -> `{#for}`
    - [x] `id="id_{{@id}}"` -> `id={"id_#{@id}"}`
    - [x] `selected=true` -> `selected={true}` and `tabindex=1` -> `tabindex={1}`
    - [x] Replace `~H` with `~F`
  - [x]  Add converter instructions to `MIGRATING.md`
  - [ ] Update documentation

**Comment by Malian** [comment]
@msaraiva As we implement `if/elseif/else`, what do you think of adding `unless` too?

```elixir
<#unless>
...
</#unless>
```
Related to https://github.com/surface-ui/surface/pull/219

**Comment by msaraiva** [comment]
If people find that useful, I have no problem adding it. 

**Note:** Just in case you're curious, I guess the fact I never use `unless` is because in my native language (portuguese) we barely use its equivalent, which is `a não ser que`, so I end up always reading `unless` as `se não`, which is the exact translation of `if not`. So, at least for me, reading `unless` in the code, brings this unintentional additional overhead of "translating" `unless` to `if not` so I prefer to just use `if not` already :) 

The funny thing is that when I'm speaking english, I use `unless` quite a lot and there's no overhead at all. It only happens when reading code. 🤷‍♂️

Sorry for the unrequested note. I was just wondering if there would be more people sharing the same "issue". Probably not. 😁 

Back to your question. I'm pretty sure people with different languages background might find it very useful. So yeah, we can add it.

**Comment by Malian** [comment]
@msaraiva It's funny because I never have used `unless` for the same reason :sweat_smile: If French, `unless` is equivalent to `sauf si`, that is the literal translation of `not if` or `except if`. So, same as you, reading unless in the code, results in overhead in my head because I have to translate it before understanding the condition... As like you, I prefer using `if not`.

I'll add it to the checklist. We can also wait for more requests about it?

**Comment by miguel-s** [comment]
@Malian @msaraiva in Spanish it's very similar to Portuguese: `a no ser que`, `salvo que` or `si no` 😄 

But I do use `unless` relatively often (mostly for `if not` without `else`), so having it in Surface would be nice.

**Comment by davydog187** [comment]
I am a native English speaker, and I find I have the same cognitive overhead when reading "unless" in code!

I personally advocate for not using it in code for that reason, but if people like it, so be it!

**Comment by msaraiva** [comment]
> I am a native English speaker, and I find I have the same cognitive overhead when reading "unless" in code!

That's interesting. I really thought that wouldn't apply to native speakers. I feel much better now 😁

**Comment by olivermt** [comment]
I am not an english native speaker, but my mom says I'm very smart and I also think it's very difficult to work with unless :D 

On the topic of this issue though:

warning: automatic conversion of string literals into atoms is deprecated and will be removed in v0.5.0.

Hint: replace `field="example_01_textarea"` with `field={{ :example_01_textarea }}`

Have we really thought this change through? 
Even with single brackets that is _extremely_ wordy imo.

Could we support 'naked' prop like we do with prop=false?
prop=:foo_atom ?

**Comment by miguel-s** [comment]
> Even with single brackets that is extremely wordy imo.

@olivermt could you elaborate on this?

`field="example_01_textarea"` vs `field={:example_01_textarea}` is just 1 more character, where do you see the issue?

Some pros side of this change:
1. Familiar to devs experienced with React
2. More explicit and less magic

**Comment by msaraiva** [comment]
@olivermt this is one of the few changes we're introducing to make passing attribute values more consistent. 

The biggest issue here is that in HTML, every value is a string, including unquoted attribute values. Since we're extending HTML, we should try to keep as much as possible from its semantics. So, in order to do that, we should avoid changing the values in any way when those values are defined as literals, i.e. no auto-conversion, no encoding and no interpolation. Without those changes, whenever copying/pasting HTML code might lead to different rendering in the browser and we don't want that.

We had some issues already in that regard. I remember a couple of them. One when dealing with form fields, which may accept both strings and atoms and another one when the user tried to pass an encoded entity using as `&entity_name;` in a literal string. There are other cases where this can bring inconsistencies but I can't remember all of them :)

So we decided to have a very simple rule: if the value is passed as literal,  we don't touch it. That guarantees that any HTML code will be rendered as expected. If you want to pass anything other than a string, you have to pass it inside `{ }`, in that case, since `{ }` is our extended realm, we can accept whatever we want.

Now, regarding accepting unquoted strings as attribute values. We have a few options:

1. Stay faithful to HTML specs. Accept them but always as strings
2. Accept them but emit warnings advising the user that if the intention is to pass a non-string value, `{ }` should be used instead.
3. Do not accept them. I think this was the behaviour React adopted in the past. Probably because `JSX` accepts non-string values as properties and the absence of proper quoting would bring the same confusion. It's much easier to just map `"..."` to `string` and `{ }` to JS expressions than to add a third way of passing values without any explicit indication (no quoting) of how that value will be evaluated.
4. Accept them as strings when passed as HTML tags attributes (keeping 100% compatible with HTML specs) but warning or even raising an error when passing as component properties. 

My vote will probably go to `#2`. That would allow users to still copy/past HTML that would work but they would be aware that this could bring confusion so they should change it.

**Comment by Malian** [comment]
>  Remove support for `{{ }}` interpolation inside string values for attributes, for instance, `id="id_{{@id}}"` will not evaluate `{{@id}}`. Such code should be rewritten as `id={"id_#{@id}"}`. Reason: literal string values should be kept as they were defined, i.e. no encoding, no conversion, no interpolation.

@msaraiva it seems that this has already been "fixed", isn't it?

I wrote the following test, expecting it to fail but it did not
```elixir
  test "`{}` interpolation inside string values for attributes is not evaluated" do
    code = """
    <Button class="id_{ @id }" />
    """

    [node | _] = Surface.Compiler.compile(code, 1, __ENV__)

    assert %Surface.AST.Component{
             module: Surface.CompilerTest.Button,
             props: [
               %Surface.AST.Attribute{
                 name: :label,
                 type: :string,
                 value: %Surface.AST.Literal{value: "id_{ @id }"}
               }
             ]
           } = node
  end
```
The following 2 comments tests fail if I uncommented them as the `{ ... }` inside the prop is not treated as an `attribute_expr`. Isn't it the goal we want to achieve?

https://github.com/surface-ui/surface/blob/441faebdd999ef8f1566c8b9919f73cbc4215b98/test/parser_test.exs#L716-L742

Am I missing something or could we check the checkbox?

**Comment by frankdugan3** [comment]
This issue replaces #107, which included a request for an implementation of `cond`, but I didn't see anything like `{#cond}...{#match}...{/cond}` mentioned here or in the new proposal. Is that still planned, or has it been excluded? It would certainly be useful to me!

**Comment by msaraiva** [comment]
Hi @frankdugan3!

The new syntax will allow you do to:

```
{#if @value == 0}
  ...
{#elseif @value > 0}
  ...
{#else}
  ...
{/if}
```

So we removed `cond` from our TODO list. Is there anything specifically that you cannot achieve with `if/elseif/else` that you can do with `cond`?

**Comment by frankdugan3** [comment]
Ahh, that makes sense. No, that should cover it just fine!
