### ISSUE TITLE
[question] Clarity as component option base

### ISSUE THREAD

**Issue by leonardb** [surface-ui/surface#341]
Would [Clarity](https://clarity.design) be a potential option for components?

They're slowly moving all their angular specific UI components to web components under their Clarity Core.

Seeing as though they provide a very rich set of UI components would this potentially be an option? Somehow basing/porting Clarity to/from Surface components?

**Comment by msaraiva** [comment]
Hi @leandrocp!

I don't have much knowledge of the internals of Clarity Core but assuming it's mostly based on CSS and in case it doesn't make heavy use of JS stuff, I don't see any reason why it wouldn't play nice with Surface/LV. You can try asking this on the `#surface` channel on Slack. Maybe someone has already given a try.

**Comment by leandrocp** [comment]
Hi @msaraiva, I guess you meant @leonardb :)

**Comment by msaraiva** [comment]
Haha. Yeah, I got tricked by the autocompletion. Cheers.
