### ISSUE TITLE
Cannot render built-in components

### ISSUE THREAD

**Issue by imsekun** [surface-ui/surface#352]
Having difficulty with using the existing UI components.

Error when compiling: 

```
warning: cannot render <LivePatch> (module LivePatch could not be loaded)
Hint: Make sure module `LivePatch` can be successfully compiled.
If the module is namespaced, you can use its full name. For instance:

  <MyProject.Components.LivePatch>

or add a proper alias so you can use just `<LivePatch>`:

  alias MyProject.Components.LivePatch
```

Which is strange because I set it up like this:

```elixir
defmodule PageLive do
  use Surface.LiveView
end
```

Is there more setup required to use the built-in components?

**Comment by imsekun** [comment]
I made a minimal project to demonstrate the issue.

https://github.com/imsekun/phx-surface-bug/pull/1/files

**Comment by imsekun** [comment]
I checked `surface_site` to see how this was done. Turns out I had to alias it. :man_facepalming: I couldn't find it in the docs. I'll open a PR to improve it.

**Comment by msaraiva** [comment]
Hi @imsekun!

It should be 

```elixir
alias Surface.Components.LivePatch
``` 

instead of

```elixir
alias MyProject.Components.LivePatch
``` 

The hint message just provides an example to show how it might look like. Maybe we should change that message to something like:

```
If the module is namespaced, you can use its full name. For instance:

  <TheFullNamespace.LivePatch>
```

Do you think such a message could have prevented the misunderstanding?

**Comment by imsekun** [comment]
Maybe it could add in a possibility of it being a built-in component.

```
If the module is namespaced, you can use its full name. For instance:

  <MyProject.Components.LivePatch>

or add a proper alias so you can use just `<LivePatch>`:

  alias MyProject.Components.LivePatch

However if you're trying to use `surface`'s built-in component:

  alias Surface.Components.LivePatch
```

I wasn't really sure how to import a built-in one although it should've been obvious to me.
