### ISSUE TITLE
Send event information to parent

### ISSUE THREAD

**Issue by chrisjowen** [surface-ui/surface#359]
When passing an event prop I would like to send additional cahangeset information back to the parent. Currently I see that I can do:

```
 prop save, :event
```

And later:

```
    <button :on-click={{{@save}}} disabled={{!valid?(@changeset)}}>Save</button>
```

But im unclear how I would senf the @changeset back with the event to be picked up by te parents `handle_event`

**Comment by Malian** [comment]
Like in Phoenix Live view, you are not able to send a changeset to a live view. The changeset is computed in the backend part, so you can handle the event locally in your component with `handle_event` and then use `send` to send the `changeset` to the parent live view and handle it with  `handle_info` in the parent live view

**Comment by chrisjowen** [comment]
> use send to send the changeset to the parent

Sorry, maybe I confused the issue but this was the part I was asking about. I dont know how to send to the parent, I see in the socket the parent_pid is nil.

**Comment by Malian** [comment]
@chrisjowen This is not related to Surface but how phoenix live view works. 

`send` is a function that lets you send a message to a process pid.

```elixir
send(destination, message)
```

A LiveView is nothing more than a process, and your components "live" in that process. The LiveView process can be retrieved with `self()`. You are now able to send a message to the LiveView process.

```elixir
send(self(), {:update_changeset, changeset})
```

In the live view, you have to handle the message with the `handle_info(message, socket)` function.

```elixir
def handle_info({:update_changeset, changeset}, socket) do
  # Do what you want here
  {:noreply, socket}
end
``` 

Does it help you?

**Comment by chrisjowen** [comment]
Yes, thank you. I confusedly thought that each sub component would have its own process. I see that I can handle the message on the parent live view as you mentioned. I think I need to jump into learning more live view. Thanks for guidance.
