### ISSUE TITLE
Confusing warning message for duplicated attribute if node is not a component

### ISSUE THREAD

**Issue by drselump14** [surface-ui/surface#381]
From version 4.0, when there are multiple attributes found on components a warning message appears to warn the developer.

Example:
```
warning: The prop `height` has been passed multiple times. Considering only the last value.
Hint: Either remove all redundant definitions or set option `accumulate` to `true`:
```

However, the current implementation of the parser detects the duplicated attributes on non-component nodes too.
Although I found the warning for non-component node is useful, the message is rather confusing because it says about the attribute/property for a component based node.

I think there are two options to fix this issue:
- Fix the parser so it will detect only for component node
- Change the message to be more proper

**Comment by Malian** [comment]
@drselump14 Thanks for the detailed issue and the proposition to fix it.

The [HTML standard](https://html.spec.whatwg.org/multipage/syntax.html#attributes-0) says: 
> There must never be two or more attributes on the same start tag whose names are an ASCII case-insensitive match for each other.

As this is not allowed in HTML, I believe we should change the message according to the type of the node, HTML or Component.

@drselump14 feel free to propose an pull request if you would like to contribute to Surface.

The code where we generate this warning is the following:
https://github.com/surface-ui/surface/blob/5ddbbc67b2c165ba53a85c68c0da8fce491472f2/lib/surface/compiler.ex#L531-L565

I believe that we could propose an alternative error message by checking if `mod` equals `nil`.

**Comment by Malian** [comment]
@drselump14 Fixed in surface-next branch.
