### ISSUE TITLE
Use new `component/3` macro for stateless components

### ISSUE THREAD

**Issue by msaraiva** [surface-ui/surface#400]
From the slack channel:

@paulstatezny:

> Do we know what the timeline is until Surface is supported in “dead views”?

@msaraiva:

> Now that the `component/3` macro has landed, we can finally use it. However, there's one thing to decide before moving on, which is how to abstract its behaviour. We have at least the following options:
> 
> 1. Update `Surface.Component` to use `component/3` instead of `live_component/4`. This would introduce a breaking change on any existing stateless component that implements either mount or update. There shouldn't be many of them but we need to take them into account. The most common case of using those is to update computed assigns based on other assigns changes.
> 
> 2. Update `Surface.Component` to use `component/3` instead of `live_component/4` but introducing our own `mount` or `update` callbacks to keep minimum compatibility with those existing components. We say "minimum" because although we expect to be able to keep the same template, the callbacks have to be a bit different because there's no socket to assign values to so you'll probably have to manipulate the values themselves instead of using `assign/3` or `update/3`.
> 
> 3. Create a new `Surface.FunctionComponent` or `Surface.StatelessComponent` that uses `component/3` and keep `Surface.Component` as it is. 
> 
> Each option comes with different tradeoffs.
> 
> While `#1` introduces a breaking change for some existing components, it makes the model match perfectly the underlying LV's model. However, depending on how many components you have that depend on the mentioned callbacks, you'll spend more time migrating those components. You also get a sub-optimal DX as you can't create computed assigns that easily so you'll probably end up creating functions to do that. This strategy works fine but it makes the template more polluted, especially if you use the same computed value in more than one place. It might also have a small (probably insignificant) performance impact as you may need to perform the same computation multiple times depending on the template.
> 
> With `#2`, we can have a smoother transition but it will take longer to implement as will have to roll our own mechanism to provide `mount` and `update` to mimic the existing behaviour.
> 
> Finally, with `#3`, we have no breaking changes but, in order to benefit from the new stateless component API, you'll have to migrate the components yourself according to your needs. Besides, although this might be a practical solution, it seems a bit odd to have two different implementations for stateless components.
> 
> Personally, I think having computed assigns derived from other assigns is a very common requirement and LV should provide a standard way to do that. Unfortunately, there's no consensus yet on how this should be implemented in LV itself. So, if we want to move on, we'll have to stay ahead in the game, make our own decisions based on our own experiences until a decision is made on the LV side. That might take a month or a couple of years.
> 
> In case anyone has any suggestion on how we should proceed, feel free to share your thoughts. Keep in mind that we're always trying to make pragmatic decisions, without any dogma or attachments to any specific solution. We just want to be able to build great web applications while having a great development experience. So, if you have an idea, please share :slightly_smiling_face:
> 
> Wrapping up. We haven't decided yet which approach we'll use but the discussion has already begun so we should have a final decision soon. After that, we'll be finally able to have a timeline.

@olivermt:

> I suggest StatelessComponent and deprecate Component
> 
> what will liveview itself do with live_component without ID? aka stateless live component
> 
> then in StatelessComponent allow data props and implement an optional computed/1 callback that takes assigns and hands off {:ok, assigns}
> 
> this way when / if we expand on data props to be able to add a computed: &callback_that_takes_socket_and_or_assigns/1 (or /2 depending on socket or not) you make the computed callback unneeded
> 
> imo the focus should be hyperattentional towards ergonomics
> 
> that is what react finally did with hooks etc, finally productive without so much boilerplate
> 
> also a new StatelessComponent makes the upgrade path very simple
> 
> this assumes that LV will deprecate the id-less live_component

**Comment by msaraiva** [comment]
> I suggest StatelessComponent and deprecate Component

I agree. I think `#3` is certainly the safest approach. This way we can benefit from `component/3` straight away and give time to LV to introduce a standard way to do that. Regarding the naming, in the LV realm those components are officially called "Function Components" so maybe we should go with `Surface.FunctionComponent` to avoid confusion.

**Comment by miguel-s** [comment]
Agree on going with `#3` and naming the new component type `Surface.FunctionComponent` 👍 

React also calls them [Function Components](https://reactjs.org/docs/components-and-props.html) so the name should be familar to many devs coming from that world.

**Comment by paulstatezny** [comment]
The `Phoenix.LiveView.Helpers` functions are `component` and `live_component`, not `function_component` and `live_component`. I would love it if we could somehow make these new stateless components `Surface.Component`.

I appreciate the concern for backwards compatibility. However, there will never be a better time to make a breaking change. The more time passes, the more friction there is to do that.

😅

**Comment by msaraiva** [comment]
@paulstatezny those are good arguments.

I took a quick look at a few projects, including Surface itself and as far as I could see, 99% of the stateless components don't implement any callback other them `render`. The very few that do, can be easily adjusted to use functions to calculate the values and replace the related assigns.

Can anyone else provide an example of a `Surface.Component` implementing other callbacks that would be hard to migrate if we go with option `#1`? 

@olivermt, what would be the impact in `surface_bootstrap`?

**Comment by Malian** [comment]
I never have used `update` with a stateless component.

> I appreciate the concern for backwards compatibility. However, there will never be a better time to make a breaking change. The more time passes, the more friction there is to do that.

I share the same opinion, so I vote for `#1`.

**Comment by msaraiva** [comment]
Ok. I changed my mind and also vote for `#1`. 

In case users must use `update` in some components, they can still use `Surface.LiveComponent`. However, in order to allow that, we need to remove the validation that forces `Surface.LiveComponent` to have an `id` so it should behave just like any other component using `live_component`. I believe the support for "stateless" components using `live_component` will only be dropped when they have a solution for computed assigns.

**Comment by olivermt** [comment]
I also changed my mind because I don't want to look stupid and be the only one still cheering for `#1`!

**Comment by msaraiva** [comment]
BTW, this change will only be introduced after releasing `v0.5.0` as we want to have a safe point where all syntax changes can be applied without breaking the application. Since this change cannot be automatically handled by the converter, it's better to bring it after the migration.

**Comment by paulstatezny** [comment]
@olivermt Be a rebel and go against the crowd! 😂 If nobody pushes back then ideas don't have to stand on their own merit.

**Comment by msaraiva** [comment]
Implemented in https://github.com/surface-ui/surface/pull/453.
