### ISSUE TITLE
phx-value-* equivalent in Surface?

### ISSUE THREAD

**Issue by margusp2heathmont** [surface-ui/surface#402]
Good day!

How to enable API for arbitrary params to be passed to handle_call as https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html?

**Comment by Malian** [comment]
@margusp2heathmont the support for `phx-value-* `has been added in the `surface-next` branch. This branch will be merged soon into master, and the feature will be released in `v0.5.0`. See #357  and #354 for more info. You will be able to use the directive, `:values`, for generating `phx-value-*`. 

In the meantime, you can use the plain old Phoenix Live View way: `<div phx-value-var="myvar">...</div>`. If you are using a built in component of `Surface` you probably can pass it through the `opts` prop of the component. `<BuiltInComponent opts={{phx_value_var: "myvar"}} />`

I am closing this issue. Feel free to reopen it if I didn't answer your question.
