### ISSUE TITLE
Component requires an :id assign to be given

### ISSUE THREAD

**Issue by lukashambsch** [surface-ui/surface#414]
I just discovered surface and I love it's syntax and how it simplifies so much of the live view workflow, so I'm converting my existing components to use it. It's been going pretty smoothly so far, but I just ran into one issue I can't seem to resolve. I have a `SidePanel` component that essentially functions like a modal, which contains a `handle_event` call to close the panel. That `handle_event` call just sends a message that the parent live view can handle. This was working great using a liveview component, but for some reason I'm getting the following error when I convert it to a surface component: `a component TrackBoostWeb.Components.SidePanel that has implemented handle_event/3 or preload/1 requires an :id assign to be given`.

I think I must be missing something obvious, but I can seem to figure out what it is. What I'm doing is similar to the `Dialog` example in the docs, so I've read through those, but I still don't see what I'm missing. I'm passing the id attribute into the `SidePanel` component and, even though the `Dialog` example doesn't do this, also declaring the prop in the component itself (I've also tried it without that declaration). I've commented out the `handle_event` call to inspect the assigns and the `id` assign is present.

Here is the relevant code:

SidePanel Component

```
defmodule Web.Components.SidePanel do
  use Web, :surface_component

  prop id, :string, required: true
  prop title, :string, required: true
  slot default, required: true

  def render(assigns) do
    ~H"""
    <div class="fixed top-0 left-0 w-screen h-screen bg-black bg-opacity-50" :on-click="close" />
    <div class="fixed top-0 right-0 w-1/2 h-screen bg-white p-4 overflow-scroll">
      <div class="w-full text-right">
        <i class="fas fa-times text-gray-300 cursor-pointer hover:text-gray-400" :on-click="close" />
      </div>
      <div class="text-lg font-medium mb-4">
        {{ @title }}
      </div>
      <slot />
    </div>
    """
  end

  def handle_event("close", _params, socket) do
    send(self(), :close_side_panel)
    {:noreply, socket}
  end
end
```

OrderDetails Component that uses SidePanel

```
defmodule Web.OrdersLive.OrderDetails do
  use Web, :surface_component

  alias Orders
  alias Web.Components.{LabeledField, SidePanel}
  alias Web.OrdersLive.{Fulfillments, LineItems}

  prop order_id, :integer, required: true
  data order, :struct, default: %{}

  def render(assigns) do
    ~H"""
    <div>
      <SidePanel id="order-details-panel" title="Order Details">
        <LabeledField label="Order" value={{ @order.order_name }} />
        <LabeledField label="QTY" value={{ total_quantity(@order) }} />
        <LabeledField label="Order" value={{ @order.total_price }} />

        <LineItems line_items={{ @order.line_items }} />

        <div class="flex">
          <LabeledField label="Name" value={{ @order.customer_name }} />
          <LabeledField label="Email" value={{ @order.customer_email }} />
          <LabeledField label="Shipping Address" value={{ shipping_address(@order) }} />
        </div>

        <Fulfillments fulfillments={{ @order.fulfillments }} />
      </SidePanel>
    </div>
    """
  end

  def update(%{order_id: order_id}, socket) do
    {:ok,
     socket
     |> assign(order: Orders.get_order!(order_id))}
  end

  defp total_quantity(order) do
    Enum.reduce(order.line_items, 0, fn line_item, sum -> sum + line_item.quantity end)
  end

  @spec shipping_address(%TrackBoost.Orders.Order{}) :: String.t()
  defp shipping_address(order) do
    "#{Map.get(order.shipping_address, "city")}, #{
      Map.get(order.shipping_address, "country_code")
    }"
  end
end
```

**Comment by treebee** [comment]
How is your `:surface_component` defined? Is this using a statless component? (`Surface.Component`)

I think you will have to use a stateful LiveComponent. Check the `Dialog` example in the Surface docs again. There it's a stateless component in at the start, but then introduces stateful LiveCompnents

**Comment by lukashambsch** [comment]
@treebee That was it! Thank you!
