### ISSUE TITLE
Compile error when comment in a slot that takes renderless components

### ISSUE THREAD

**Issue by totaltrash** [surface-ui/surface#424]
With a slot that takes renderless components and uses a generator (like the example at: https://surface-ui.org/slots#binding-slot-props-to-generators - Binding slot props to generators)

When using the component and commenting out a line in the slot, this used to work fine in 0.4:

```
<Table items={user <- @users}>
  <Column title="Email Address">{user.email}</Column>
  <!--<Column title="Post Count">{{ user.post_count }}</Column>-->
</Table>
```
But is now a compile error in 0.5:

```
no slot "default" defined in parent component <Table>

Available slot: "cols"
```

Here's my table and column components:

```
defmodule Component.Table.Column do
  use Surface.Component, slot: "cols"

  @doc "The title of the column"
  prop title, :string, required: true
end

defmodule Component.Table do
  use Surface.Component

  prop items, :list, required: true

  slot cols, props: [item: ^items]

  def render(assigns) do
    ~F"""
    <table>
      <thead>
        <tr>
          <th :for={col <- @cols} scope="col">
            {col.title}
          </th>
        </tr>
      </thead>
      <tbody>
        <tr :for={item <- @items}>
          <td :for.index={@cols}>
            <#slot index={index} name="cols" :props={item: item} />
          </td>
        </tr>
      </tbody>
    </table>
    """
  end
end
```

**Comment by Malian** [comment]
@totaltrash in 0.5 `<!-- -->` is treated as regular HTML comment. It means that it will appears in the HTML code. It was not the case with 0.4. The encountered behaviour is the expected one as you have 2 nodes: public comment and a slot but the table composent does not accept a default slot.

0.5 also introduce the notion of private comment `{!-- --}` that are ignored at compile time and that will not appears in the HTML code.

Could you replace your code with the new syntax and see if it fix your issue ?

**Comment by totaltrash** [comment]
Yep, works perfectly, thanks @Malian
