### ISSUE TITLE
ErrorTag crashing when an error has an opt that can't be converted to a string

### ISSUE THREAD

**Issue by kfajdsl** [surface-ui/surface#436]
I found this out trying to use Changeset.unsafe_validate_unique/4, which has an opt with an array value in its error. This causes an ArgumentError when ErrorTag tries to interpolate the error opts into the message in ErrorTag.translate_error/1. 

I'll open a PR with my fix, but I'm not sure if it's the best solution (I'm pretty new to Elixir!).

**Comment by Malian** [comment]
@kfajdsl  Thanks for reporting this. Could you try to provide the default translator for `ErrorTag` as explained here? https://surface-ui.org/builtincomponents/ErrorTag

```elixir
config :surface, :components, [
  {Surface.Components.Form.ErrorTag, default_translator: {MyAppWeb.ErrorHelpers, :translate_error}}
]
```

If it does not fix your issue, could you please provide us a simple example that reproduces the bug you encounter?

**Comment by kfajdsl** [comment]
Aha, that does fix my issue! Can't believe I missed that. So is the `translate_error` found in the component itself just a minimal fallback then?

Thanks for the help, I'll close the issue and PR.

**Comment by Malian** [comment]
@kfajdsl exactly. This is a c/p from phoenix. Glad that solution works for you!
