### ISSUE TITLE
HTML comment turns into span in stateful LiveComponent with multiple root elements

### ISSUE THREAD

**Issue by miguel-s** [surface-ui/surface#438]
When a stateful live component has multiple root elements and one of those elements is a HTML comment then this comment is turned into a span.

In my case:

```html
<!-- my comment -->
```

Turns into:

```html
<span data-phx-component="6"> my comment </span>
```

This might be an issue in LiveView, will try to reproduce it there.

**Comment by Malian** [comment]
The bug comes from LiveView. To reproduce it, just render the following stateful component into a live view

```elixir
defmodule CommentBugWeb.SimpleComponent do
  use CommentBugWeb, :live_component

  def render(assigns) do
    ~L"""
    <!-- HTML COMMENT -->
    <div>
      My Content
    </div>
    """
  end
end
```
with
```elixir
<%= live_component(CommentBugWeb.SimpleComponent, id: "bug") %>
```

The HTML result is the following:
```html
<span data-phx-component="1"> HTML COMMENT </span>
<div data-phx-component="1" id="phx-FopBULfGFMABMwbB-1-2">
  My Content
</div>

**Comment by davydog187** [comment]
Relevant LiveView issue https://github.com/phoenixframework/phoenix_live_view/issues/802

**Comment by mcrumm** [comment]
Potentially more relevant is that LiveView is deprecating components without a single root element phoenixframework/phoenix_live_view#1453
