### ISSUE TITLE
Feature: Add Typescript Support

### ISSUE THREAD

**Issue by chevinbrown** [surface-ui/surface#444]
We don't currently support Typescript. I likely won't have time to get to this, unfortunately, but want to tag the issue to kick off discussion.

**Comment by codechips** [comment]
Interesting! What current (or future) problem will it solve?

**Comment by chevinbrown** [comment]
@codechips TS is fairly pervasive in the js community...and for some projects, nonstarter if the project isn't in TS. I would think we would want to support that part of the JS community.

**Comment by codechips** [comment]
Hear hear .. I am curious where JS in Surface is used. Thought it was hidden (abstracted away) by the LiveView since Surface is more or less a compiler. Care to point me in the right direction @chevinbrown? Where do I start? I know my way around TS so I might be able to help :)

**Comment by chevinbrown** [comment]
@codechips nice! Yeah, it'd only be for hooks AFAIK. I'm actually not familiar with how it does/should work. I'd start here: https://github.com/surface-ui/surface/blob/master/lib/mix/tasks/compile/surface.ex#L9

**Comment by justin-m-morgan** [comment]
One solution would be to write a types declaration and publish it to the @types NPM organization. 

[Typescript - Publishing](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)

I'd be happy to undertake this project.

**Comment by simonmcconnell** [comment]
@justin-m-morgan I think it is more around allowing people to write their hooks in typescript.  PR #483 has some info around it.

Not sure if the clojurescript usage in https://github.com/code-shoily/covid19 would be of any inspiration?

**Comment by onelesd** [comment]
Phoenix 1.6 uses esbuild which supports typescript out of the box. You rename the *.js files to *.ts and it Just Works. See my PR #574.

**Comment by onelesd** [comment]
Phoenix 1.6 uses esbuild which supports typescript out of the box. You rename the *.js files to *.ts and it Just Works. See my PR #574.

**Comment by VictorGaiva** [comment]
I could see some gain in writing hook type definitions, so that writing them become less painful, but this work would be done on the Phoenix Live View project first.

I started a refactor of the JS on the Phoenix Live View project a while ago, seen [here](https://github.com/VictorGaiva/phoenix_live_view), strongly typing stuff all around. Any help moving forward is welcome.

**Comment by chevinbrown** [comment]
@onelesd very nice! Hopefully that makes it upstream and we can close this out!
