### ISSUE TITLE
Bug: Rendered component gets a new line character

### ISSUE THREAD

**Issue by totaltrash** [surface-ui/surface#445]
## Describe the bug

I've got a component that renders some text, and is used inline. The rendered component gets an additional \n character, which is displayed in the browser as a space. I'm rendering something that is to be used like so:

```html
(<MyInlineComponent ... />)
```

but is getting rendered with some whitespace before the closing bracket

```html
(Rendered result )
```

## How to reproduce it

A render function like:

```elixir
def render(assigns) do
  ~F"""
  TEST
  """
end
```

Or

```elixir
def render(assigns) do
  ~F[TEST]
end
```

And tested with

```elixir
test "new line" do
  html =
    render_surface do
      ~F"""
      <MyInlineComponent ... />
      """
    end

  assert html == "TEST"
end
```

Results in:

```
    Assertion with == failed
    code:  assert html == "TEST"
    left:  "TEST\n"
    right: "TEST"
```

## The behavior you expected

No newline character to be appended to the rendered component

## Your Environment
Surface: v0.5.0
LiveView: v0.15.7
Elixir: v1.12.1

**Comment by miguel-s** [comment]
Hi @totaltrash!

I'm not able to reproduce your issue, could you provide more code around your `<MyInlineComponent ... />`?

Here are my test cases:

```elixir
defmodule Surface.NewlineTest do
  use Surface.ConnCase, async: true

  defmodule ComponentWithNewline do
    use Surface.Component

    def render(assigns) do
      ~F"""
      world!
      """
    end
  end

  defmodule ComponentWithoutNewline do
    use Surface.Component

    def render(assigns) do
      ~F[world!]
    end
  end

  test "should have newline" do
    html =
      render_surface do
        ~F"""
        Hello (<ComponentWithNewline />)
        """
      end

    assert html == "Hello (world!\n)\n"
  end

  test "should not have newline" do
    html =
      render_surface do
        ~F"""
        Hello (<ComponentWithoutNewline />)
        """
      end

    assert html == "Hello (world!)\n"
  end
end
```

**Comment by totaltrash** [comment]
Thanks for looking into this @miguel-s , yes it was my mistake, the new line was getting injected on the test case, silly me
