### ISSUE TITLE
Bug: TextInput doesn't accept values option

### ISSUE THREAD

**Issue by simonmcconnell** [surface-ui/surface#447]
## Describe the bug
```
<FieldContext name={"#{@name_ref}[value]"}>
  <Label class="sr-only">Value</Label>
  <div class="shadow-sm">
    <TextInput
      class="rounded-none"
      value={@value}
      opts={type: determine_type(@field, @operator), "phx-debounce": "blur"}
      values={name_ref: @name_ref}/>
  </div>
</FieldContext>
```

fails with error
```
lists in Phoenix.HTML and templates may only contain integers representing bytes, binaries or other lists, got invalid entry: {:name_ref, "alarm_filter[filter][rules][0]"}
```

Temporary workaround is to pass `phx-value-...` to `opts`.

## How to reproduce it
Create a `TextInput` with a `values` keyword list.

## The behavior you expected
Compilation!

## Your Environment
Surface: v0.5.0
LiveView: v0.15.7
Elixir: v1.12.1

**Comment by msaraiva** [comment]
Closing this in favor of https://github.com/surface-ui/surface/pull/448/.
