### ISSUE TITLE
Phoenix cannot compile on a fresh install with surface

### ISSUE THREAD

**Issue by DamienFF** [surface-ui/surface#460]
## Describe the bug
Adding surface 0.5.1 to the deps of a freshly created phoenix app results in the app not compiling anymore.
The error is pasted below.
It is written to report the bug to elixir. I do it here : Please tell me if I have to report it to elixir.

Pasted error

Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

==> surface
Compiling 102 files (.ex)
** (EXIT from #PID<0.105.0>) an exception was raised:
    ** (Module.Types.Error) found error while checking types for Mix.Tasks.Compile.Surface.generate_files/2

def(generate_files({js_files, _css_files}, build_time)) do
  opts = Application.get_env(:surface, :compiler, [])
  hooks_output_dir = Keyword.get(opts, :hooks_output_dir, "assets/js/_hooks")
  js_output_dir = Path.join([File.cwd!(), hooks_output_dir])
  index_file = Path.join([js_output_dir, "index.js"])
  File.mkdir_p!(js_output_dir)
  unused_hooks_files = delete_unused_hooks_files!(js_output_dir, js_files)
  index_file_time = case(File.stat(index_file)) do
    {:ok, %File.Stat{mtime: time}} ->
      time
    _ ->
      nil
  end
  update_index? = for({src_file, dest_file_name} <- js_files, dest_file = Path.join(js_output_dir, dest_file_name), {:ok, %File.Stat{mtime: time}} <- [File.stat(src_file)], case(case(File.exists?(dest_file)) do
    x when :erlang.orelse(:erlang."=:="(x, false), :erlang."=:="(x, nil)) ->
      true
    _ ->
      false
  end) do
    false ->
      :erlang.>(time, index_file_time)
    true ->
      true
  end, do: (_ -> (
    content = [header(build_time), "\n\n", File.read!(src_file)]
    File.write!(dest_file, content)
    true
  )), reduce: false)
  case(case(case(case(index_file_time) do
    x when :erlang.orelse(:erlang."=:="(x, false), :erlang."=:="(x, nil)) ->
      true
    _ ->
      false
  end) do
    false ->
      update_index?
    true ->
      true
  end) do
    false ->
      :erlang."/="(unused_hooks_files, [])
    true ->
      true
    other ->
      :erlang.error({:badbool, :or, other})
  end) do
    x when :erlang.orelse(:erlang."=:="(x, false), :erlang."=:="(x, nil)) ->
      nil
    _ ->
      File.write!(index_file, index_content(js_files, build_time))
  end
end

Please report this bug: https://github.com/elixir-lang/elixir/issues

** (KeyError) key :version not found in: [line: 46]
        (elixir 1.11.0) lib/keyword.ex:420: Keyword.fetch!/2
        (elixir 1.11.0) lib/module/types/unify.ex:318: Module.Types.Unify.get_var!/2
        (elixir 1.11.0) lib/module/types/expr.ex:112: Module.Types.Expr.of_expr/3
        (elixir 1.11.0) lib/module/types/helpers.ex:106: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.11.0) lib/module/types/expr.ex:83: Module.Types.Expr.of_expr/3
        (elixir 1.11.0) lib/module/types/helpers.ex:106: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.11.0) lib/module/types/expr.ex:374: Module.Types.Expr.of_expr/3
        (elixir 1.11.0) lib/module/types/helpers.ex:106: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.11.0) lib/module/types/expr.ex:83: Module.Types.Expr.of_expr/3
        (elixir 1.11.0) lib/module/types/expr.ex:289: Module.Types.Expr.of_expr/3
        (elixir 1.11.0) lib/module/types/expr.ex:136: Module.Types.Expr.of_expr/3
        (elixir 1.11.0) lib/module/types/helpers.ex:106: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.11.0) lib/module/types/expr.ex:195: Module.Types.Expr.of_expr/3
        (elixir 1.11.0) lib/module/types.ex:63: Module.Types.warnings_from_clause/6
        (elixir 1.11.0) lib/module/types.ex:22: anonymous fn/8 in Module.Types.warnings/5
        (elixir 1.11.0) lib/enum.ex:3421: Enum.flat_map_list/2
        (elixir 1.11.0) lib/enum.ex:3422: Enum.flat_map_list/2
        (elixir 1.11.0) lib/module/parallel_checker.ex:104: Module.ParallelChecker.check_module/2
        (elixir 1.11.0) lib/module/parallel_checker.ex:300: anonymous fn/5 in Module.ParallelChecker.spawn_checkers/1

## How to reproduce it
- I created a new phoenix app with the --live extension -> working.
- I added {:surface, "~> 0.5.0"} to mix.exs and ran mix deps.get -> working
- Phoenix does not compile any more.

## The behavior you expected
It compiles.
Thanks for your great work.

## Your Environment
Surface: v0.5.1
LiveView: v0.15.7
Elixir: v1.11.0, erlang/OTP 23

**Comment by msaraiva** [comment]
Hi @DamienFF!

Some users have experienced this issue using Elixir `v1.11.0`. You can find possible solutions here https://github.com/surface-ui/surface/issues/442#issuecomment-864414341.

Please let us know if still run into this problem after trying them out.

**Comment by DamienFF** [comment]
This solved the issue. Thanks a lot and sorry for wasting your time.
