### ISSUE TITLE
Compile error if slot index property is listed before name

### ISSUE THREAD

**Issue by totaltrash** [surface-ui/surface#463]
## Describe the bug

When binding slots to generators, if i configure the slot like so:

```
<#slot index={index} name="cols" :args={item: item} />
```

i get 

```
** (CompileError) lib/i_fix/components/table.ex:38: invalid attribute `index` for <#slot>.
Slots only accept `name`, `:args`, `:if` and `:for`.
```

but, if i reorder the slot props, so the index comes after the name:

```
<#slot name="cols" index={index} :args={item: item} />
```

everything is cool

## How to reproduce it

as above

## The behavior you expected

to either compile ok, or to warn about the order of the slot props if there is a requirement

## Your Environment
Surface: v0.5.1
LiveView: v0.15.7
Elixir: v1.12.1

**Comment by miguel-s** [comment]
In the compiler we force the `name` attribute to always be first, else we raise a compile error: https://github.com/surface-ui/surface/blob/2f951acf277126ef2a33f09f1050898ce2c384d5/lib/surface/compiler.ex#L1195
Is there a reason for this @msaraiva ? Else this should be an easy fix :)

**Comment by msaraiva** [comment]
@miguel-s the implementation is completely broken. This function was supposed to be recursive, traversing all attributes and it should consider `name` and `index` as valid attributes, not just `name`. 

Jesus, where was my mind I when I wrote that 🤦‍♂️
