### ISSUE TITLE
Docs specify wrong / outdated (?) syntax for things like options

### ISSUE THREAD

**Issue by hubertlepicki** [surface-ui/surface#470]
I think the docs are using wrong syntax for component parameters. For example, the documentation for TextInput proposes the following syntax:

```
<TextInput form="user" field="name" opts={{ autofocus: "autofocus" }} />
```

This is on the following link: https://hexdocs.pm/surface/Surface.Components.Form.TextInput.html#content

I have found in the tests that the correct form is, however:

```
<TextInput form="user" field="name" opts={ autofocus: "autofocus" } />
```

I don't know the history here but I suspect double mustache is historically valid (?) but new syntax uses single mustache instead?

I am using surface v0.5.2.

**Comment by Malian** [comment]
@hubertlepicki Thanks! It has been fixed on master with https://github.com/surface-ui/surface/commit/7d9da97080de686671e3d8537155b16796edbe14

**Comment by hubertlepicki** [comment]
Indeed it was, thanks @Malian !
