### ISSUE TITLE
[idea] Single file components

### ISSUE THREAD

**Issue by dmitriid** [surface-ui/surface#475]
This may have been proposed already, but quick search didn't find it.

Idea is: single file components. This borrows from both [Svelte](https://svelte.dev/tutorial/adding-data) and [Vue](https://v3.vuejs.org/guide/single-file-component.html#single-file-components).

This would be especially helpful with "view-only" components where the `.ex` portion is just `defmodule X do endmodule`.

## The idea:

Allow `.sface` file to fully define a component:

(For some reason Github can't render this as a single code block)

```
<script lang="elixir">
  alias QuireWeb.Router.Helpers, as: Routes

  props pages, :list, required: true
</script>

<script lang="js">
  export const Hook = { something };
</script>

<h2>
  Pages
</h2>
<ul>
  {#for page <- @pages }
    <li :hook=":Hook">
        { live_patch page.title, to: Routes.live_path(@socket, MyWeb.PageView, page.id) }
    </li>
  {/for}
</ul>
```

## Pros:

- Fewer files to keep around. Especially for "view"/"leaf"components that don't have much functionality you only need one file instead of at least two
- All code is already collocated, no need to track which other files belong to a component

**Comment by Zurga** [comment]
You could put the html-template code in the ".ex" file, in the render/1 function.

Because this is where the props and aliases are defined, this is what I usually start out with. I only split it up when the render function becomes too long.

**Comment by msaraiva** [comment]
Hi @dmitriid!

Thanks for the suggestion.

Since we're already discussing the viability of a standard declarative API for both, LV and Surface, I believe it's better to stick with the current approach until we have a definition on that front. We can then reopen this in the future if we feel the idea is still valid considering the possible unified API.
