### ISSUE TITLE
Proposal: Shorter short-hand for slots

### ISSUE THREAD

**Issue by margusp2heathmont** [surface-ui/surface#477]
Hello!

Current slots syntax:
```
<TextInput placeholder="Search for dashboard, segments and more">
  <:left_icon>
    <IconZoom />
  </:left_icon>
  <:right_icon>
    <IconCloseRounded on_click="clear_search" />
  </:right_icon>
</TextInput>
```

Proposed shorthand slot syntax:
```
<TextInput placeholder="Search for dashboard, segments and more">
  <IconZoom as={:left_icon} />
  <IconCloseRounded on_click="clear_search" as={:right_icon} />
</TextInput>
```

Sidenote: React would enable to write following syntax (would something similar be also possible in Surface?):
```
<TextInput 
  placeholder="Search for dashboard, segments and more"
  left_icon={<IconZoom />}
  right_icon={<IconCloseRounded on_click="clear_search" />}
/>
```

**Comment by Malian** [comment]
Thanks for you proposition @margusp2heathmont !

It has already been discussed here https://github.com/surface-ui/surface/issues/212 by introducing a new directive: `:slot`. I was the author of the proposition and after near a year, I am convinced that it is not the way to go as it introducing such a feature will make the whole slot thing confusing.

This is the main reason why we introduce the short syntax `:slot_name` as it is a valuable compromise and it is clear that the content is related to a slot.

I also believe that `as` is not clear about the intention. `as` could be something else than a slot, for example, it could be a component.  

I am closing the issue but feel free to reopen it anytime you have new related information or ideas to improve the proposition.
