### ISSUE TITLE
Triggering custom event from a stateful component

### ISSUE THREAD

**Issue by techninja1008** [surface-ui/surface#479]
I recently started using surface, and I think the concept is great! It's helped me be extremely productive in building a complex LiveView-based application. There is one particular use case however that I can't figure out: triggering an event passed via a `prop` from within `handle_event`.

For example, I have a stateful component that displays a few form controls to collect input from the user. This component listens to events such as `:on-keyup` etc with its own events in order to process the user input into a more refined (ie. parsed & validated) form. How do I then trigger an event to the parent component/liveview, passing this parsed & validated data for it to handle?

**Comment by codechips** [comment]
This example helped me understand it https://github.com/hubertlepicki/phoenix_live_components_app

Basically, you use `send_update(ParentComponent, id: 'parent_component_id', one: 1, two: 2)` and then you pattern match on the values passed in the `send_update` in the `update` method in the parent component

**Comment by techninja1008** [comment]
@codechips that only works if the parent is a component and not a live view. It also requires you to know the ID, which is often not the case and can be impractical.

**Comment by Malian** [comment]
> I recently started using surface, and I think the concept is great! It's helped me be extremely productive in building a complex LiveView-based application. There is one particular use case however that I can't figure out: triggering an event passed via a prop from within handle_event.

@techninja1008, unfortunately, it is currently not available due to PhoenixLiveView limitations. I have seen a tweet from Jose or Chris that says many users request this feature, so we could hope that PhoenixLiveView will add it in the future. Currently, what @Zurga suggests is the way to go.

I am closing the issue. Feel free to reopen it if you believe I have closed it to quickly.
