### ISSUE TITLE
Can we disable build time timestamp?

### ISSUE THREAD

**Issue by hubertlepicki** [surface-ui/surface#481]
I would like to add a config option to Surface that would disable adding "Build time: " line. The code in question is here:

https://github.com/surface-ui/surface/blob/6164224a7b156dd41327db7142af7eae182e86bb/lib/mix/tasks/compile/surface.ex#L176

The reasoning is that it annoys me when switching branches and is being added to commits by developers by mistake, even if nothing changes, resulting in merge conflicts that have to be resolved.

I can provide a PR.

That is if you want to keep this. I am not sure this timestamp is needed at all - the file on the filesystem can be also queried for modification date, so maybe we don't need it at all and can just rely on that? If that's preferred I'd remove the line completely.

**Comment by msaraiva** [comment]
Hi @hubertlepicki!

> The reasoning is that it annoys me when switching branches and is being added to commits by developers by mistake, even if nothing changes, resulting in merge conflicts that have to be resolved.

Yeah, we should avoid that.

> the file on the filesystem can be also queried for modification date, so maybe we don't need it at all and can just rely on that?

The problem is that the modification date's precision is provided in seconds which makes it unsuitable for some of the tests we have. However, instead of a configuration, we could print the build time only when in `test` env. WDYT?

> I can provide a PR.

That would be wonderful!

**Comment by hubertlepicki** [comment]
> The problem is that the modification date's precision is provided in seconds which makes it unsuitable for some of the tests we have. However, instead of a configuration, we could print the build time only when in test env. WDYT?

Yes, we can do that. I had a glance at the tests and it looks like the build time is used here, mostly for this test to see that the file changed when you rebuild it, which actually shows the issue I'm having precisely: source files didn't change and yet the resulting compiled file did.
https://github.com/surface-ui/surface/blob/c5c0b1b26228d1f96a83dd14694071030858eab7/test/mix/tasks/compile/surface_test.exs#L108

How about I refactor the test in a way that it actually modifies the source files, to check if recompilation happens and the resulting compiled file has the modifications made instead of the current one that relies on adding build time line? In such case we wouldn't have to add build time at all, not even in tests, and we'd have slightly better, real-life testing scenario.

**Comment by msaraiva** [comment]
Is the idea to actually change the content of the `fake_button.hooks.js` file? If so, we would be changing a file that belongs to the project's source code during the tests, which is probably not a good idea. 

Alternatively, we could make the `run/1` function accept a `colocated_assets_fun` option, allowing us replace the default `get_colocated_assets` function with a fake implementation that returns a non-versioned temporary `fake_button.hooks.js` file just for tests.

Thoughts?

**Comment by hubertlepicki** [comment]
@msaraiva I actually had some thoughts that maybe are not inline with yours but I went ahead and implemented as it was quick and probably shows better then intent than discussing.

In short, the PR above updates the header, but also generates the hook files in the test set up itself. My thinking is that I don't like adding code, not even the dependency injection, just for the sake of testing, and instead prefer the higher level test that does the set up & cleanup. So, in the PR above we're now generating the hook files in the setup block itself.

At the same time, I figured the message in header files could be a bit more helpful and point the user to the source files, which I added.

Please let me know what you think of the above, obv, this is just a proposal so if you don't like it no hurt feelings.

**Comment by hubertlepicki** [comment]
I found one issue with this where I added the path to the header it exposes full filesystem path. I'll have to update it so it's only a relative path otherwise we may be exposing something build-time that we don't want to be exposed like filesystem structure on the build environment. So, hold off merging this. I need to update the PR. but you can give me feedback on the approach!

**Comment by hubertlepicki** [comment]
Done & ready for review.

**Comment by msaraiva** [comment]
Hey @hubertlepicki!

I just review it and it looks great!

> At the same time, I figured the message in header files could be a bit more helpful and point the user to the source files, which I added.

Maybe we don't need to expose the source file path at all (even if it's just the relative path). I mean, the file name is already the full module name of the component, so it should be straightforward to the user to find the source. The less information we generate the better :) 

Let me know what you think so I can merge it.

Thanks a bunch for your contribution!

**Comment by hubertlepicki** [comment]
@msaraiva right. I removed the path to the source file completely, the PR is ready.
