### ISSUE TITLE
Update docs to inform how to use Surface.LiveView instead of Phoenix.LiveView globally

### ISSUE THREAD

**Issue by justin-m-morgan** [surface-ui/surface#487]
## Describe the bug

With a freshly scaffolded Phoenix app, turning a live view to a `Surface.LiveView` results in the default "live.html.heex" layout not being rendered.

## How to reproduce it
1. Scaffold new phoenix 1.6-rc.0 app
2. Add Surface as dependency
3. Create new live_view and route 
4. Change `use MyApp, :live_view` to `use Surface.LiveView`
5. Change sigil in render function from `~H` to `~F` (or template extension from `.heex` to `.sface`)
6. Observe content expand full width (no longer in `<main class="container">` and flash `div`s no longer in rendered page) 

## The behavior you expected

Rendered content of `Surface.LiveView` to include layout defined in `MyAppWeb.live_view`

## Your Environment
Surface: v0.5.2
Phoenix: v1.6.0-rc.0
LiveView: v0.16.3
Elixir: v1.12.2

**Comment by justin-m-morgan** [comment]
This behaviour is manageable by configuring each `Surface.LiveView` with the desired layout but the options provided in the `MyAppWeb.live_view` allow for a global default layout. Alternatively, this could be accomplished with documentation about how to configure Surface to use a global default layout for `Surface.LiveView`s.

```elixir 
use Surface.LiveView, layout: {MyApp.LayoutView, "live.html"}
```

**Comment by msaraiva** [comment]
Hi @justin-m-morgan!

Yes. Either you create a new `surface_live_view` macro (as you did) or you change the original `live_view` to use `Surface.LiveView`.

I agree we should add a note to the docs. Maybe in the [Getting Started](https://github.com/surface-ui/surface_site/blob/master/lib/surface_site_web/live/getting_started.ex) guide as an "optional" step. Feel free to submit a PR if you want.

**Comment by Malian** [comment]
I am closing the issue as the documentation has been improved to better explain how to use a custom macro.
