### ISSUE TITLE
how to escape <> or {} in template

### ISSUE THREAD

**Issue by schneiderlin** [surface-ui/surface#488]
I might be missing something obvious, but I don't see a document about how to write <> or {} inside tag, like this.
```
<SomeComponent>
   some text that contains <> {}
</SomeComponent>
```
thanks in advance

**Comment by msaraiva** [comment]
You can either use HTML entities:

* `<` -> `&lt;`
*  `>` -> `&gt;`
* `{` ->  `&lcub;`
* `}` ->  `&rcub;`

or just wrap than in `{""}`:

```
<SomeComponent>
   some text that contains {"<>"}  {"{}"} 
</SomeComponent>
```
