### ISSUE TITLE
dynamic stateless components commit seems to introduce a compiler bug 

### ISSUE THREAD

**Issue by dvic** [surface-ui/surface#493]
## Describe the bug

We tried switching to the `surface` master version today and we encountered something weird. When we do a clean compile all tests pass but when we run `mix test` a second time, there are failures. The failures are all related to essential assigns missing (things like the `get` assign in modules where context is used or `capture_click` for the `Submit` component. An example stacktrace:

```
   ** (exit) exited in: Phoenix.LiveViewTest.call(#Phoenix.LiveViewTest.Element<selector: "#_modal-video_name_modal > div", text_filter: nil, ...>)
         ** (EXIT) an exception was raised:
             ** (KeyError) key :capture_click not found in: %{__changed__: nil, __context__: %{}, __surface__: %{provided_templates: [], slots: %{default: %{size: 0}}}, class: ["inline-flex", "justify-center", "py-2", "px-4", "border", "border-transparent", "shadow-sm", "text-sm", "font-medium", "rounded-md", "text-white", "bg-indigo-600", "hover:bg-indigo-700", "focus:outline-none", "focus:ring-2", "focus:ring-offset-2", "focus:ring-indigo-500"], label: "Update"}
                 (surface 0.5.1) lib/surface/components/utils.ex:89: Surface.Components.Utils.events_to_opts/1
                 (surface 0.5.1) lib/surface/components/form/submit.ex:27: Surface.Components.Form.Submit.render/1
                 (phoenix_live_view 0.16.4) lib/phoenix_live_view/helpers.ex:508: Phoenix.LiveView.Helpers.__component__/3
                 (myapp 0.1.0) lib/myapp_web/live/video_live/show.ex:81: anonymous fn/3 in MyAppWeb.VideoLive.Show.render/1
                 (phoenix_live_view 0.16.4) lib/phoenix_live_view/diff.ex:370: Phoenix.LiveView.Diff.traverse/6
                 (phoenix_live_view 0.16.4) lib/phoenix_live_view/diff.ex:444: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/6
                 (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
                 (phoenix_live_view 0.16.4) lib/phoenix_live_view/diff.ex:370: Phoenix.LiveView.Diff.traverse/6
                 (phoenix_live_view 0.16.4) lib/phoenix_live_view/diff.ex:444: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/6
                 (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
                 (phoenix_live_view 0.16.4) lib/phoenix_live_view/diff.ex:370: Phoenix.LiveView.Diff.traverse/6
                 (phoenix_live_view 0.16.4) lib/phoenix_live_view/diff.ex:444: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/6
                 (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
                 (phoenix_live_view 0.16.4) lib/phoenix_live_view/diff.ex:370: Phoenix.LiveView.Diff.traverse/6
                 (phoenix_live_view 0.16.4) lib/phoenix_live_view/diff.ex:444: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/6
                 (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
                 (phoenix_live_view 0.16.4) lib/phoenix_live_view/diff.ex:370: Phoenix.LiveView.Diff.traverse/6
                 (phoenix_live_view 0.16.4) lib/phoenix_live_view/diff.ex:444: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/6
                 (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
                 (phoenix_live_view 0.16.4) lib/phoenix_live_view/diff.ex:370: Phoenix.LiveView.Diff.traverse/6
```

We tried each commit since `0.5.2` and we found out that the problem occurs from this commit: https://github.com/surface-ui/surface/commit/09cd5b495842321d0be909beb3532abd337cadf5. I haven't had the time to see if I can reproduce it in isolation but I thought someone might already have an idea what's going on by looking at the commit in question.

## Your Environment
Surface: 09cd5b495842321d0be909beb3532abd337cadf5
LiveView: v0.16.4
Elixir: v1.12.4

**Comment by dvic** [comment]
Just guessing here, but isn't maybe this line the cause of the issue: https://github.com/surface-ui/surface/commit/09cd5b495842321d0be909beb3532abd337cadf5#diff-ae4237693e1d6b02e7b564f63e253ae4765c89cad33534fdd0fd032a764a9a62R205 Shouldn't there always be *some* props? (i.e., the surface internal props)

**Comment by msaraiva** [comment]
Hi @dvic!

It could be but even if that's the case, it should always break the tests, not only when running them for the second time. I still need to investigate that. I could be a race condition during compilation while introspecting information about the component or the lack of a `require` to enforce a compile-time dependency in the caller code.

**Comment by dvic** [comment]
Oh wait, but now the problem is also present when running the app:

![image](https://user-images.githubusercontent.com/1214337/136598894-dbbc3730-390d-4fd0-a284-55cd85d7e776.png)

Anyways, this repo definitly reproduces it, hopefully it's broken on your machine as well 😅
