### ISSUE TITLE
Surface DX improvement suggestion

### ISSUE THREAD

**Issue by olivermt** [surface-ui/surface#499]
Hello.

I just caught a regression bug with a renaming of a form and some radio buttons that didnt work anymore.

The issue was that when the form changes id, the derivative inputs also change id.

In our case a input named "scheduled_gift_msg" in form "gift_msg_later_form" -> "gift_msg_later_form_scheduled_gift_msg".

Form was updated to new syntax and ended up as "gift-msg-later-form" and then new input derivative of "gift-msg-later-form_scheduled_gift_msg".

The Label component was still pointing at "gift_msg_later_form_scheduled_gift_msg" and the radio buttons stopped working.

My theory is that mayhaps the compiler could look at the produced html for Label components that use a literal as its identifier. If there is no input of that name in current form, show compiler warning / error.

**Comment by msaraiva** [comment]
Currently, the only way to do this would be to implement `transform/1` and validate there.
