### ISSUE TITLE
Cannot upgrade Surface post 0.1.0-alpha.2

### ISSUE THREAD

**Issue by fdeage** [surface-ui/surface#502]
## Describe the bug

I am currently tracking the master branch of Surface in my `mix.exs`: `{:surface, github: "msaraiva/surface", branch: "master"}`.

Recently I realized that my `mix.lock` had locked me on commit 28a53e74cd7923cd (0.1.0-alpha.2), which is >1 year old. But when I tried to upgrade, I get compilation errors:

`
== Compilation error in file lib/surface/components/live_file_input.ex ==
** (CompileError) lib/surface/components/live_file_input.ex:37: undefined function live_file_input/2
    (elixir 1.12.2) src/elixir_locals.erl:114: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
    (stdlib 3.15.2) erl_eval.erl:685: :erl_eval.do_apply/6
    (elixir 1.12.2) lib/kernel/parallel_compiler.ex:319: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
could not compile dependency :surface, "mix compile" failed. You can recompile this dependency with "mix deps.compile surface", update it with "mix deps.update surface" or clean it with "mix deps.clean surface"
`
or
`
== Compilation error in file lib/surface/components/form/date_select.ex ==
** (CompileError) lib/surface/components/form/date_select.ex:22: module Phoenix.Component is not loaded and could not be found. This may be happening because the module you are trying to load directly or indirectly depends on the current module
    (elixir 1.12.2) expanding macro: Kernel.use/1
    lib/surface/components/form/date_select.ex:22: Surface.Components.Form.DateSelect (module)
    expanding macro: Surface.Component.__using__/1
    lib/surface/components/form/date_select.ex:22: Surface.Components.Form.DateSelect (module)
    (elixir 1.12.2) expanding macro: Kernel.use/1
    lib/surface/components/form/date_select.ex:22: Surface.Components.Form.DateSelect (module)
    (elixir 1.12.2) lib/kernel/parallel_compiler.ex:319: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
could not compile dependency :surface, "mix compile" failed. You can recompile this dependency with "mix deps.compile surface", update it with "mix deps.update surface" or clean it with "mix deps.clean surface"
`

## How to reproduce it

1. add `{:surface, "~> 0.5.1"}` to `mix.exs`
2. `mix deps.get && mix.deps.compile surface`

## The behavior you expected

The dep compiles.

## Your Environment

Surface: master (but locks to 0.1.0-alpha.2)
LiveView: v0.14.8
Elixir: v1.12.2

**Comment by Malian** [comment]
@fdeage I am closing the issue. Feel free to reopen it if you run into any other issues.

**Comment by fdeage** [comment]
@Malian thanks! Can't upgrade now because of some dependency hell, I'll let you know.
