### ISSUE TITLE
Clashes with live_view 0.17.x

### ISSUE THREAD

**Issue by mfeckie** [surface-ui/surface#514]
## Describe the bug
When trying to update a project to live_view 0.17.2 there is a clash with `slot/2` when using Surface

`function slot/2 imported from both Surface.API and Phoenix.LiveView.Helpers, call is ambiguous`

## How to reproduce it
Upgarde live_view to 0.17.x

## The behavior you expected
Should still compile

## Your Environment
Surface: v0.6.0
LiveView: v0.17.2
Elixir: v1.12.2

**Comment by msaraiva** [comment]
Fixed in #546.
