### ISSUE TITLE
"assign @socket not available" with surface 0.6.1 

### ISSUE THREAD

**Issue by anildigital** [surface-ui/surface#515]
Getting error `assign @socket not available` for surface stateless component (surface v0.6.1). It didn't occur for surface v0.5.2

```
  def render(assigns) do
    ~F"""
    {@name && icon_name_to_module(@name) &&
      live_component(@socket, icon_name_to_module(@name),
        color: @color,
        ...
        class: @class
      )}
    """
  end
```

**Comment by dvic** [comment]
@anildigital did you manage to get it working :)? If so then I guess you can go ahead and close this issue?

**Comment by anildigital** [comment]
@dvic yep. It's fine now. You can close the issue.

**Comment by dvic** [comment]
> @dvic yep. It's fine now. You can close the issue.

I can't, I'm not one of the maintainers :)

**Comment by miguel-s** [comment]
Awesome, glad it worked for you. Clasing the issue now :)
