### ISSUE TITLE
Support dynamic stateful components

### ISSUE THREAD

**Issue by tiberiuc** [surface-ui/surface#516]
Are there any plans to add support for dynamic stateful components similar to Dynamic.Component (maybe Dynamic.LiveComponent ) ?

**Comment by cybernetlab** [comment]
+1

**Comment by msaraiva** [comment]
Yes, that's certainly on the roadmap 👍

**Comment by tiberiuc** [comment]
@msaraiva I created a PR #518 with that one implemented , let me know what you think , thank you

**Comment by tiberiuc** [comment]
This issues is done in PR #518
