### ISSUE TITLE
What is the proper way of defining the on-change event handler in Select?

### ISSUE THREAD

**Issue by saleyn** [surface-ui/surface#517]
I am getting a warning when defining an `:on-change` event handler in a `select` component:
```
warning: Unknown property ":on-change" for component <Select>
```
![image](https://user-images.githubusercontent.com/272543/139946123-120b7af7-f8aa-4b7c-a098-ea5199895132.png)

Is this definition incorrect or this is a bug?

**Comment by simonmcconnell** [comment]
From the events page on surface-ui.org:

```
IMPORTANT: Pay attention that :on-[event] directives can only be used in HTML tags, not components. The reason is because, unlike a tag, a component may render more than one DOM element so it's up to the component's author to define the component's public API, including its exposed events, and properly forward those events to the related HTML elements they belong.
```

You can use `phx-change` on things but I expect the usual path is to handle the change from the`form`.

**Comment by saleyn** [comment]
Actually changing that to use `phx-change` results in a similar warning:

![image](https://user-images.githubusercontent.com/272543/140059394-a73c383a-69a7-41d5-a8c1-434d189d9a0a.png)

In this particular case I need to be able to track changes of this `Select` element independently from the form.  `phx-change` works fine if I use the `select` HTML tag, but I get this warning with the `Select` component.

**Comment by msaraiva** [comment]
Hi @saleyn!

You just need to pass them as `opts`, like: 

```
<Select opts={id: ..., phx_change: "update", phx_target: "#phone_#{@phone_num}"}>
```

@miguel-s I wonder if we should have `use Surface.Components.Events` on `Select`. Have we missed this or there's a reason we don't do that? I can't remember :)

**Comment by miguel-s** [comment]
LiveView does not support `phx-change` on individual inputs, only on the form itself.

Based on Chris McCord's answer in this [thread](https://elixirforum.com/t/liveview-phx-change-attribute-does-not-emit-event-on-input-text/21280/2).

In Surface you can do this:

```elixir
def handle_event("select", %{"items" => %{"item" => item}}, socket) do
  {:noreply, socket}
end

def render(assigns) do
  ~F"""
  <Form for={:items} change="select">
    <Field name="item">
      <Select .../>
    </Field>
  </Form>
  """
end
```

**Comment by saleyn** [comment]
@miguel-s: the issue with this approach is that if the `Select` field needs to be a part of another form, this solution creates a nested form, which doesn't behave well (and is browser-dependent) when the outer form is submitted, since HTML doesn't support [form nesting](https://www.w3.org/MarkUp/html3/forms.html).
