### ISSUE TITLE
Make Surface compatible with PhoenixLiveView 0.17

### ISSUE THREAD

**Issue by Malian** [surface-ui/surface#520]
This is a tracking issue.

- [ ] Replace Surface slots with built int Phoenix Live View Slots
- [ ] Fix: Stateful components must return a HEEx template (~H sigil or .heex extension)
- [ ] Migration guide from v0.6 to v0.7

Related issues #514, #494

**Comment by dvic** [comment]
Is `Replace Surface slots with built int Phoenix Live View Slots` required for 0.18 compatibility or can it be considered as an improvement/optimization?

**Comment by hubertlepicki** [comment]
Extra question from me is if we want to retain the same top-level API we have currently in surface, and just use the new LiveView slots under the hood to call it, or the top-leve/Surface API for slots should be gone completely.

**Comment by msaraiva** [comment]
> Is `Replace Surface slots with built int Phoenix Live View Slots` required for 0.18 compatibility or can it be considered as an improvement/optimization?

Both 😉

> An extra question from me is if we want to retain the same top-level API we have currently in surface, and just use the new LiveView slots under the hood to call it, or the top-leve/Surface API for slots should be gone completely?

LV's new slot API is pretty much the same as Surface's API so we don't expect any changes on that. What we'll certainly do though is to extend the API to allow some new features available in LV, like passing custom properties to slots without the need to define a component for that slot.

**Comment by edwardzhou** [comment]
May I know when this feature can be delivered? I can't wait for it :)

**Comment by benkeil** [comment]
Any news on this?

**Comment by Malian** [comment]
@benkeil & @edwardzhou We are close to releasing a new version compatible with LV 0.17. You can already test it and give us feedback with the following branch: https://github.com/surface-ui/surface/tree/ms-support-lv-0.17

**Comment by joshuataylor** [comment]
Works perfectly!

It now throws an error where components don't have an ID (great!!).

My upgrade steps:

1. In mix.exs, change `phoenix_live_view` dependency to: `{:phoenix_live_view, github: "phoenixframework/phoenix_live_view", override: true},`, as the branch relies on this.
2. Change surface dependency to `{:surface, git: "https://github.com/surface-ui/surface", tag: "ms-support-lv-0.17"},`
3. Bump up other dependencies you might have (liveview dashboard, oban, etc)

:partying_face:

**Comment by severian1778** [comment]
This upgrade is really needed.   Compatibility with 0.17 breaks surface currently.

**Comment by msaraiva** [comment]
Fixed in #546.

**Comment by brettinternet** [comment]
@msaraiva Will you also create another release? :)
