### ISSUE TITLE
Dynamic Component can't handle events with target

### ISSUE THREAD

**Issue by evansorenson** [surface-ui/surface#526]
## Describe the bug
Using a dynamic component and passing event with target. Error shown below.
> invalid value for property "submit". Expected a :any, got: ["start", {:target, %Phoenix.LiveComponent.CID{cid: 1}}].

## How to reproduce it
Pass an event to dynamic component as prop (shown below).  
`<Dynamic.Component module={@game_config.components.options} game_changeset={@game_changeset} submit={"start", target: @myself} change={"validate", target: @myself}/>`

## The behavior you expected
Should be able to pass event with target for dynamic component. 

## Your Environment
Surface: v0.6.1
LiveView: v0.16.4
Elixir: v1.11.4

**Comment by Malian** [comment]
@evansorenson Thanks! I can confirm the bug.

After few investigations, it seems that the `event` properties are not treated as `:event` but `:any`.

I'll look at this during the we.

**Comment by Malian** [comment]
It happens because we convert all prop to  `:any` here

https://github.com/surface-ui/surface/blob/d1c6b9e8df02c21507b35bbd4c882e165be771fe/lib/surface/type_handler.ex#L235-L239

@tiberiuc I suspect we will have the same issue with the new `Dynamic.LiveComponent`

**Comment by tiberiuc** [comment]
@Malian yes, we are having the same issue with Dynamic.LiveComponent, when I will have time and nobody fix it in the meantime I will try to fix it

**Comment by msaraiva** [comment]
@evansorenson and @tiberiuc, in case any of you want to give master a try, please let me know if you still run into any issue.

Thanks for reporting this problem!

@Malian we have now a new private type called `:dynamic` which is automatically set for all dynamic components' attributes. This way we can skip the compile-time type validation/conversion but still validate/convert the values to the proper types at runtime.
