### ISSUE TITLE
ErrorTag has error always shown

### ISSUE THREAD

**Issue by mxrguspxrt** [surface-ui/surface#527]
What would be nice pattern to show error only when user has left field or has tried to save the changeset? I could not find example in documentation.

on_blur="fieldname_blur" and show_error={@fieldname_blurred || @user_submitted}?

**Comment by simonmcconnell** [comment]
Typically you perform a validate function on form change, which you can trigger on field [blur](https://hexdocs.pm/phoenix_live_view/bindings.html#rate-limiting-events-with-debounce-and-throttle), where you give an action to the changeset. Same when you trigger the submit action.

It's talked about in several places in various docs, one is [Phoenix.HTML.Form](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html)
