### ISSUE TITLE
Introduce :keyword_or_map prop type and handle it in the default components

### ISSUE THREAD

**Issue by hubertlepicki** [surface-ui/surface#529]
To address the inconsistencies in replacing "_" with "-", we need a new prop type: `:keyword_or_map`

This type would accept a keyword list or a map, so both would be valid. This should be used for `:opts` on components such as link 
[here](https://github.com/surface-ui/surface/blob/master/lib/surface/components/link.ex#L73) so that it's possible to pass `:attrs` to "<a>" tag directly, preventing issues described here: https://github.com/surface-ui/surface/issues/512#issuecomment-957355292

**Comment by hubertlepicki** [comment]
@msaraiva if you can assign this to me and add label "enhancement", that'd be great - I don't have permission to do so.

**Comment by msaraiva** [comment]
Done! 

@hubertlepicki, thanks for  contributing.

**Comment by hubertlepicki** [comment]
I have toyed with this issue and came up to the conclusion that this is a bad solution to the problem.

Since we do expect keyword lists everywhere for :opts, in all copmonents, we would need to conditionally support maps and lists in all components, for things like extracting HTTP method (:get/:post) etc., adding csrf params etc. etc.

Instead, I have sent a PR to phoenix_html [here](https://github.com/phoenixframework/phoenix_html/pull/362/files) that has been accepted and merged in an exceptionally fast manner xD.

With the above, whenever phoenix_html releases new version and Surface / LiveView, updates to use it, it will be possible to solve the remaining problem of #512 with something like:

```
<Link label="user" to="/users/1" opts={ phx: [click: "my_click", value: [{"user_id", 1}]] } />
``` 

I think it's a better solution over all, and one resulting in 0 code added to Surface.

I am closing this issue if that's ok.
