### ISSUE TITLE
Compilation error while trying to use Surface

### ISSUE THREAD

**Issue by dsignr** [surface-ui/surface#531]
## Describe the bug
Compilation error while trying to use Surface in an existing Phoenix project.

## How to reproduce it
Add surface to your dependencies and do `mix deps.get`.

## The behavior you expected
Compilation should pass.

## Your Environment
Surface: v0.6.1
LiveView: v017.5
Elixir: 1.12.3 (compiled with Erlang/OTP 24)

```
==> surface
Compiling 114 files (.ex)

== Compilation error in file lib/surface/components/form/field.ex ==
** (CompileError) lib/surface/components/form/field.ex:24: the function "component" cannot handle clauses with the -> operator because it is not a macro. Please make sure you are invoking the proper name and that it is a macro
    (stdlib 3.16.1) lists.erl:1358: :lists.mapfoldl/3
    (elixir 1.12.3) src/elixir_fn.erl:15: anonymous fn/4 in :elixir_fn.expand/3
    (stdlib 3.16.1) lists.erl:1358: :lists.mapfoldl/3
    (elixir 1.12.3) src/elixir_fn.erl:20: :elixir_fn.expand/3
    expanding macro: Surface.sigil_F/2
    lib/surface/components/form/field.ex:24: Surface.Components.Form.Field.render/1
could not compile dependency :surface, "mix compile" failed. You can recompile this dependency with "mix deps.compile surface", update it with "mix deps.update surface" or clean it with "mix deps.clean surface"
```

![image](https://user-images.githubusercontent.com/5097028/141439128-fd8927e7-23be-4663-adf3-c9b6b2ba8468.png)

**Comment by simonmcconnell** [comment]
You need to be on Liveview 0.16.*

**Comment by Malian** [comment]
@dsignr as @simonmcconnell said, Surface is not yet compatible with phoenix live view 0.17. Downgrading LV, will do the job. I am closing the issue. Feel free to reopen it, if needed.

**Comment by dsignr** [comment]
Oops, thank you guys! Sorry for wasting your time.

**Comment by ajmeese7** [comment]
> @dsignr as @simonmcconnell said, Surface is not yet compatible with phoenix live view 0.17. Downgrading LV, will do the job. I am closing the issue. Feel free to reopen it, if needed.

@Malian is there an estimated timeline for when the newer version of LiveView is going to be supported?

Thank you for your time!
