### ISSUE TITLE
Upgrading from `0.1.0-alpha.2` to `0.5.1`

### ISSUE THREAD

**Issue by fdeage** [surface-ui/surface#534]
I'm currently in the process of upgrading Surface from `0.1.0-alpha.2` to `0.5.1`.

Besides the obvious stuff (`property(...)` -> `prop(...)`, etc.), some functions seem to have disappeared, like ` context(set(...))`, `get_form(...)`, or `get_non_nil_props(...)`.

Is there a tutorial to explain how to upgrade?

**Comment by Malian** [comment]
@fdeage Unfortunately, there is no migrating guide. That being said, we can surely help you to migrate from Surface 0.1 to surface 0.5 (or 0.6 now).

The context API has been changed. You can take a look at the [Contexts](https://surface-ui.org/contexts) section of the Surface website.

Regarding the "form", maybe this page could help you: [Form](https://surface-ui.org/builtincomponents/Form)

The `get_non_nil_props` has been splitted into 2 functions. Look at this commit to have some example: https://github.com/surface-ui/surface/commit/cddf81884a5573f1c746c08f5b9dad8025a9efb1#diff-43d3ccbca3d7ccbc86ab6b039f606bfb2a2a76b50b3f977e6de5c0d2656ca00c  Basicly you should be able to replace `get_non_nil_props` with `props_to_opts`

Feel free to comment this issue with your findings or with your comments. I'll try to help you upgrade Surface the best I can.

**Comment by fdeage** [comment]
Hi @Malian, thanks a lot for your response. I'm doing the upgrade this week, I let you know!

**Comment by GoulvenC** [comment]
Hi @Malian , thanks a lot for your help on this (I'm fdeage coworker).

I'm not sure exactly how to use `Context` API ? I tried to do like the commit you sent, but got an error :

```ex
defmodule EncheresImmoWeb.Components.Form.Textarea do

  use Surface.Components.Form.Input

  import Phoenix.HTML.Form, only: [textarea: 3]
  import Surface.Components.Form.Utils

  def render(assigns) do
    props = get_non_nil_props(assigns, [:value, :class])
    event_opts = get_events_to_opts(assigns)


    ~H"""
    <InputContext assigns={{ assigns }} :let={{ form: form, field: field }}>
      {{ textarea(form, field, props ++ @opts ++ event_opts) }}
    </InputContext>
    """
  end
end
```

```
== Compilation error in file lib/encheres_immo_web/components/form/textarea.ex ==
** (Phoenix.LiveView.HTMLTokenizer.ParseError) lib/encheres_immo_web/components/form/textarea.ex:14:5: invalid tag <InputContext>
    (phoenix_live_view 0.16.4) lib/phoenix_live_view/html_engine.ex:485: Phoenix.LiveView.HTMLEngine.decompose_remote_component_tag!/3
    (phoenix_live_view 0.16.4) lib/phoenix_live_view/html_engine.ex:216: Phoenix.LiveView.HTMLEngine.handle_token/3
    (elixir 1.12.2) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (eex 1.12.2) lib/eex/compiler.ex:48: EEx.Compiler.generate_buffer/4
    (phoenix_live_view 0.16.4) expanding macro: Phoenix.LiveView.Helpers.sigil_H/2
    lib/encheres_immo_web/components/form/textarea.ex:13: EncheresImmoWeb.Components.Form.Textarea.render/1
    (elixir 1.12.2) lib/kernel/parallel_compiler.ex:319: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
    ```
    
    Do you have any idea what my mistake might be?

**Comment by Malian** [comment]
@GoulvenC You are using the `~H` sigil from Phoenix Live View instead of the new `~F` sigil from Surface. We had to replace the sigil due to the introduction of the same sigil in Phoenix Live View.

**Comment by GoulvenC** [comment]
@Malian Thank you for your answer, indeed I was trying to reproduce what we see on this commit: https://github.com/surface-ui/surface/commit/77132bdda7ff88f2457a14423d986e59e0470851#diff-43d3ccbca3d7ccbc86ab6b039f606bfb2a2a76b50b3f977e6de5c0d2656ca00c 

I will instead rely on the syntax we can see here : https://github.com/surface-ui/surface/blob/master/lib/surface/components/form/textarea.ex

Thanks again for your time !
