### ISSUE TITLE
Is it supported to use Surface stateless components without LiveView?

### ISSUE THREAD

**Issue by guisehn** [surface-ui/surface#538]
I'm testing adding Surface to an existing Phoenix project that currently doesn't have LiveView, and I'm wondering if the use case of stateless components on regular pages (non-LiveView) is officially supported.

I was able to render a stateless Surface component on a regular controller by overriding the `render("index.html", assigns)` of my view file:

```ex
defmodule PhoenixProjectWeb.PageView do
  use PhoenixProjectWeb, :view

  alias PhoenixProjectWeb.Components.Button

  def render("index.html", assigns) do
    ~F"""
    <Button>I'm a Surface button</Button>
    """
  end
end
```

I wasn't able to render it on my template though (`templates/page/index.html.heex`).  There is a page on the docs talking about [usage with Phoenix templates](https://surface-ui.org/usage_with_phoenix_templates) but it only covers LiveView templates, not regular ones.

Tried changing the extension of my template file from `.heex` to `.sface` but there's no configured engine for it.

So is this use case supported? And is there a way to use Surface components on a controller with a template file? (without defining `render/2` on the view file)

**Comment by msaraiva** [comment]
Implemented in #543 and #548.
