### ISSUE TITLE
Dynamic html tag?

### ISSUE THREAD

**Issue by d3caf** [surface-ui/surface#540]
Hello,

First of all, thanks for the wonderful lib. I'm really enjoying using it. 

Secondly, is it possible to generate an HTML tag in a render function dynamically? e.g. I'm creating just a very simple heading component and would like to dynamically output `h1`, `h2`, etc depending on the prop specified for the size. I realize I could just use some pattern matching on the render function, but since I'm going all the way down to H6, I thought it'd be nice to just dynamically insert the tag somehow.

Thanks again!

**Comment by msaraiva** [comment]
LiveView has introduced a new `<dynamic_tag>`. So I believe we should use that for those cases when it's available. See https://github.com/phoenixframework/phoenix_live_view/blob/9cd3c22972ce769d9755ac77d14750461dec61c7/lib/phoenix_live_view/helpers.ex#L1358.
