### ISSUE TITLE
mix surface.init error

### ISSUE THREAD

**Issue by shubie** [surface-ui/surface#542]
## I created a new phoenix application and followed the documetation to set up Surface
1.  Add `surface` to the list of dependencies in `mix.exs:`
2. Configuring the project using `mix surface.init`

I got 

```
== Compilation error in file lib/surface/components/form/field.ex ==
** (CompileError) lib/surface/components/form/field.ex:24: the function "component" cannot handle clauses with the -> operator because it is not a macro. Please make sure you are invoking the proper name and that it is a macro
    (elixir 1.13.1) src/elixir_fn.erl:17: anonymous fn/4 in :elixir_fn.expand/4
    (stdlib 3.17) lists.erl:1358: :lists.mapfoldl/3
    (elixir 1.13.1) src/elixir_fn.erl:23: :elixir_fn.expand/4
    expanding macro: Surface.sigil_F/2
    lib/surface/components/form/field.ex:24: Surface.Components.Form.Field.render/1
    
```

## The behavior you expected
It should complete without error

## Your Environment
Surface: v0.6.1
LiveView: v0.17.5
Elixir: v1.13.1

**Comment by simonmcconnell** [comment]
@shubie you need to be on LiveView v0.16.x

**Comment by Malian** [comment]
@shubie We are working on the making Surface compatible with LV 0.17. In the meantime, you could try with the following branch: https://github.com/surface-ui/surface/tree/ms-support-lv-0.17
