### ISSUE TITLE
Collection not bound to slot content when passed to a component

### ISSUE THREAD

**Issue by fdeage** [surface-ui/surface#550]
I am in the process of migrating to `0.6.0` (from `0.1.0-alpha.2`) and I am running into a new compilation error.

When I try to pass a collection of items to a component using the `... -> ...` syntax, *and* also some content as a slot, then the items in the collection are not available to the content passed as slot, e.g.:

```elixir
<SomeComponent items={ org <- orgs }>
  <div>
    { org.name }
  </div>
</SomeComponent>
```

This gets me:
```
** (CompileError)my_file.ex:34: undefined function org/0
    (elixir 1.12.2) src/elixir_locals.erl:114: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
    (stdlib 3.15.2) erl_eval.erl:685: :erl_eval.do_apply/6
    (elixir 1.12.2) lib/kernel/parallel_compiler.ex:319: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

And the `some_component.ex` file:

```elixir
defmodule MyProject.SomeComponent do
  use MyProjectWeb, :surface_component

  prop(items, :list, required: true)
  slot(default)

  def render(assigns) do
    ~F"""
    <div>
      <#slot>
    </div>
    """
  end
end
```

**Comment by msaraiva** [comment]
Hi @fdeage!

You need to bind the variable created by the generator with the argument passed to the default slot. Like:

```elixir
defmodule MyProject.SomeComponent do
  use MyProjectWeb, :surface_component

  prop items, :list, required: true

  # Bind whatever variable is generated by prop `items` with the `item` arg
  slot default, args: [item: ^items]

  def render(assigns) do
    ~F"""
    <div>
      {#for i <- @items}
        <!-- Pass the `item` arg -->
        <#slot :args={item: i}>
      {/for}
    </div>
    """
  end
end
```

**Comment by fdeage** [comment]
Thank you so much, that's exactly what I needed!
I couldn't find it in the online doc though, is there something I am missing?

**Comment by msaraiva** [comment]
The concept is explained here https://surface-ui.org/slots#binding-slot-arguments-to-generators and although we don't have an specific example using the default slot, the concept is the same ;)
