### ISSUE TITLE
v0.7 introduces compile time dependencies

### ISSUE THREAD

**Issue by dvic** [surface-ui/surface#552]
I believe https://github.com/surface-ui/surface/blob/master/lib/surface/base_component.ex#L62 introduces various compile time dependencies. I just cleaned up my project to get rid of the troublesome so-called "compile-connected" dependencies and with the latest version (as of time of writing this is d80b3e347537d07990d7cd2d3be7495a2af1fad1) many compile dependencies returned.

Is there another way to implement liveview 0.17 support without the need for these `require` statements? Maybe generate another module at compile time to avoid requiring the original module?

**Comment by msaraiva** [comment]
Hi @dvic!

> I believe https://github.com/surface-ui/surface/blob/master/lib/surface/base_component.ex#L62 introduces various compile time dependencies.

Yes. Currently, module components (as opposed to pure function components ) must be defined as compile-time dependencies so we can do static checking based on the information introspected from those components. This has always been the case. One exception recently discovered was that if you're using Surface, running on elixir v1.13, due to some compiler optimizations, some of those dependencies will not be created, bringing a bunch of problems. That was the reason we needed to change the way we force the dependencies in `BaseComponent`.

> Is there another way to implement liveview 0.17 support without the need for these `require` statements? Maybe generate another module at compile time to avoid requiring the original module?

Yes. I'm already working on a unified [Declarative API](https://github.com/phoenixframework/phoenix_live_view/pull/1747) for both Surface and Liveview that will introduce a separate compiler that will do those checks without the need to add compile-time dependencies. Until then, we need those dependencies.

Besides the created dependencies (which is expected), are you facing any other issue? Errors? Warnings? Out-of-sync modules?, etc.

**Comment by dvic** [comment]
> Yes. Currently, module components (as opposed to pure function components ) must be defined as compile-time dependencies so we can do static checking based on the information introspected from those components. This has always been the case. One exception recently discovered was that if you're using Surface, running on elixir v1.13, due to some compiler optimizations, some of those dependencies will not be created, bringing a bunch of problems. That was the reason we needed to change the way we force the dependencies in BaseComponent.

We are indeed on Elixir 1.13. Not sure how it was done before, but surface 0.6 did not introduce compile dependencies when I call a component inside another component (reported by `mix xref trace`).

> Besides the created dependencies (which is expected), are you facing any other issue? Errors? Warnings? Out-of-sync modules?, etc.

I haven't had a lot of time to play around with it so can't say anything on that but so far I haven't encountered any issues. The only thing that affected us is that we had some selectors on `phx-click` in our tests and this of course also changed with the JS API, but that was an easy fix.

But in terms of impact of this change: changing one file required previously 42 files to be compiled, I worked a full day to get this down to one file and I succeeded (eliminating all troublesome compile-connected dependencies). I just checked with the latest version of Surface: it's now compiling 150 files 😅.

We do have a large project and I have to evaluate how this impacts day-to-day development but at a first glance it's not looking good. Before my refactoring, we had around 150 of these "compile-connected" dependencies, after my refactoring it was down to 0 (ignoring some valid compile-connected dependencies), and now it's back up again to 692 dependencies.

**Comment by msaraiva** [comment]
> We are indeed on Elixir 1.13. Not sure how it was done before, but surface 0.6 did not introduce compile dependencies when I call a component inside another component (reported by `mix xref trace`).

Surface 0.6 should introduce the same compile-time dependencies in elixir < 1.13.

> I just checked with the latest version of Surface: it's now compiling 150 files...
> ...we had around 150 of these "compile-connected" dependencies, after my refactoring it was down to 0 (ignoring some valid compile-connected dependencies), and now it's back up again to 692 dependencies.

Do those dependencies make sense? I mean, are those 150 files defining components that inject the same component you're changing? If not, please let me know. It could be a bug.

**Comment by dvic** [comment]
> Surface 0.6 should introduce the same compile-time dependencies in elixir < 1.13.

I just checked and I can confirm that it doesn't (both on 1.12 and 1.13), the command I'm running is: `mix xref trace my_file.ex --label compile`.

> Do those dependencies make sense? I mean, are those 150 files defining components that inject the same component you're changing? If not, please let me know. It could be a bug.

Yes this particular example makes sense, it's not a bug, this was the sidebar component (on almost all live views) :)

But the problem is also in other places: changing something in one of our contexts context -> 151 files (before: 1 file). This is something that I expected because of the nature of these "compile-connected" dependencies. Just to be clear: what I mean with this is to depend at compile-time on something that has a large runtime dependency tree below itself. We have a few components that are used across the system (storing phones, emails, URLs) that especially cause problems in this situation. When every component introduces a compile-time dependency you automatically have to recompiled if *any* of it's runtime dependencies change.

**Comment by msaraiva** [comment]
@dvic if that has become something really annoying in terms of compilation time, there are a few things you could do to improve the situation until we introduce the new API. For instance:

1. Identify the most critical dependencies (the ones that most commonly triggers those recompilations)
2. Convert some of them into function components. The downside is that by doing this you lose any compile-time check, however, it might be worth it until we release Liveview `v0.18` and Surface `v0.8`, which should be the first versions with the new API.

We may also release a patch version before `v0.8` that could do some optimization in that regard. We had to start with a very conservative approach to guarantee that the information we have about the dependencies are up-to-date but there's room for improvements even before the new API is released. We'll start checking on that as soon as we release `v0.7` this week.

**Comment by dvic** [comment]
> @dvic if that has become something really annoying in terms of compilation time, there are a few things you could do to improve the situation until we introduce the new API. For instance:
> 
> 
> 
> 1. Identify the most critical dependencies (the ones that most commonly triggers those recompilations)
> 
> 2. Convert some of them into function components. The downside is that by doing this you lose any compile-time check, however, it might be worth it until we release Liveview `v0.18` and Surface `v0.8`, which should be the first versions with the new API.
> 

Thanks for the suggestion, will definitely consider that!


> We may also release a patch version before `v0.8` that could do some optimization in that regard. We had to start with a very conservative approach to guarantee that the information we have about the dependencies are up-to-date but there's room for improvements even before the new API is released. We'll start checking on that as soon as we release `v0.7` this week.

Good to hear! Looking forward to the v0.7 release :)

**Comment by dvic** [comment]
Just an update: unfortunately we've not been able to upgrade yet (the suggestions did not help enough to significantly reduce the compilation times).

> We may also release a patch version before `v0.8` that could do some optimization in that regard. We had to start with a very conservative approach to guarantee that the information we have about the dependencies are up-to-date but there's room for improvements even before the new API is released. We'll start checking on that as soon as we release `v0.7` this week.

Now that v0.7 is released, are there any concrete plans for improving this aspect of v0.7? If there is anything I can do to help, please let me know. We would love to switch to Surface 0.7 / LV 0.17 :)

Out of curiosity, one more thing about something you previously mentioned: 

> Currently, module components (as opposed to pure function components ) must be defined as compile-time dependencies so we can do static checking based on the information introspected from those components. This has always been the case.

I just double checked, and Surface v0.6 does not create compile-time dependencies, at least for the sample of (live) components in our project I tried this (using `mix xref trace`). Are there particular conditions in which case these dependencies were created that you know of?

**Comment by msaraiva** [comment]
Hey @dvic!

I started to isolate the cases where we actually need a compile-time dependencies between components. So far, I found these:

1. Using macro components
2. Using components implementing the `translate/2` callback
3. Components using contexts
4. Components receiving props or slots

The one with greatest impact is certainly `#4` so it will be the first to be addressed by moving all static validations regarding props and slots to the surface compiler, which only runs after compilation.

**Comment by dvic** [comment]
> Hey @dvic!
> 
> I started to isolate the cases where we actually need a compile-time dependencies between components. So far, I found these:
> 
> 1. Using macro components
> 2. Using components implementing the `translate/2` callback
> 3. Components using contexts
> 4. Components receiving props or slots
> 
> The one with greatest impact is certainly `#4` so it will be the first to be addressed by moving all static validations regarding props and slots to the surface compiler, which only runs after compilation.

Awesome! Let me know if you want me to try out some version of this wip on our big project to see the effect in practice (or in any other way I can help).

**Comment by dvic** [comment]
Hi @msaraiva! One question: are the changes you have planned regarding `#4` dependant upon https://github.com/phoenixframework/phoenix_live_view/pull/1747? If so, do you have any idea if there's a timeframe for merging that PR? (it's been open since november) We're reassessing our decision not to upgrade (we're encountering more and more lv 0.16/0.17 dep incompatibilities) but before we do that I thought to ask about the latest updates/plan.

Thanks! And once again, if there's anything I can do to help please let me know!

**Comment by msaraiva** [comment]
Hi @dvic!

> are the changes you have planned regarding `#4` dependant upon https://github.com/phoenixframework/phoenix_live_view/pull/1747?

No. They can be done independently. As a matter of fact, we already started working on `#4`. We should have a PR for that one very soon.

**Comment by kernel-io** [comment]
Just wondering if we will see more on this when LV 0.18 drops?

**Comment by kernel-io** [comment]
https://github.com/surface-ui/surface/pull/653

seems to be fixed with this @dvic (at least for me and a few other users on Slack).
this will be released independently of LV 0.18

**Comment by dvic** [comment]
> #653
> 
> seems to be fixed with this @dvic (at least for me and a few other users on Slack). this will be released independently of LV 0.18

Yup, fixes it for us as well! Major win 🎉

**Comment by msaraiva** [comment]
Fixed in https://github.com/surface-ui/surface/pull/653
