### ISSUE TITLE
Fragment template sets phx-target to :live_view

### ISSUE THREAD

**Issue by Menkir** [surface-ui/surface#555]
## Describe the bug
The application consists of a LiveView and a LiveComponent. The component renders a button in a separate function whose event is to be processed in the component.  Instead, the event is sent to the LiveView so that an error is thrown: 
`** (UndefinedFunctionError) function TestWeb.PageLive.handle_event/3 is undefined or private`
## How to reproduce it
```elixir
defmodule TestWeb.PageLive do
  use Surface.LiveView
  alias TestWeb.Component
  def render(assigns) do
    ~F"""
    <div>
      <Component id="my-comp"/>
    </div>
    """
  end
end

defmodule TestWeb.Component do
  use Surface.LiveComponent
  def render(assigns) do
    ~F"""
    <div>
      <h1>component</h1>
      {button(assigns)}
    </div>
    """
  end

  def button(assigns) do
    ~F"""
    <button :on-click="click"></button>
    """
  end

  def handle_event("click", _, socket) do
    IO.inspect "clicked :D"
    {:noreply, socket}
  end

end

```

## The behavior you expected
I expect the LiveComponent that renders the button to also receive the event. 
The bug can be worked around if the entire template is inside the `render/1` function.
## Your Environment
Surface: v0.7.0
LiveView: v0.17.5
Elixir: v1.12.1

**Comment by elliotb** [comment]
I'm also seeing something similar where an event from a stateful component isn't respecting the target given, and is instead attempting to be handled by the LiveView.

With a set up of LiveView -> ComponentA -> ComponentB, inside ComponentB I have a button tag that has `:on-click={"select-item", target: "#component-a-dom-id"}`. Prior to upgrading to Surface v0.7 (from 0.6.x), the handle_event function defined on ComponentA would process the event, but after upgrading the handle_event function on the parent LiveView is being called instead, causing the LiveView to crash.

**Comment by elliotb** [comment]
> I'm also seeing something similar where an event from a stateful component isn't respecting the target given, and is instead attempting to be handled by the LiveView.
> 
> With a set up of LiveView -> ComponentA -> ComponentB, inside ComponentB I have a button tag that has `:on-click={"select-item", target: "#component-a-dom-id"}`. Prior to upgrading to Surface v0.7 (from 0.6.x), the handle_event function defined on ComponentA would process the event, but after upgrading the handle_event function on the parent LiveView is being called instead, causing the LiveView to crash.

In the above scenario, the HTML generated by v0.6 is as follows:

`<button phx-click="select-item" phx-target="#component-a-dom-id" class="block w-full h-full" phx-value-item-id="x" phx-value-area-id="y">`

for v0.7 it generates:

`<button phx-click="[[&quot;push&quot;,{&quot;event&quot;:&quot;select-pupil&quot;,&quot;target&quot;:&quot;#component-a-dom-id&quot;}]]" class="block w-full h-full" phx-value-item-id="x" phx-value-area-id="y">`

**Comment by elliotb** [comment]
> I'm also seeing something similar where an event from a stateful component isn't respecting the target given, and is instead attempting to be handled by the LiveView.
> 
> With a set up of LiveView -> ComponentA -> ComponentB, inside ComponentB I have a button tag that has `:on-click={"select-item", target: "#component-a-dom-id"}`. Prior to upgrading to Surface v0.7 (from 0.6.x), the handle_event function defined on ComponentA would process the event, but after upgrading the handle_event function on the parent LiveView is being called instead, causing the LiveView to crash.

In the above scenario, the HTML generated by v0.6 is as follows:

`<button phx-click="select-item" phx-target="#component-a-dom-id" class="block w-full h-full" phx-value-item-id="x" phx-value-area-id="y">`

for v0.7 it generates:

`<button phx-click="[[&quot;push&quot;,{&quot;event&quot;:&quot;select-item&quot;,&quot;target&quot;:&quot;#component-a-dom-id&quot;}]]" class="block w-full h-full" phx-value-item-id="x" phx-value-area-id="y">`

**Comment by msaraiva** [comment]
Hi @Menkir and @elliotb!

That's the expected behavior. Surface can only set the target automatically as `@myself` when the event is defined inside a live component, i.e., inside the `render/1` function of a module using `SurfaceLive.Component`. In the provided example:

```elixir
  def button(assigns) do
    ~F"""
    <button :on-click="click"></button>
    """
  end
```

The event `"click"` is defined inside an ordinary function, which has no knowledge of any assign called `@myself`.  That function can be called by any other component, live component or liveview so we can not blindly assume it will have that assign or not. For cases like this, you have to pass the target explicitly. Like:

```elixir
defmodule TestWeb.Component do
  use Surface.LiveComponent

  def render(assigns) do
    ~F"""
    <div>
      <h1>component</h1>
      <.button target={@myself}/>
    </div>
    """
  end

  def button(assigns) do
    ~F"""
    <button :on-click={"click", target: @target}></button>
    """
  end
  ...
end
```

Ideally, to could make the function even more flexible and pass the event as a whole:

```elixir
defmodule TestWeb.Component do
  use Surface.LiveComponent

  def render(assigns) do
    ~F"""
    <div>
      <h1>component</h1>
      <.button click={"click", target: @myself}/>
    </div>
    """
  end

  def button(assigns) do
    ~F"""
    <button :on-click={@click}></button>
    """
  end
  ...
end
```

**Comment by Menkir** [comment]
Thank you @msaraiva  for the explanation!

**Comment by elliotb** [comment]
Thanks @msaraiva. 

In my case, it was that using the DOM ID as the target wasn't working correctly.

I've refactored `ComponentB` to have an event prop for `select_item`, and then in ComponentA I set this to `{"select-item", target: @myself}` and this then works as expected. As a bonus it's neater too as `ComponentB` no longer needs to have knowledge of the DOM ID of `ComponentA`.
