### ISSUE TITLE
Sibling or child target not working with :on-click={"toggle", target: "#cssID"}

### ISSUE THREAD

**Issue by schnittchen** [surface-ui/surface#557]
## Describe the bug

I have a `<Button click={"toggle", target: "#create_channel"}>` inside a Surface.LiveView which targets a sibling component. After upgrading, this stopped working. The LiveView handle_event function is now being called with an unrecognized message, the first argument being a JSON string of a nested data structure, and the generated DOM looking similar to what's described in this comment https://github.com/surface-ui/surface/issues/555#issuecomment-1014735854.

## How to reproduce it

Below is a reproduction of what is happening with the current versions. Only the "Second button" shows the MyModal content. Using `:on-click=` (or `click=` through a nested component) does not work.

## Your Environment
Surface: v0.7.0 (after upgrading from 0.6.1)
LiveView: v0.17.5 (after upgrading from 0.16.4)
Elixir: v1.13.1

```elixir
defmodule MyModal do
  use Surface.LiveComponent

  slot header
  slot body, required: true
  slot footer

  data show?, :boolean, default: false

  def render(assigns) do
    ~F"""
    <div id={@id} :show={@show?}>
      <#slot name="body" />
    </div>
    """
  end

  def hide(id) do
    send_update(__MODULE__, id: id, show?: false)
  end

  def handle_event("toggle", _, socket) do
    {:noreply, assign(socket, :show?, !socket.assigns.show?)}
  end
end

defmodule MyButton do
  use Surface.Component

  prop click, :event
  prop class, :css_class
  prop type, :string, default: "button"
  prop form, :string

  slot default

  def render(assigns) do
    ~F"""
    <button :on-click={@click} class={@class} type={@type} form={@form}>
      <#slot />
    </button>
    """
  end
end

defmodule MyLive do
  use Surface.LiveView

  def render(assigns) do
    ~F"""
      <button class="button is-info" :on-click={"toggle", target: "#my-modal"}>First button</button>
      <button class="button is-info" phx-click="toggle" phx-target="#my-modal">Second button</button>
      <MyButton class="btn-accent-welect" click={"toggle", target: "#my-modal"}>Third button</MyButton>
      <MyModal id="my-modal">
        <:body>Body shown</:body>
      </MyModal>
    """
  end
end
```

**Comment by msaraiva** [comment]
Hi @schnittchen!

Thank you for reporting this issue. It turned out this was a [bug](53bb1c5a1af8a5f3e033bf97f117291907dbae73) in liveview. Chris has just released a new patch version fixing it. Please update `phoenix_live_view` to  `v0.17.6` and let us know if you still run into any problem.

**Comment by schnittchen** [comment]
Nope, the problem is still present.

**Comment by msaraiva** [comment]
@schnittchen are you sure you're using `0.17.6`? I tested the following code in vanilla LV and confirmed the issue. As soon as I updated it, it worked flawlessly.

```elixir
defmodule MyLiveComponent do
  use Phoenix.LiveComponent

  def mount(socket) do
    {:ok, assign(socket, :count, 0)}
  end

  def render(assigns) do
    ~H"""
    <div id={@id}>
      <%= @count %>
    </div>
    """
  end

  def handle_event("inc", _, socket) do
    {:noreply, assign(socket, :count, socket.assigns.count + 1)}
  end
end

defmodule MyAppWeb.TargetBug do
  use MyAppWeb, :live_view

  alias Phoenix.LiveView.JS

  def render(assigns) do
    ~H"""
    <div>
      <button class="button is-info" phx-click="inc" phx-target="#live_comp">
        It works!
      </button>
      <button class="button is-info" phx-click={JS.push("inc", target: "#live_comp")}>
        It works only on LV v0.17.6!
      </button>
      <h2>
        <.live_component module={MyLiveComponent} id="live_comp"/>
      </h2>
    </div>
    """
  end
end
``` 

The `phx-click={JS.push("inc", target: "#live_comp")}` is what is generated by surface when using `:on-click={"inc", target: "#live_comp"}`.

If you run the above code in your project and it doesn't work, that means either you're not using `v0.17.6` or we have a different bug in surface. Please check your `mix.lock` file to make sure mix is picking the right version. You may also try to remove the `_build` folder and see if it makes any difference. 

After trying that out, in case you still have any issue, please let me know so I can do further investigation.

**Comment by msaraiva** [comment]
Oh, and most importantly, since the bug fix was all about JS stuff, make sure you're using the updated liveview's `.js` file. If you're using `npm`, nuke `node_modules`, run `npm install` and give another try.

**Comment by schnittchen** [comment]
That pointed me in the right direction: I had not upgraded the `phoenix_live_view` _npm package_.

Thank you <3

**Comment by dvic** [comment]
> That pointed me in the right direction: I had not upgraded the `phoenix_live_view` _npm package_.
> 
> Thank you <3

This is something that happens to me so often 🙃, wish there was some server-side check in `dev` mode that emits a warning for this (in LiveView) 🙂

**Comment by schnittchen** [comment]
Is there always a release of one package when one is done for the other, of the exact same version? If so, I'm considering adding a check for this in our CI.

**Comment by dvic** [comment]
Note sure, but it looks like this is standard practice: https://github.com/phoenixframework/phoenix_live_view/commits/master/package.json

**Comment by karlosmid** [comment]
For `esbuild` users, here was my problem:

Hi! I found the root cause of the problem with my `esbuild`. `esbuild` the first folder to look for the package is `./node_modules` folder, not the `deps` folder. I had there incompatible phoenix_live_view package. Manifestation is that surface live view events propagation did not work:

Tip: `rm -rf ./node_modules`

Then use `mix assets.clean`
`mix assets.setup`
