### ISSUE TITLE
Use with live layout

### ISSUE THREAD

**Issue by gabrielrinaldi** [surface-ui/surface#558]
Is it possible to use Surface components on the `live.html.heex` layout? 

I've updated my application according to the recommended instructions [here](https://surface-ui.org/usage_with_phoenix_templates) by updating all macros to use `Surface` modules. 

But when I try to use a Surface component on the `heex` file I get a compilation error saying that I have an invalid tag. Note that using that component in another `Surface` live view works.

**Comment by gabrielrinaldi** [comment]
Also, using `Surface.View` according to the documentation [here](https://github.com/surface-ui/surface/blob/master/lib/surface/view.ex) gives me the following error:

```
cannot make function __mix_recompile__?/0 overridable because it was not defined
```

**Comment by guisehn** [comment]
> Also, using `Surface.View` according to the documentation [here](https://github.com/surface-ui/surface/blob/master/lib/surface/view.ex) gives me the following error:
> 
> ```
> cannot make function __mix_recompile__?/0 overridable because it was not defined
> ```

Did `use Phoenix.View` get removed on your `view/0`?

Both `use Phoenix.View, [...]` and `use Surface.View, [...]` need to be present, and `use Phoenix.View` needs to come first.

**Comment by msaraiva** [comment]
@guisehn I wonder if it wouldn't be better to make `use Surface.View` already inject the required `use Phoenix.View`. Is there any problem you foresee using this approach?

**Comment by gabrielrinaldi** [comment]
> Did use Phoenix.View get removed on your view/0 on [your_app]_web.ex?

Yes, it did, let me try without it. Should the template option be on the `Phoenix` one or on the `Surface` one? 

Also, for the other macros in `[your_app]_web.ex` I also just replaced it, would that approach be fine on the other places? 

@msaraiva I think that would be great if possible since it would be more consistent with the other docs and uses.

**Comment by gabrielrinaldi** [comment]
I tested it, but while the compile error goes away, I still cannot use Surface components on the live view nor rename the files to `sface`. 

My goal is to have a global template like you would normally have with `Surface` components like NavagationBar and others on it.

**Comment by clone1018** [comment]
Hey there, I ran through this morning to figure out exactly how it works, here's the steps that work for me:
1. Add Surface.View to your `view/0` macro in your web entrypoint. (Normally `lib/yourapp_web.ex`)
```
  def view do
    quote do
      use Phoenix.View,
        root: "lib/yourapp_web/templates",
        namespace: YourappWeb

      # Include shared imports and aliases for views
      unquote(view_helpers())

      use Surface.View,
        root: "lib/yourapp_web/templates"
    end
  end
  ```
  2. Add your live layout (if you don't already have one) to `live_view/0` macro in the web entrypoint. 
  ```
 def live_view do
    quote do
      use Surface.LiveView,
        layout: {YourappWeb.LayoutView, "live.html"}

      alias YourappWeb.Router.Helpers, as: Routes

      unquote(view_helpers())
    end
  end
  ```
  3. Create a new `live.sface` file in `lib/yourapp_web/templates/layout/` and use fully qualified names to your components. I'm sure there's a way to shorten these, but I haven't figured that out yet! 
```
<Yourapp.Components.Layout id="layout" some_prop={@some_global_var}>
    <Yourapp.Components.NavBar />
    <div class="container"> 
        {@inner_content}
    </div>
</Yourapp.Components.Layout>
```

**Comment by gabrielrinaldi** [comment]
@clone1018 thank you so much for this, that worked.

Out of curiosity, why do you include the `html` here: `layout: {YourappWeb.LayoutView, "live.html"}` but on the file name that is not included? This is why a lot of the things I was trying were not working. 

Personally, I think it is a little confusing that you name it with the `html` "extension" but the file does not include that.

**Comment by guisehn** [comment]
> @guisehn I wonder if it wouldn't be better to make use Surface.View already inject the required use Phoenix.View. Is there any problem you foresee using this approach?

I think we can do that.

One caveat is that `Surface.View` doesn't support additional options supported by `Phoenix.View` like [`namespace` and others](https://hexdocs.pm/phoenix_view/Phoenix.View.html#__using__/1). We had an example of one user that had a custom namespace [here](https://elixir-lang.slack.com/archives/C01220C92QM/p1642257804058700).

I wonder if we change the API to require only `use Surface.View`, would users expect that it supports all the same options as `Phoenix.View`? In that case should we implement these options first?

**Comment by guisehn** [comment]
> 3. Create a new `live.sface` file in `lib/yourapp_web/templates/layout/` and use fully qualified names to your components. I'm sure there's a way to shorten these, but I haven't figured that out yet!
> 
> ```
> <Yourapp.Components.Layout id="layout" some_prop={@some_global_var}>
>     <Yourapp.Components.NavBar />
>     <div class="container"> 
>         {@inner_content}
>     </div>
> </Yourapp.Components.Layout>
> ```

@clone1018 since `live.sface` is rendered by `YourappWeb.LayoutView`, you can add the aliases you need to `YourappWeb.LayoutView` and they'll be applied on the template file, e.g.

```elixir
defmodule YourappWeb.LayoutView do
  use YourappWeb, :view

  alias Yourapp.Components.Layout

  # ...
end
```

**Comment by guisehn** [comment]
> @clone1018 thank you so much for this, that worked.
> 
> Out of curiosity, why do you include the `html` here: `layout: {YourappWeb.LayoutView, "live.html"}` but on the file name that is not included? This is why a lot of the things I was trying were not working.
> 
> Personally, I think it is a little confusing that you name it with the `html` "extension" but the file does not include that.

I agree it's confusing.

This has to do with supporting `render/1` on controllers. For example, if we have a `page_controller.ex` with:

```elixir
defmodule YourAppWeb.PageController do
  use YourAppWeb, :controller

  def index(conn, _params) do
    render(conn)
  end
end
```

The `render` call on `index/2` will dispatch a `PageView.render("index.html", assigns)` under the hood, so we need to generate a `render("index.html", _)` to render `index.sface` even though `index.sface` doesn't have html in its name.

**Comment by simonmcconnell** [comment]
@zoedsoupe what version are you on?  Looks pretty similar to my setup...

```elixir
  def view do
    quote do
      use Phoenix.View,
        root: "lib/nocodo_io_web/templates",
        namespace: NocodoIoWeb

      use Surface.View,
        root: "lib/nocodo_io_web/templates"

      # Import convenience functions from controllers
      import Phoenix.Controller,
        only: [get_flash: 1, get_flash: 2, view_module: 1, view_template: 1]

      # Include shared imports and aliases for views
      unquote(view_helpers())
      import Surface
    end
  end

  def surface_live_view do
    quote do
      use Surface.LiveView

      unquote(view_helpers())
    end
  end
```
