### ISSUE TITLE
Surface.BaseComponent.__before_compile__ "module Surface.Components.Dynamic.LiveComponent.X is not loaded and could not be found"

### ISSUE THREAD

**Issue by RealVidy** [surface-ui/surface#560]
## Describe the bug

After upgrading to Surface 0.7 and LV 0.17.6 (from Surface 0.5 and LV 0.16), I cannot compile my project anymore with errors in every file that uses a Surface LiveComponent that look like this:

```bash
== Compilation error in file lib/myapp_web/live/my_live.ex ==
** (CompileError) lib/myapp_web/live/my_live.ex:209: module Surface.Components.Dynamic.LiveComponent.MyModule is not loaded and could not be found. This may be happening because the module you are trying to load directly or indirectly depends on the current module
    (surface 0.7.0) expanding macro: Surface.BaseComponent.__before_compile__/1
    lib/myapp_web/live/my_live.ex:1: MyappWeb.SomeOtherLive (module)
```

I am also getting warnings for all of my LiveComponents with the same kind of issue:

```bash
warning: cannot render <SomeSurfaceLiveComponent> (module Surface.Components.Dynamic.LiveComponent.MyModule could not be loaded)
  lib/myapp_web/my_file.ex:282: LiveComponent.MyModule.render/1
```

Starting a brand new project with the surface demo files and the same versions of Elixir, Surface and LV work fine however, so it looks like I need to do something to migrate from Surface 0.5 to 0.7 but I cannot figure out what it is.

I did not test with multiple deeply nested LiveComponents though, whereas my buggy project has lots of them. This might also be the issue here?

How can I go about debugging this?

## Your Environment
Surface: v0.7
LiveView: v0.17.6
Elixir: v1.13

**Comment by RealVidy** [comment]
Alright, this is a fun one! 

The issue was that my modules are defined like this `demodule LiveComponent.MyModule do`. If I rename to `demodule SomethingElse.MyModule do`, it compiles fine!

**Comment by msaraiva** [comment]
In case anyone faces the same issue, the reason is that Surface has a built-in `Surface.Dynamic.LiveComponent` module witch is already aliased as `LiveComponent` so you can't have a module/namespace with that same name in components.
