### ISSUE TITLE
Nested render functions do not render :on-click correctly

### ISSUE THREAD

**Issue by Coffei** [surface-ui/surface#566]
## Description

While migrating from 0.5.1 to 0.7.0 I noticed that nested render functions do not work correctly anymore. We often use nested render functions to break up HTML into multiple smaller functions, instead of having one single giant render function.

In principle this is something like this

```elixir
  def render(assigns) do
    ~F"""
    <section class={"phx-hero", "alert-#{@color}": @color}>
      <h1>Hi, {@name}</h1>
      <p>{@subtitle}</p>
      <p>Time is {@time}</p>
      <p><button :on-click="click">Click me in render/1.</button></p>
      {render_click(assigns)}
    </section>
    """
  end

  defp render_click(assigns) do
    ~F"""
    <p><button :on-click="click">Click me in render_click/1.</button></p>
    """
  end
```

The issue I stumbled upon is that `:on-click` in the nested render is not correct. In the example, the first `:on-click` is rendered as
```
phx-click='[["push",{"event":"click","target":1}]]'
```

while the other one is rendered only as 

```
phx-click="click"
```

and therefore the second event is routed to the parent Live View.

I am sure this worked in 0.5.1 as we relied on this.

## How to reproduce it
Simple, I prepared a reproducer - https://github.com/Coffei/surface_multi_render_reproducer, see README for instructions.

## Your Environment
Surface: v0.7.0
LiveView: 0.17.7
Elixir: v1.12.1

**Comment by Coffei** [comment]
I also noticed our uploads to stop working, I am seeing

```
** (ArgumentError) no uploads have been allowed on LiveView named Module.Of.The.Top.LiveView
```

It shows the module of the top live view instead of the component that allows the upload.

**Comment by miguel-s** [comment]
Hi @Coffei!

Thanks for providing a sample app for reproducing the issue!

LiveView 0.17 introduced [Function Components](https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html), which are almost the same thing as your render functions, but require more explicit handling of passing assigns and settings targets.

I managed to get your example working with just a few changes:

```elixir
  def render(assigns) do
    ~F"""
    <section class={"phx-hero", "alert-#{@color}": @color}>
      <h1>Hi, {@name}</h1>
      <p>{@subtitle}</p>
      <p>Time is {@time}</p>
      <p><button :on-click="click">Click me in render/1.</button></p>
      <.render_click target={@myself} /> # Use new notation and pass the event target as an assign
    </section>
    """
  end

  defp render_click(assigns) do
    ~F"""
    <p><button :on-click={"click", taget: @target}>Click me in render_click/1.</button></p> # Set the target for the event from the assign
    """
  end
```

By using the new notation you also get the benefit of improved change tracking ;)

**Comment by Coffei** [comment]
That's great! It would be cool to at least mention that in the README, although I am not sure how supported/recommended were the render functions before.

I'll also investigate the upload errors once again, I think they weren't directly affected by the first issue, since I put everything into single render fun and saw these errors. Will check that, add it to the reproducer and post the results here.

Thanks.

**Comment by Coffei** [comment]
The upload is still problematic and I don't see a way to resolve it in the same way, see the reproducer at https://github.com/Coffei/surface_multi_render_reproducer/tree/upload.

When I upload the form I see 
```
** (ArgumentError) no uploads have been allowed on LiveView named SurfaceMultiRenderReproducerWeb.Demo
``` 
which would indicate the core issue is the same - upload is not handled in the component but rather in the parent Live View.

The upload file input is generated via function, so it definitely looks like the original problem

```
{live_file_input(@uploads.upload)}
```

However, AFAIK here we don't have the option of using function components, because of the `live_file_input` signature. Downgrading fixes the issue, same as described above.

Any idea how to fix this?

**Comment by Coffei** [comment]
Amazing, thanks for the fast response! This unblock me form the upgrade to LV 0.17 and Surface 0.7, will give this another shot. Thank you again!
