### ISSUE TITLE
Hooks are being copied to all projects inside an umbrella

### ISSUE THREAD

**Issue by gushonorato** [surface-ui/surface#567]
## Describe the bug

A hook from one project inside an umbrella project is being copied to the assets folder of the other project in the same umbrella project.

## How to reproduce it
1. Create an umbrella project
2. Create two web projects ("A" and "B") inside this umbrella project
3. Create a component with a JavaScript hook on project "A"
4. Build the project
5. Check that the hook created in project "A" is also present in "B"

## The behavior you expected

The desired behavior is that the hook created on project A do not be copied to project B. Copying all hooks to all projects causes an unnecessary increase of app.js final file size since the most common are components used in project A is not being used in project B.

## Your Environment
Phoenix: 1.6.6
Surface: v0.7.0
LiveView: v0.17.6
Elixir: v1.13.2

**Comment by msaraiva** [comment]
Fixed in https://github.com/surface-ui/surface/pull/591.
