### ISSUE TITLE
_target is lost on Form updates with 0.7.1

### ISSUE THREAD

**Issue by kernel-io** [surface-ui/surface#572]
## Describe the bug

After updating to Surface 0.7.1 from 0.7.0 the correct `_target` is no longer sent along with Form `change` events. This has broken a few of my forms which depend on knowing which inputs have triggered the form change events.

This seems to be due to switching to the `JS.push` API in this commit https://github.com/surface-ui/surface/commit/6aab9139c66bc242be6d6c58d1c2e7ad646504aa, the traditional way still works as expected.

Here is an open bug by Chris McCord regarding this problem in LiveView.

https://github.com/phoenixframework/phoenix_live_view/issues/1850

I'd expect the target to be sent as per normal.
![image](https://user-images.githubusercontent.com/1523960/156280601-678b8844-0dbe-472a-87e7-1806832f10fe.png)

instead of arriving like this
![image](https://user-images.githubusercontent.com/1523960/156280621-c2f36674-a5d1-47c2-9162-54e73839c61f.png)

## Your Environment
Surface: v0.7.1
LiveView: v0.17.7
Elixir: v1.13.3

**Comment by msaraiva** [comment]
@kernel-io yeah, it's a LV bug. We can't just revert that commit as we need to use `JS.push` to properly set the target. I'm not sure how complex is to fix that in LV but it seems quite critical so I hope it will be fixed soon. The only workaround I can think of is to maybe pass the `phx_change` explicitly along with the `phx_target` using the `opts` prop.

**Comment by kernel-io** [comment]
wonderful idea, I just reverted to 0.7.0, I'll try setting that attribute via `opts` and update if it doesn't work.

**Comment by dvic** [comment]
For me it worked (setting `opts={phx_target: @myself}`)

**Comment by kernel-io** [comment]
> For me it worked (setting `opts={phx_target: @myself}`)

This doesn't resolve the issue that this issue is about, this is about `_target` not being set on change events, usually it contains the name of the input which triggered the change.

**Comment by dvic** [comment]
Ahh I see, but is this problem not also linked to the issue of the event itself being sent to the wrong target? But good point!

**Comment by kernel-io** [comment]
nope, but I've just run into that issue you are referring to 😆

**Comment by msaraiva** [comment]
I'm closing this as it can only be fixed in LV itself. To follow the issue please see https://github.com/phoenixframework/phoenix_live_view/issues/1850.
