### ISSUE TITLE
using Surface.View breaks on_mount changes to the socket 

### ISSUE THREAD

**Issue by sezaru** [surface-ui/surface#589]
## Describe the bug

I'm following this tutorial https://fly.io/phoenix-files/liveview-active-nav/ to update the navigation buttons with the current page information.

The way it is done is by adding some logic to a `live_session` `on_mount` option which will assign the value to the socket. This works fine with a default `root.html.heex` file, but my navigation component is a `Surface.Component` so I changed it to support surface and rename it to `root.sface` as described here: https://github.com/surface-ui/surface/blob/main/lib/surface/view.ex

The issue is that after this change, the assigned value doesn't propagate the change to the `sface` value even though the function is being called and is changing the socket.

## How to reproduce it
You can follow the tutorial linked above, but you basically need to create the nav file, here is mine:

```elixir
defmodule FbpEnterpriseWeb.Nav do
  @moduledoc false

  alias FbpEnterpriseWeb.{MainLive, CounterLive}

  import Phoenix.LiveView

  def on_mount(:default, _params, _session, socket) do
    {:cont, attach_hook(socket, :active_tab, :handle_params, &set_active_tab/3)}
  end

  defp set_active_tab(_params, _url, socket) do
    active_tab =
      case {socket.view, socket.assigns.live_action} do
        {MainLive, _} -> :users
        {CounterLive, _} -> :counter
        {_, _} -> nil
      end

    IO.inspect(active_tab)

    {:cont, assign(socket, active_tab: active_tab)}
  end
end
```

Create the `MainLive` and `CounterLive`, both as `Surface.LiveView`.

In router, add this:

```elixir
    live_session :admin, on_mount: [FbpEnterpriseWeb.Nav] do
      live "/", MainLive
      live "/counter", CounterLive
    end
```

And in the `root.sface` file, add this to the `body`:

```elixir
{@active_tab}
{live_redirect "counter", to: "/counter"}
```

Now from the `MainLive` page, you will see that `@active_tab` is settled correctly to `:users`, but if you click on the `counter` link, you will be redirected to the `/counter` route, the `FbpEnterpriseWeb.Nav` `on_mount` function will be called but `root.sface` will keep `@active_tab` as `:users` instead of `:counter`.

## Your Environment
Surface: v0.7.1
LiveView: v0.17.5
Elixir: v1.13.4

**Comment by miguel-s** [comment]
Hi @sezaru

You need to use the `live` layout instead of the `root` layout, the tutorial mentions it here https://fly.io/phoenix-files/liveview-active-nav/#defining-the-sidebar-markup.

I actually followed the same tutorial for one of my apps and got it working without issues, only difference is that I left the `root.html.heex` untouched and changed `live.html.heex` to `live.sface`.

Let me know if I can help you get this working.

**Comment by sezaru** [comment]
Thank you @miguel-s that was exactly the problem!
