### ISSUE TITLE
Style attribute does not accept a list of style strings

### ISSUE THREAD

**Issue by joshprice** [surface-ui/surface#593]
LiveView accepts a list of string for a style attribute, and automatically concatenates them:

```html
<div style={[
  "style1: style1;",
  "style2: style2;"
]} />
```

Note that LV only joins the strings together with spaces " " (not semi colons ";") so we have to add our own semi-colons above. In our specific instance the styles are for CSS grid and are quite long, so are formatted as above for readability. I've simplified our real example for clarity.

Surface doesn't accept this so an `Enum.join()` is required to concatenate the strings manually.

```html
<div style={[
  "style1: style1",
  "style2: style2"
] |> Enum.join(";")} />
```

## Expected behaviour

It would be nice if Surface mimicked the LV behaviour by auto-joining with spaces as follows:

```html
<div style={[
  "style1: style1;",
  "style2: style2;"
]} />
```

should produce:

```html
<div style="style1: style1; style2: style2;" />
```

## Expected behaviour (if Surface was a mind-reader)

It would be amazing if Surface could detect that we're in a style attr and automatically join with semi-colons (;) in which case

```html
<div style={[
  "style1: style1",
  "style2: style2"
]} />
```

should produce:

```html
<div style="style1: style1; style2: style2;" />
```

## Your Environment

Surface: v0.7.3
LiveView: v0.17.9
Elixir: v1.13.3-otp-24

**Comment by miguel-s** [comment]
Hi @joshprice 

Surface does have a bit of magic for certain attributes like `class` and `style`.

In the case of the `style` attribute Surface accepts keyword lists and renders them as expected into a string:

```elixir
<div style={[style1: "style1", style2: "style2"]} />
```

will produce:

```html
<div style="style1: style1; style2: style2;" />
```

Surface also let's you ommit the square brackets when passing keyword lists to attributes:

```elixir
<div style={style1: "style1", style2: "style2"} />
```

will also produce:

```html
<div style="style1: style1; style2: style2;" />
```

Could you give this a try and see if it covers your issue?

**Comment by joshprice** [comment]
Perfect thanks! 👌
