### ISSUE TITLE
Request: Animation system

### ISSUE THREAD

**Issue by sevensidedmarble** [surface-ui/surface#607]
See: https://github.com/surface-ui/surface/issues/218

In #218, it was determined that LV itself had plans to implement an animations system like the one in Svelte, for convenient transitions when elements leave/enter the page. It's been a while since #218 and to my knowledge that system has yet to materialize in LV. Would it be possible to reopen the idea here?

There is a library which has made some cool progress on this concept here: https://github.com/benvp/live_motion

**Comment by msaraiva** [comment]
@sevensidedmarble what Surface could bring to the table in terms of API that could improve DX when compared to just use LiveMotion directly?
