### ISSUE TITLE
Confusing error message when incorrectly using the default slot

### ISSUE THREAD

**Issue by davydog187** [surface-ui/surface#620]
## Describe the bug
When trying to render the default slot as a named slot, you will get the following error message

> Error: cannot render <div> (templates are only allowed as children elements of components, but found template for slot)

## How to reproduce it
1. Create a component with a default slot `slot default`
2. In the template, render the slot as named `<:slot />`
3. Observe the above error

## The behavior you expected
Have a better error message, such as:

> No slot found named `slot`. Did you mean `<#slot />`?

## Your Environment
Surface: v0.7.4
LiveView: v0.17.10

Hex:    1.0.1
Elixir: 1.13.4
OTP:    25.0

**Comment by msaraiva** [comment]
Fixed in #628.
