### ISSUE TITLE
surface-ui.org seems outdated

### ISSUE THREAD

**Issue by Gilou06** [surface-ui/surface#633]
This is more a question than a bug report, I could not find where I could ask a question.

https://surface-ui.org/ seems outdated. I wonder if the plan is to drop the site in favor of hexdocs.pm or to get it updated sometimes.
For example, I could not find Dynamic components there.
Also I could not find the Sample UI Components in Surface v0.7.4 nor in V0.7.5

Anyway, I'm having great fun using Surface. 
About Dynamic components, I found the feature by chance, I just tried 
`  <Component module={@data_module.gui_module} {=@displayed_data} {=@display_style} />` and it worked !

Cheers
Jean-yves :)

**Comment by msaraiva** [comment]
Thanks for reporting this. 

Fixed in [e8058cd5fa4d5c684743325f7e8a850437bd571f](https://github.com/surface-ui/surface_site/commit/e8058cd5fa4d5c684743325f7e8a850437bd571f).

**Comment by tiagoefmoraes** [comment]
> I wonder if the plan is to drop the site in favor of hexdocs.pm or to get it updated sometimes.

We'll simplify the site and improve the other documentation sources: https://github.com/surface-ui/surface/issues/643#issuecomment-1234202221
