### ISSUE TITLE
dialyzer complains since v0.8.2 

### ISSUE THREAD

**Issue by dvic** [surface-ui/surface#654]
Since e8aea39, I'm getting dialyzer errors across my project in the form of

```
lib/my_web/some_file.ex:1:pattern_match
The pattern can never match the type.

Pattern:
false

Type:
true
```

cc @tiagoefmoraes

**Comment by tiagoefmoraes** [comment]
@dvic I suspect it's these [lines](https://github.com/surface-ui/surface/commit/e8aea39ce29d4025a1446abe65c3d7c752675a9d#diff-96328b37fbe00256a44961d185c56d2b6812ccf64fd5108cbc8cf9b4a1b2f2ecR610-R613) but couldn't reproduce it, can you create a repo with this issue?

**Comment by dvic** [comment]
Unfortunately I can't reproduce it but commenting out those lines indeed fixes the problem!

**Comment by dvic** [comment]
I found a solution: add `generated: true` to the `quote` call and Dialyzer ignores it :)

Now the question is: should all of the AST generated by Surface have `generated: true` or do we just add it to this part?

**Comment by msaraiva** [comment]
@dvic Thanks! Adding `generated: true` makes sense there. I wonder why we're not getting any warning on our tests. 

Anyway, I think we should add it only to this part, for now. Would you be willing to submit a PR with that fix?

**Comment by dvic** [comment]
Sure, will do 👍!
