### ISSUE TITLE
prop default evaluated at compile time.

### ISSUE THREAD

**Issue by jimsynz** [surface-ui/surface#658]
## Describe the bug

We recently ran into a compile failure due to a team member not understanding that the `default:` prop option is evaluated at compile time:

```elixir
 prop nav_items, :list,
    default: [
      %{name: "Home", path: "/"},
      %{name: "Apps", path: Routes.app_path(Endpoint, :index)},
      %{name: "About", path: "/about"}
    ]
```

This fails because Phoenix's router helpers only work at runtime (they rely on an ETS table containing the route information).

## How to reproduce it

1. Place any expression which can only be evaluated at runtime as a prop default.

## The behavior you expected

I'm actually okay with the compile error (although maybe a better error message would be good?), but we need to provide a way to support lazy definition of defaults.  I was thinking that an anonymous function might be the way to go, but I believe that they also have some issues with encoding in macros.  So my suggestions are two fold:

* Either store the AST for the default expression and actually evaluate it when the component is instantiated, or
* Provide a method of lazy definition of defaults.

I tried to fix it myself, but I had trouble finding/understanding where these are evaluated in the surface codebase.

## Your Environment
Surface: v0.8.2
LiveView: v0.17.11
Elixir: v1.14.0

**Comment by msaraiva** [comment]
Hi @jimsynz! 

Yeah, the values are always evaluated at compile time. If you need runtime values, you have to use `assign_new/3`. We may consider adding a way to do that in the future, but not for now, as we're working on adopting the new LV's API for declarative assigns, so we have to wait and see if there's any plan to add this feature there. If not, we may consider adding it.

I'm closing this for now but we can reopen when we have a better picture about the future plans of the API.

Cheers.

**Comment by jimsynz** [comment]
Thanks @msaraiva
