### ISSUE TITLE
v0.9.1 not tagged in GitHub

### ISSUE THREAD

**Issue by mbuhot** [surface-ui/surface#663]
## Describe the bug

Missing tag for v0.9.1 causes broken links from Hex docs, eg https://github.com/surface-ui/surface/blob/v0.9.1/lib/surface.ex#L1

## How to reproduce it

1. Go to https://hexdocs.pm/surface/Surface.html
2. Click the "View Source" link at the top right of the page

## The behavior you expected

Navigate to related Github source file successfully.

**Comment by tiagoefmoraes** [comment]
Thank you, tag created.
