### ISSUE TITLE
Slot `:as` option doesn't seem to be working

### ISSUE THREAD

**Issue by d3caf** [surface-ui/surface#668]
## Describe the bug
When providing the `:as` option to a slot, it doesn't seem that the slot is properly being added to the assigns with the provided name. I get a `KeyError` when trying to implement the slot with the provided name.

## How to reproduce it
I have the following:
```elixir
prop value, :any
slot value, as: :value_slot

def render(assigns) do
  ~F"""
   <#slot {@value_slot} />
  """
end
```

The view will not compile due to a `KeyError` saying that `value_slot` is not available.

## The behavior you expected
The slot should be usable with the name provided via the `:as` option.

## Your Environment
Surface: v0.9.1
LiveView: v0.18.2
Elixir: v1.14.1

**Comment by Malian** [comment]
Hi @d3caf 

Thanks for reporting this issue. Unfortunately, I am not able to reproduce it. These kinds of code is also present in the tests. See https://github.com/surface-ui/surface/blob/e8aea39ce29d4025a1446abe65c3d7c752675a9d/test/surface/integrations/slot_test.exs#L177-L209 for examples.

Could you please provide us the full example, or best, a minimum application that reproduce the issue.

Thanks

**Comment by d3caf** [comment]
@Malian thanks for the quick response! So it seems all is working now. I'm wondering if it was some odd compilation issue because the example code I gave was _definitely_ not working. I tested moving the `slot` above the `prop` and that seemed to magically fix it. Now it works with the `slot` back in the original place. Sorry for the false alarm!
