### ISSUE TITLE
Support Phoenix 1.7.0-rc

### ISSUE THREAD

**Issue by msaraiva** [surface-ui/surface#674]

**Comment by ThaddeusJiang** [comment]
wait in hope

**Comment by travelmassive** [comment]
Surface 0.9.2 works with Phoenix 1.7.0-rc.2 for me :)

**Comment by noozo** [comment]
Forms with `for={:bla}` issue a warning now. Same for Form.Inputs (and for this latter one i can't seem to make it work by passing `for={%{}} opts={as: :bla}` as per LV suggestion.

**Comment by simonmcconnell** [comment]
@noozo that's fixed on master. See closed PR re 0.18.14

**Comment by VictorGaiva** [comment]
Currently Phoenix isn't able to understad `.sface` files when using `embed_templates`.

**Comment by msaraiva** [comment]
Closed in #687.

@VictorGaiva I created a specific issue for that one https://github.com/surface-ui/surface/issues/688.
