### ISSUE TITLE
Question: How install sample UI components?

### ISSUE THREAD

**Issue by ChuckIrvine** [surface-ui/surface#675]
I hope you don't mind that I am asking a question here. Let me if you would rather I not do this. I thought about posting my question on the Elixir forum. In the future, I can do that if you would prefer.

How do install the sample components described here:

https://surface-ui.org/samplecomponents

I see the instructions about pulling in the Bulma styles, but it seems to me there must be more to it. I'm new to most of this stuff. Hope I'm not missing something obvious.

Thanks

**Comment by Malian** [comment]
@ChuckIrvine these components come from https://github.com/surface-ui/surface_bulma 

That being said, the documentation mention:

> **Note**: This is not a full-featured suite of components yet. Most of
  the functionality we have so far is based on the requirements we had
  to build Surface's [website](http://surface-demo.msaraiva.io).

Other components libraries exist like https://github.com/surface-ui/surface_bootstrap

Unfortunately, I am not sure these libs work with the latest versions of Surface.

Hope it helps you.
