### ISSUE TITLE
Compilation failing with liveview v0.18.5+

### ISSUE THREAD

**Issue by dougw-bc** [surface-ui/surface#676]
## Describe the bug
A lot of errors compiling with new version of liveview 0.18 (0.18.5+)

## How to reproduce it
1. Update LiveView ( `{:phoenix_live_view, "== 0.18.5"}` )
2. Run surface test suite 

This error in particular appears a bunch - and is what first caught my attention. 
```
 25) test option :form_context in live components passing the prop overrides the value from the context (Surface.Components.ContextTest)
     test/surface/components/context_test.exs:221
     ** (ArgumentError) cannot convert component Surface.Components.ContextTest.LiveComponentUsingFromContext with id "1" to HTML.
     
     A component must always be returned directly as part of a LiveView template.
     
     For example, this is not allowed:
     
         <%= content_tag :div do %>
           <.live_component module={SomeComponent} id="myid" />
         <% end %>
     
     That's because the component is inside `content_tag`. However, this works:
     
         <div>
           <.live_component module={SomeComponent} id="myid" />
         </div>
     
     Components are also allowed inside Elixir's special forms, such as
     `if`, `for`, `case`, and friends.
     
         <%= for item <- items do %>
           <.live_component module={SomeComponent} id={item} />
         <% end %>
     
     However, using other module functions such as `Enum`, will not work:
     
         <%= Enum.map(items, fn item -> %>
           <.live_component module={SomeComponent} id={item} />
         <% end %>
```

## The behavior you expected
compilation to succeed 

## Your Environment
Surface: v0.9.1 (main)
LiveView: v0.18.5 +
Elixir: v1.14.2

**Comment by mayel** [comment]
I encountered the same issue

**Comment by maennchen** [comment]
Related Issue: https://github.com/phoenixframework/phoenix_live_view/issues/2389#issuecomment-1377694005

**Comment by ivanminutillo** [comment]
any estimation for when surface will be compatible with the latest liveview version?

**Comment by mikl** [comment]
@ivanminutillo there are no deadlines or estimations. This is an open source project. In the thread linked above, Marlus has said that he’ll look into it, so you’ll have to be patient and wait. Or do it yourself, the source is right here after all.

**Comment by travelmassive** [comment]
Hey folks, I'm in the same boat. What can I do to help?

**Comment by msaraiva** [comment]
Hi everyone! I just pushed a fix to `main`. Feel free to try it out and let me know in case you find any issue.

**Comment by janwillemvd** [comment]
We can confirm it's working like a charm (tested with LV 0.18.11). Thanks @msaraiva!

**Comment by msaraiva** [comment]
Surface v0.9.2 has just been released with the fix!

**Comment by travelmassive** [comment]
Thanks @msaraiva — this fix works great! ~ Ian
