### ISSUE TITLE
Bogus "undefined assign `@streams`." warning

### ISSUE THREAD

**Issue by arkadiyk** [surface-ui/surface#695]
When I try to use LV Streams 
```
{#for {id, d} <- @streams.items}
```
The `undefined assign '@streams'.` warning shows up.

**Comment by drselump14** [comment]
Defining the streams as data solves the problem...  I hope surface could generate it automatically

**Comment by msaraiva** [comment]
Fixed in https://github.com/surface-ui/surface/commit/91ae6b3a6cb5d99d0408bf83b6ac99c2b5ffca44.
