### ISSUE TITLE
inputs_for/3 warning

### ISSUE THREAD

**Issue by dougw-bc** [surface-ui/surface#703]
## Describe the bug
The following warning is being emitted:

```
warning: inputs_for/3 without an anonymous function is deprecated. If you are using Phoenix.LiveView, use the new Phoenix.Component.inputs_for/1 component
  (phoenix_html 3.3.2) lib/phoenix_html/form.ex:606: Phoenix.HTML.Form.inputs_for/3
  (surface 0.11.0) lib/surface/components/form/inputs.ex:42: anonymous fn/2 in Surface.Components.Form.Inputs."render (overridable 1)"/1
  ...
```

Is this easy to swap? can we achieve the same surface API with the new Phoenix.Component.inputs_for/1 function component? can we just use it directly?  

## The behavior you expected
No Warnings

## Your Environment
Surface: v0.11.0
LiveView: v0.19.5
Elixir: v1.15.4

**Comment by marcandre** [comment]
Thanks for the fix... but can we expect a release?
