### ISSUE TITLE
Props missing inside `handle_event()` `socket.assigns` map.

### ISSUE THREAD

**Issue by c4lliope** [surface-ui/surface#706]
Hello - another good day using Surface here, though there is a rather perplexing case holding me up.

I am making an appt-booking application, and the scheduling logic needs to pair a number of customers demanding services alongside a number of employees who can help. These are the props, `service_keys` and `employee_keys`.

I use `data possible_by_day` to hold open hours for the customer to book, so these can be displayed on a calendar heatmap, and as clickable booking links. I load these from `Shop.Schedule.check_blocks/4` in `update/2`, because the props seem to be missing in `mount/1` - this could be a similar problem.

So `@possible_by_day` is loading properly on initial render, and then I see the case where a user changes the month on the calendar; I need to load new options for booking times. This is done in `handle_event("schedule_month", params, socket)`. Here also, `socket.assigns` is missing the necessary props, `:service_keys` and `:employee_keys`. I mucked around in Context also and had no luck accessing them inside the event.

Checking the `IO.inspect` responses in the console, on the `schedule_month` event I see the keys from both `params` and `socket.assigns` - the assigns are missing the two props I need to use, although [related docs](https://hexdocs.pm/phoenix_live_view/bindings.html) imply they should be there:
```elixir
["month"]
[:block, :day, :__changed__, :flash, :__context__, :__caller_scope_id__,
 :myself, :possible_by_day]
```

The pre-release application is running on https://assemble.codes/book -
I pre-recorded some of the user inputs so you can see the schedule component's issue on page load.
 
[Here is the code I use](https://base.bingo/code/pain/src/branch/main/lib/pain_web/components/schedule.ex) (simplified in this code block).
The commented lines are causing the error.

```elixir
defmodule ShopWeb.Components.Schedule do
  use Surface.LiveComponent
  import Shop.Schedule

  prop service_keys, :list, default: []
  prop employee_keys, :list, default: []

  data possible_by_day, :map, default: %{}
  data day, :string
  data block, :string, default: nil

  def mount(socket),
    do: {:ok, socket |> assign(:day, today() |> Date.to_string) }

  def update(assigns, socket) do
    {:ok, socket
    |> assign(:possible_by_day, message() |> check_blocks(
      assigns[:service_keys], assigns[:employee_keys], this_month()))
    }
  end

  def handle_event("schedule_day", params, socket) do
    IO.inspect params
    {:noreply, assign(socket, :day, params["day"])}
  end

  def handle_event("schedule_month", params, socket) do
    IO.inspect params |> Map.keys
    IO.inspect socket.assigns |> Map.keys

    {:noreply, socket }
    # {:noreply, socket |> assign(:possible_by_day,
    #   message() |> check_blocks(
    #   socket.assigns[:service_keys],
    #   socket.assigns[:employee_keys],
    #   month(params["month"]))
    # ) }
  end

  def render(assigns) do
    ~F"""
    <style>
    </style>

    <section class="schedule" data-day={today()}
      data-possible={@possible_by_day |> Jason.encode! } >
      <h4>Please schedule:</h4>
      <!-- ... -->
    </section>
    """
  end
end
```

**Comment by c4lliope** [comment]
As is, I accomplished my goals using a sad hackaround:

```elixir
  prop service_keys, :list, default: []
  prop employee_keys, :list, default: []

  data possible_by_day, :map, default: %{}
  data services, :list, default: []
  data employees, :list, default: []
  data day, :string
  data block, :string, default: nil

  def mount(socket),
    do: {:ok, socket |> assign(:day, today() |> Date.to_string) }

  def update(assigns, socket) do
    {:ok, socket
    |> assign(:services, assigns[:service_keys])
    |> assign(:employees, assigns[:employee_keys])
    |> assign(:possible_by_day, message() |> check_blocks(
      assigns[:service_keys], assigns[:employee_keys], this_month()))
    }
  end

  def handle_event("schedule_day", params, socket) do
    {:noreply, assign(socket, :day, params["day"])}
  end

  def handle_event("schedule_month", params, socket) do
    {:noreply, socket
    |> assign(:possible_by_day,
      message() |> check_blocks(
        socket.assigns[:services],
        socket.assigns[:employees],
        month("#{params["year"]}-#{params["month"]}"))
    )
    |> push_event("color", %{})
    }
  end

```

**Comment by simonmcconnell** [comment]
I don't know if assigning your assigns in `update` is a sad workaround... Generally, you `assign(socket, assigns)` as per the default callback that you're overriding.

**Comment by c4lliope** [comment]
ah, really? that sure is cleaner than doing them each one by one. if this is the price of admission for using the `update` callback, this makes sense. The Phoenix docs on hexdocs.pm glossed over this side effect, so I'd been unsure why some of my components that had no need for `update/2` seemed to be running properly, and this one seemed broken.

I'll see how much I can add to the docs there.
