### ISSUE TITLE
Malformed HTML when using LiveRedirect with another component inside

### ISSUE THREAD

**Issue by noozo** [surface-ui/surface#723]
## Describe the bug

When using LiveRedirect and we add another component in the default slot, we get malformed HTML error in rendered.js.

Example:

```
<li><LiveRedirect
            to={~p"/admin/companies"}
            class={admin_nav_selected_class(@socket, PassionFruitWeb.Live.Admin.Companies)}
          >Companies<.badge count={@unverified_companies} tooltip="Unverified companies" class="badge-red" /></LiveRedirect></li>
```

If we remove the `<.badge>` function component from the LiveRedirect slot, everything works fine, like so:

```
<li><LiveRedirect
            to={~p"/admin/companies"}
            class={admin_nav_selected_class(@socket, PassionFruitWeb.Live.Admin.Companies)}
          >Companies</LiveRedirect></li>
```

This only happens from LiveView 0.20.2 onwards, as 0.20.1 is still working.

Also tried making `<.badge>` a normal surface component, but same problem occurs.

**Comment by msaraiva** [comment]
Hi @noozo! 

This has been fixed in https://github.com/surface-ui/surface/tree/fix-lv-20-compat.

Feel free to try it out. It should be merged as soon as I fix another compatibility issue we've found.
