### ISSUE TITLE
Mix.env() usage can cause troubles in release

### ISSUE THREAD

**Issue by clsource** [surface-ui/surface#734]
## Describe the bug

When using 

```
mix surface.init --catalogue
```

It creates a new route in `router.ex` with the catalogue routes.
But it is using `Mix.env()` to check these routes.

```elixir
if Mix.env() == :dev do
    scope "/" do
      pipe_through :browser
      surface_catalogue "/catalogue"
    end
  end
```

## Possible Fix

We can create a new module constant `@env` to fetch the value at compile time
and check the value afterwards in runtime. Since `Mix` would no be available in runtime
at production release.

```elixir
defmodule MyWeb.Router do
  use MyWeb, :router

  import Surface.Catalogue.Router
  @env Mix.env()

  ...

  if @env == :dev do
    scope "/" do
      pipe_through :browser
      surface_catalogue "/catalogue"
    end
  end
```

## Your Environment
Surface: v0.11.1
LiveView: v0.19.0
Elixir: v1.14

**Comment by tiagoefmoraes** [comment]
@clsource Thanks for the report, `mix surface.init --catalogue` generates `if Mix.env() == :dev do` at the module level (compile time) exactly as your suggested fix.

Did you run into any errors trying to run the original code? Or changed the Router somehow? Can you share more details to reproduce the error?

**Comment by clsource** [comment]
Thanks. Yes was just a misunderstanding :)
Seems everything is fine .
