### ISSUE TITLE
error: module Surface.Components.Form.Inputs is not loaded and could not be found. This may be happening because the module you are trying to load directly or indirectly depends on the current module<Description>

### ISSUE THREAD

**Issue by mxrguspxrt** [surface-ui/surface#741]
I could not find manual how to fix this.

**Comment by VictorGaiva** [comment]
How is your `mix.exs` setup? Did you add surface as a dependency using `github`?

**Comment by tiagoefmoraes** [comment]
`:surface` `0.12.0` and `:surface_form_helpers` were released today organizing the usage of Form components, please check their changelogs for instructions.
