### ISSUE TITLE
error: undefined function date_select/3 in v0.11.4

### ISSUE THREAD

**Issue by noozo** [surface-ui/surface#747]
Is it just my env or version 0.11.4 already removed the form functions to the new library, even though that one is not in hex yet?

```
ssl_verify_fun 1.1.7
  statistics 0.6.3
  surface 0.11.4
  sweet_xml 0.7.4
  swoosh 1.16.4
  table_rex 4.0.0
```

```
error: undefined function datetime_select/3 (expected Surface.Components.Form.DateTimeSelect to define such a function or for it to be imported, but none are available)
    │
 89 │     ~F[{datetime_select(@form, @field, @opts)}]
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    │
    └─ lib/surface/components/form/datetime_select.ex:89: Surface.Components.Form.DateTimeSelect.render/1


== Compilation error in file lib/surface/components/form/datetime_select.ex ==
** (CompileError) lib/surface/components/form/datetime_select.ex: cannot compile module Surface.Components.Form.DateTimeSelect (errors have been logged)

    error: undefined function date_select/3 (expected Surface.Components.Form.DateSelect to define such a function or for it to be imported, but none are available)
    │
 77 │     ~F[{date_select(@form, @field, @opts)}]
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    │
    └─ lib/surface/components/form/date_select.ex:77: Surface.Components.Form.DateSelect.render/1
```

**Comment by tiagoefmoraes** [comment]
Form removal is just on main. v0.11.4 still has Form components (https://hexdocs.pm/surface/0.11.4/Surface.Components.Form.html) `datetime_select` if from phoenix_html (https://hexdocs.pm/phoenix_html/3.3.3/Phoenix.HTML.Form.html#datetime_select/3)

**Comment by sarat1669** [comment]
How do I get started with surface? it is throwing the same error when I initialize a new project

**Comment by tiagoefmoraes** [comment]
@noozo `datetime_select` and `date_select` are functions from `phoenix_html ~> 3.3` that were [extracted to `phoenix_html_helpers`](https://github.com/phoenixframework/phoenix_html/blob/main/CHANGELOG.md#v400-2023-12-19) on `phoenix_html 4.0.0`

Not sure how you didn't see an error like: 
```
Because surface >= 0.11.2 and < 0.12.0 depends on phoenix_html ~> 3.3.1 and your app depends on phoenix_html 4.0.0, surface >= 0.11.2 and < 0.12.0 is forbidden.
So, because your app depends on surface 0.11.4, version solving failed.
```

`:surface` `0.12.0` has being released removing the direct dependency on `:phoenix_html` because the form components were extracted. If you still need the old `Form` components you can check [`:surface_form_helpers`](https://hex.pm/packages/surface_form_helpers).

**Comment by tiagoefmoraes** [comment]
> How do I get started with surface? it is throwing the same error when I initialize a new project

@sarat1669, the best way is to follow Surface's [Getting Started](https://surface-ui.org/getting_started) guide. If you have any questions please reach us on [Elixir's slack #surface channel](https://elixir-lang.slack.com/archives/C01220C92QM), if you need an invite you can get one [here](https://elixir-slack.community/).

Please note that `mix surface.init` is compatible with `phx_new` `1.7.10` and to create a new project you'll need to install `phx_new` with `mix archive.install hex phx_new 1.7.10`, it may work on newer versions but you'll need to manually patch some files.
