### ISSUE TITLE
Is Surface actively maintained?

### ISSUE THREAD

**Issue by ramyma** [surface-ui/surface#751]
First of all, I would like to express my admiration of everything this project has achieved and the potential it holds.
 
I'm wondering what's the state of Surface, will it get updates? Will it work with live view 1.x / rc?
Is there a release plan or some sort of a road map?

Coming from more established frontend libraries (in the JS realm), there're a lot of expectation and high hopes.

@msaraiva would you be so kind to shed some light here.

Cheers!

**Comment by mudspot** [comment]
@ramyma LV 1.x works fine for me.

just do `{:phoenix_live_view, "~> 1.0.0-rc.6", override: true}` in your mix.exs

**Comment by msaraiva** [comment]
Hi @ramyma! 

Yes, it's been maintained. We have just released `v0.11.5` and we're working on `v0.12` right now. Most of the work that have been done for those versions are related to compatibility with LV and other related libs.
