### ISSUE TITLE
Compile error protocol String.Chars not implemented for {15, 41} of type Tuple

### ISSUE THREAD

**Issue by nottewae** [surface-ui/surface#758]
## Describe the bug
When compiling a mix project, I see this:
` $mix compile --verbose --tracer --profile --all-warning ` 

** (Protocol.UndefinedError) protocol String.Chars not implemented for {15, 41} of type Tuple
    (elixir 1.17.3) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir 1.17.3) lib/string/chars.ex:22: String.Chars.to_string/1
    (elixir 1.17.3) lib/exception.ex:769: Exception.format_file_line/3
    (elixir 1.17.3) lib/exception.ex:638: Exception.format_stacktrace_entry/1
    (elixir 1.17.3) src/elixir_errors.erl:79: :elixir_errors."-print_diagnostic/2-lc$^0/1-0-"/1
    (elixir 1.17.3) src/elixir_errors.erl:79: :elixir_errors.print_diagnostic/2
    (elixir 1.17.3) src/elixir_errors.erl:106: :elixir_errors.emit_diagnostic/6
    (surface 0.12.0) lib/mix/tasks/compile/surface.ex:200: anonymous fn/2 in Mix.Tasks.Compile.Surface.print_diagnostics/1

## How to reproduce it
1. Project with Surface. and LiveView components
2. Insert any 2 live routes, one to LiveView component, one to Surface LiveComponent in some scope
I dont sure for this reproduce method, but in my case this is true.

## The behavior you expected
Correct handling of any error
## Your Environment
Surface: v0.12.0
LiveView: v1.0.0-rc.7
Elixir: v1.17.3

**Comment by nottewae** [comment]
I change deps/surface/lib/mix/tasks/compile/surface.ex
200 line number
print_diagnostics/1
```defp print_diagnostics(diagnostics) do

    for %Diagnostic{message: message, severity: severity, file: file, position: position} <- diagnostics do
      position = if is_tuple(position) do
        {p, _} = position
        p
      else
        position
      end
      print_diagnostic(message, severity, file, position)
    end
  end```
then  `mix deps.compile surface --force`
It saved me.

**Comment by msaraiva** [comment]
Hey @nottewae!

Thanks for reporting the issue. This has already been fixed on `main`. 

We should be releasing a new version with this fix by the end of the week.
